// lib/questions/coding-ai-grade6.ts
const codingAiGrade6Questions = [
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "At a Seattle school, a student codes a sequence to help a T-Rex organize fossils 5 times in a row—what coding concept is this?",
    options: ["A) Loop", "B) Variable", "C) Condition", "D) Function"],
    correctAnswer: "A",
    hint: "Think about a coding concept that repeats actions multiple times.",
    correctAnswerExplanation:
      "A loop is a coding concept that repeats a set of instructions multiple times, like organizing fossils 5 times. It helps the T-Rex complete the task efficiently without writing the same code over and over.",
    incorrectAnswersExplanation: {
      B: "A variable stores data, like the number of fossils, but doesn’t repeat actions.",
      C: "A condition checks if something is true, like ‘if fossils are found,’ but doesn’t repeat.",
      D: "A function is a reusable block of code, not specifically for repeating tasks.",
    },
    difficulty: "Medium",
    tags: ["algorithms", "coding", "loops"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Texas writes a program to help a dog sort bones by size—what is the best algorithm to use?",
    options: [
      "A) Sorting algorithm",
      "B) Search algorithm",
      "C) Loop algorithm",
      "D) Debug algorithm",
    ],
    correctAnswer: "A",
    hint: "Consider what kind of algorithm arranges items in order, like from smallest to largest.",
    correctAnswerExplanation:
      "A sorting algorithm arranges items, like bones, in a specific order (smallest to largest). It’s perfect for this task because it organizes data systematically.",
    incorrectAnswersExplanation: {
      B: "A search algorithm finds specific items, not sorts them.",
      C: "There’s no such thing as a loop algorithm; loops are part of algorithms.",
      D: "Debugging fixes errors, not sorts data.",
    },
    difficulty: "Hard",
    tags: ["algorithms", "coding", "sorting"],
    timeEstimate: 90,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "In a coding club, a student makes a dinosaur dance 3 times using a sequence—what is this sequence called?",
    options: ["A) Algorithm", "B) Variable", "C) Bug", "D) Output"],
    correctAnswer: "A",
    hint: "Think about a step-by-step plan that tells the dinosaur how to dance.",
    correctAnswerExplanation:
      "An algorithm is a set of step-by-step instructions, like telling the dinosaur to dance 3 times. It’s like a recipe for coding tasks.",
    incorrectAnswersExplanation: {
      B: "A variable holds data, like the number of dances, not the steps.",
      C: "A bug is an error in code, not a sequence.",
      D: "Output is what the program shows, like the dance, not the plan.",
    },
    difficulty: "Medium",
    tags: ["algorithms", "coding", "sequences"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "A wolf in a coding class writes an algorithm to count how many howls it makes—what should the algorithm include?",
    options: [
      "A) A loop to count each howl",
      "B) A condition to stop the program",
      "C) A variable to store the wolf’s name",
      "D) A function to print the wolf’s picture",
    ],
    correctAnswer: "A",
    hint: "Think about what repeats to keep track of multiple howls.",
    correctAnswerExplanation:
      "A loop in the algorithm repeats to count each howl, adding to a total. This makes it easy to track the number of howls accurately.",
    incorrectAnswersExplanation: {
      B: "A condition might stop the program but doesn’t count howls.",
      C: "The wolf’s name doesn’t help count howls.",
      D: "Printing a picture is unrelated to counting howls.",
    },
    difficulty: "Medium",
    tags: ["algorithms", "coding", "loops"],
    timeEstimate: 60,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "At a California school, a student codes a program to help a T-Rex choose the biggest fossil—what algorithm type is best?",
    options: [
      "A) Search algorithm",
      "B) Sorting algorithm",
      "C) Loop algorithm",
      "D) Debug algorithm",
    ],
    correctAnswer: "A",
    hint: "Think about finding one specific item, like the biggest fossil.",
    correctAnswerExplanation:
      "A search algorithm looks through data to find a specific item, like the biggest fossil. It’s perfect for this task because it checks each fossil to find the largest one.",
    incorrectAnswersExplanation: {
      B: "A sorting algorithm organizes items, not finds one.",
      C: "Loop algorithm isn’t a real term; loops are part of algorithms.",
      D: "Debugging fixes code, not finds items.",
    },
    difficulty: "Hard",
    tags: ["algorithms", "coding", "search"],
    timeEstimate: 90,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "A student codes a dog to bark every time it sees a wolf—what part of the algorithm makes this happen?",
    options: ["A) Condition", "B) Loop", "C) Variable", "D) Output"],
    correctAnswer: "A",
    hint: "Think about something that checks if a wolf is nearby before barking.",
    correctAnswerExplanation:
      "A condition checks if something is true, like ‘if a wolf is seen,’ then makes the dog bark. It’s a key part of the algorithm to control actions.",
    incorrectAnswersExplanation: {
      B: "A loop repeats actions but doesn’t check for wolves.",
      C: "A variable stores data, not controls barking.",
      D: "Output shows results, like barking, but doesn’t decide when.",
    },
    difficulty: "Medium",
    tags: ["algorithms", "coding", "conditions"],
    timeEstimate: 60,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "In a New York library, a student codes a program to list dinosaur books in order—what algorithm is needed?",
    options: [
      "A) Sorting algorithm",
      "B) Search algorithm",
      "C) Debug algorithm",
      "D) Input algorithm",
    ],
    correctAnswer: "A",
    hint: "Think about arranging books from A to Z or another order.",
    correctAnswerExplanation:
      "A sorting algorithm organizes items, like dinosaur books, in a specific order (e.g., alphabetically). This helps the program list them neatly.",
    incorrectAnswersExplanation: {
      B: "A search algorithm finds one book, not organizes all.",
      C: "Debugging fixes errors, not sorts books.",
      D: "Input algorithm isn’t a real term; input is data entry.",
    },
    difficulty: "Hard",
    tags: ["algorithms", "coding", "sorting"],
    timeEstimate: 90,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "A wolf codes a program to track its pack’s path—what should the algorithm do first?",
    options: [
      "A) Collect starting location data",
      "B) Print the path",
      "C) Stop the program",
      "D) Debug the code",
    ],
    correctAnswer: "A",
    hint: "Think about what the wolf needs before tracking a path.",
    correctAnswerExplanation:
      "The algorithm needs to collect the starting location data first to know where the pack begins. This is the first step in tracking their path accurately.",
    incorrectAnswersExplanation: {
      B: "Printing the path comes after tracking, not first.",
      C: "Stopping the program ends it, not starts tracking.",
      D: "Debugging fixes errors after coding, not starts the algorithm.",
    },
    difficulty: "Medium",
    tags: ["algorithms", "coding", "data"],
    timeEstimate: 60,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Florida codes a dinosaur to roar 10 times—what algorithm structure is best?",
    options: ["A) Loop", "B) Condition", "C) Function", "D) Variable"],
    correctAnswer: "A",
    hint: "Think about repeating the roar multiple times without writing it 10 times.",
    correctAnswerExplanation:
      "A loop repeats the instruction to roar 10 times, making the code shorter and easier. It’s the best structure for repeating actions in an algorithm.",
    incorrectAnswersExplanation: {
      B: "A condition checks something, like ‘if it’s loud,’ not repeats.",
      C: "A function groups code but doesn’t automatically repeat.",
      D: "A variable stores data, like the number of roars, not repeats.",
    },
    difficulty: "Medium",
    tags: ["algorithms", "coding", "loops"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "In a coding contest, a dog’s algorithm to fetch toys fails because it repeats too many times—what should the student adjust?",
    options: [
      "A) Loop limit",
      "B) Variable name",
      "C) Output text",
      "D) Function name",
    ],
    correctAnswer: "A",
    hint: "Think about what controls how many times the fetch repeats.",
    correctAnswerExplanation:
      "The loop limit controls how many times the algorithm repeats fetching toys. Adjusting it fixes the problem by setting the correct number of repeats.",
    incorrectAnswersExplanation: {
      B: "A variable name doesn’t affect how many times the loop runs.",
      C: "Output text shows results, not controls repeats.",
      D: "A function name doesn’t change the loop’s behavior.",
    },
    difficulty: "Hard",
    tags: ["algorithms", "coding", "loops"],
    timeEstimate: 90,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "A student codes a T-Rex to stomp in a pattern: left, right, left—what is this pattern called?",
    options: ["A) Sequence", "B) Loop", "C) Condition", "D) Variable"],
    correctAnswer: "A",
    hint: "Think about a list of steps that happen in order.",
    correctAnswerExplanation:
      "A sequence is a specific order of steps, like left, right, left for the T-Rex’s stomps. It tells the program exactly what to do in that order.",
    incorrectAnswersExplanation: {
      B: "A loop repeats steps, not sets their order.",
      C: "A condition checks something, not defines a pattern.",
      D: "A variable stores data, not a pattern.",
    },
    difficulty: "Medium",
    tags: ["algorithms", "coding", "sequences"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "A wolf codes a program to find the fastest path to its den—what algorithm type helps?",
    options: [
      "A) Pathfinding algorithm",
      "B) Sorting algorithm",
      "C) Debug algorithm",
      "D) Loop algorithm",
    ],
    correctAnswer: "A",
    hint: "Think about an algorithm that finds the best route from one place to another.",
    correctAnswerExplanation:
      "A pathfinding algorithm finds the best route, like the fastest path to the den. It checks possible paths and picks the most efficient one.",
    incorrectAnswersExplanation: {
      B: "A sorting algorithm organizes data, not finds paths.",
      C: "Debugging fixes errors, not finds routes.",
      D: "Loop algorithm isn’t a real term; loops are part of algorithms.",
    },
    difficulty: "Hard",
    tags: ["algorithms", "coding", "pathfinding"],
    timeEstimate: 90,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Chicago codes a dog to wag its tail 4 times—what algorithm structure is used?",
    options: ["A) Loop", "B) Condition", "C) Variable", "D) Output"],
    correctAnswer: "A",
    hint: "Think about repeating the wag action a set number of times.",
    correctAnswerExplanation:
      "A loop repeats the tail wag 4 times, making the code simple and efficient. It’s the best choice for repeating a task in an algorithm.",
    incorrectAnswersExplanation: {
      B: "A condition checks something, like ‘if the dog is happy,’ not repeats.",
      C: "A variable stores data, like the number of wags, not repeats.",
      D: "Output shows the result, like wagging, not controls repetition.",
    },
    difficulty: "Medium",
    tags: ["algorithms", "coding", "loops"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "In a school project, a dinosaur’s algorithm to collect gems fails because it skips some—what should the student check?",
    options: [
      "A) Loop conditions",
      "B) Output text",
      "C) Variable name",
      "D) Function name",
    ],
    correctAnswer: "A",
    hint: "Think about what controls whether the loop collects all gems.",
    correctAnswerExplanation:
      "Loop conditions determine when the loop stops, so checking them ensures all gems are collected. If the condition is wrong, the loop might skip gems.",
    incorrectAnswersExplanation: {
      B: "Output text shows results, not controls gem collection.",
      C: "A variable name doesn’t affect the loop’s behavior.",
      D: "A function name doesn’t fix skipping gems.",
    },
    difficulty: "Hard",
    tags: ["algorithms", "coding", "loops"],
    timeEstimate: 90,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "A student codes a wolf to howl at night —what algorithm step checks if it’s nighttime?",
    options: ["A) Condition", "B) Loop", "C) Variable", "D) Output"],
    correctAnswer: "A",
    hint: "Think about something that checks a situation before howling.",
    correctAnswerExplanation:
      "A condition checks if it’s nighttime, like ‘if it’s dark,’ then makes the wolf howl. It ensures the algorithm only acts when the condition is true.",
    incorrectAnswersExplanation: {
      B: "A loop repeats actions, not checks for nighttime.",
      C: "A variable stores data, like the time, not checks conditions.",
      D: "Output shows the howl, not decides when to howl.",
    },
    difficulty: "Medium",
    tags: ["algorithms", "coding", "conditions"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "A T-Rex codes a program to count its footsteps—what algorithm structure tracks the total?",
    options: ["A) Variable", "B) Loop", "C) Condition", "D) Function"],
    correctAnswer: "A",
    hint: "Think about something that stores the number of footsteps.",
    correctAnswerExplanation:
      "A variable stores the total number of footsteps, increasing with each step. It’s essential for the algorithm to keep track of the count.",
    incorrectAnswersExplanation: {
      B: "A loop repeats counting but doesn’t store the total.",
      C: "A condition checks something, not stores data.",
      D: "A function groups code but doesn’t hold the count.",
    },
    difficulty: "Medium",
    tags: ["algorithms", "coding", "variables"],
    timeEstimate: 60,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "In a coding camp, a student’s algorithm to sort dinosaur eggs by color fails—what should they check?",
    options: [
      "A) Sorting logic",
      "B) Output text",
      "C) Loop name",
      "D) Variable type",
    ],
    correctAnswer: "A",
    hint: "Think about the part of the algorithm that organizes the eggs.",
    correctAnswerExplanation:
      "The sorting logic determines how eggs are arranged by color, so checking it fixes the algorithm. If the logic is wrong, the eggs won’t sort correctly.",
    incorrectAnswersExplanation: {
      B: "Output text shows results, not sorts eggs.",
      C: "Loops don’t have names, and they don’t sort directly.",
      D: "Variable type might store colors but doesn’t control sorting.",
    },
    difficulty: "Hard",
    tags: ["algorithms", "coding", "sorting"],
    timeEstimate: 90,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "A dog in a coding class writes an algorithm to dig holes—what should it do after digging each hole?",
    options: [
      "A) Update the hole count",
      "B) Stop the program",
      "C) Print the dog’s name",
      "D) Change the loop name",
    ],
    correctAnswer: "A",
    hint: "Think about keeping track of how many holes are dug.",
    correctAnswerExplanation:
      "Updating the hole count after each dig tracks the total number of holes. This is a key step in the algorithm to know how many were dug.",
    incorrectAnswersExplanation: {
      B: "Stopping the program ends it, not tracks holes.",
      C: "Printing the dog’s name doesn’t count holes.",
      D: "Loops don’t have names, and changing one doesn’t track holes.",
    },
    difficulty: "Medium",
    tags: ["algorithms", "coding", "variables"],
    timeEstimate: 60,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "A student codes a wolf to run in a circle 5 times—what algorithm structure is used?",
    options: ["A) Loop", "B) Condition", "C) Variable", "D) Output"],
    correctAnswer: "A",
    hint: "Think about repeating the running action multiple times.",
    correctAnswerExplanation:
      "A loop repeats the wolf’s running action 5 times, making the code efficient. It’s the best structure for repeating tasks in an algorithm.",
    incorrectAnswersExplanation: {
      B: "A condition checks something, like ‘if it’s safe,’ not repeats.",
      C: "A variable stores data, like the number of runs, not repeats.",
      D: "Output shows the result, like running, not controls repetition.",
    },
    difficulty: "Medium",
    tags: ["algorithms", "coding", "loops"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Algorithms",
    grade: 6,
    questionType: "MC",
    question:
      "A T-Rex’s algorithm to eat plants fails because it eats too many—what should the student fix?",
    options: [
      "A) Loop limit",
      "B) Output text",
      "C) Variable name",
      "D) Function name",
    ],
    correctAnswer: "A",
    hint: "Think about what controls how many plants the T-Rex eats.",
    correctAnswerExplanation:
      "The loop limit controls how many times the T-Rex eats plants, so fixing it stops overeating. It ensures the algorithm runs the right number of times.",
    incorrectAnswersExplanation: {
      B: "Output text shows results, not controls eating.",
      C: "A variable name doesn’t affect the loop’s behavior.",
      D: "A function name doesn’t fix the eating amount.",
    },
    difficulty: "Hard",
    tags: ["algorithms", "coding", "loops"],
    timeEstimate: 90,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "During a science fair, a wolf says, ‘If I see a dinosaur, I’ll run’—what type of statement is this?",
    options: [
      "A) Conditional statement",
      "B) Loop statement",
      "C) Variable statement",
      "D) Output statement",
    ],
    correctAnswer: "A",
    hint: "Think about a statement that checks something before acting.",
    correctAnswerExplanation:
      "A conditional statement checks if something is true, like ‘if I see a dinosaur,’ then does something, like run. It helps the wolf decide what to do.",
    incorrectAnswersExplanation: {
      B: "A loop statement repeats actions, not checks for dinosaurs.",
      C: "A variable statement stores data, not decides actions.",
      D: "An output statement shows results, not checks conditions.",
    },
    difficulty: "Medium",
    tags: ["logic", "coding", "conditionals"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Ohio codes a dog to bark if it’s raining—what logic structure is used?",
    options: ["A) If-then statement", "B) Loop", "C) Variable", "D) Function"],
    correctAnswer: "A",
    hint: "Think about a structure that checks the weather before barking.",
    correctAnswerExplanation:
      "An if-then statement checks if it’s raining, then makes the dog bark. It’s a logic structure that controls actions based on conditions.",
    incorrectAnswersExplanation: {
      B: "A loop repeats actions, not checks for rain.",
      C: "A variable stores data, like rain amount, not controls barking.",
      D: "A function groups code but doesn’t check conditions.",
    },
    difficulty: "Medium",
    tags: ["logic", "coding", "conditionals"],
    timeEstimate: 60,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A T-Rex codes: ‘If I find a plant, eat it; otherwise, keep looking’—what is the ‘otherwise’ part called?",
    options: [
      "A) Else statement",
      "B) Loop statement",
      "C) Variable statement",
      "D) Output statement",
    ],
    correctAnswer: "A",
    hint: "Think about what happens when the condition, like finding a plant, isn’t true.",
    correctAnswerExplanation:
      "An else statement runs when the condition (finding a plant) is false, so the T-Rex keeps looking. It’s part of the logic to handle alternative actions.",
    incorrectAnswersExplanation: {
      B: "A loop statement repeats actions, not handles alternatives.",
      C: "A variable statement stores data, not controls actions.",
      D: "An output statement shows results, not decides what to do.",
    },
    difficulty: "Medium",
    tags: ["logic", "coding", "conditionals"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "In a school project, a wolf’s code says: ‘If the moon is full, howl; else, sleep’—what logic controls this?",
    options: [
      "A) Conditional logic",
      "B) Loop logic",
      "C) Variable logic",
      "D) Output logic",
    ],
    correctAnswer: "A",
    hint: "Think about logic that decides between two actions based on a condition.",
    correctAnswerExplanation:
      "Conditional logic uses ‘if’ and ‘else’ to decide actions, like howling or sleeping based on the moon. It helps the wolf choose what to do.",
    incorrectAnswersExplanation: {
      B: "Loop logic repeats actions, not chooses between howl or sleep.",
      C: "Variable logic isn’t a term; variables store data.",
      D: "Output logic shows results, not decides actions.",
    },
    difficulty: "Medium",
    tags: ["logic", "coding", "conditionals"],
    timeEstimate: 60,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A student codes a dog to fetch a ball only if it’s red—what happens if the ball is blue?",
    options: [
      "A) The dog doesn’t fetch",
      "B) The dog fetches anyway",
      "C) The program stops",
      "D) The dog barks",
    ],
    correctAnswer: "A",
    hint: "Think about what the condition ‘if the ball is red’ means for a blue ball.",
    correctAnswerExplanation:
      "The condition checks if the ball is red, so if it’s blue, the dog doesn’t fetch. This is how conditional logic controls the dog’s actions.",
    incorrectAnswersExplanation: {
      B: "The dog only fetches for a red ball, not a blue one.",
      C: "The program doesn’t stop; it just doesn’t fetch.",
      D: "Barking isn’t part of the condition for fetching.",
    },
    difficulty: "Medium",
    tags: ["logic", "coding", "conditionals"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A T-Rex’s code says: ‘If I’m hungry, eat; else, rest’—what logic structure is this?",
    options: [
      "A) If-else statement",
      "B) Loop statement",
      "C) Variable statement",
      "D) Output statement",
    ],
    correctAnswer: "A",
    hint: "Think about a structure that chooses between two actions based on hunger.",
    correctAnswerExplanation:
      "An if-else statement checks if the T-Rex is hungry to eat, or else it rests. This logic structure decides between two possible actions.",
    incorrectAnswersExplanation: {
      B: "A loop statement repeats actions, not chooses between eat or rest.",
      C: "A variable statement stores data, not decides actions.",
      D: "An output statement shows results, not controls choices.",
    },
    difficulty: "Medium",
    tags: ["logic", "coding", "conditionals"],
    timeEstimate: 60,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Georgia codes: ‘If the dinosaur is a T-Rex, roar; else, growl’—what controls the sound?",
    options: [
      "A) Conditional logic",
      "B) Loop logic",
      "C) Variable logic",
      "D) Output logic",
    ],
    correctAnswer: "A",
    hint: "Think about logic that picks a sound based on the dinosaur type.",
    correctAnswerExplanation:
      "Conditional logic uses ‘if’ and ‘else’ to choose roaring for a T-Rex or growling for others. It controls the sound based on the condition.",
    incorrectAnswersExplanation: {
      B: "Loop logic repeats actions, not chooses sounds.",
      C: "Variable logic isn’t a term; variables store data.",
      D: "Output logic shows the sound, not decides which one.",
    },
    difficulty: "Medium",
    tags: ["logic", "coding", "conditionals"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A wolf’s code says: ‘If I’m in Minecraft and see a sheep, chase it’—what logic is used?",
    options: [
      "A) If-then statement",
      "B) Loop statement",
      "C) Variable statement",
      "D) Output statement",
    ],
    correctAnswer: "A",
    hint: "Think about a statement that checks for a sheep before chasing.",
    correctAnswerExplanation:
      "An if-then statement checks if the wolf sees a sheep, then makes it chase. This logic controls actions based on a condition.",
    incorrectAnswersExplanation: {
      B: "A loop statement repeats actions, not checks for sheep.",
      C: "A variable statement stores data, not controls chasing.",
      D: "An output statement shows results, not decides actions.",
    },
    difficulty: "Medium",
    tags: ["logic", "coding", "conditionals"],
    timeEstimate: 60,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A student codes a dog to wag its tail if it gets a treat—what happens if there’s no treat?",
    options: [
      "A) The dog doesn’t wag",
      "B) The dog wags anyway",
      "C) The program stops",
      "D) The dog barks",
    ],
    correctAnswer: "A",
    hint: "Think about what the condition ‘if there’s a treat’ means when there’s no treat.",
    correctAnswerExplanation:
      "The condition checks for a treat, so if there’s no treat, the dog doesn’t wag its tail. This is how conditional logic works to control actions.",
    incorrectAnswersExplanation: {
      B: "The dog only wags for a treat, not without one.",
      C: "The program doesn’t stop; it just doesn’t wag.",
      D: "Barking isn’t part of the condition for wagging.",
    },
    difficulty: "Medium",
    tags: ["logic", "coding", "conditionals"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A T-Rex’s code says: ‘If I see a plant, eat it; else if I see meat, eat it; else, wait’—what is this called?",
    options: [
      "A) Nested conditional",
      "B) Loop statement",
      "C) Variable statement",
      "D) Output statement",
    ],
    correctAnswer: "A",
    hint: "Think about checking multiple conditions one after another.",
    correctAnswerExplanation:
      "A nested conditional checks multiple conditions, like plant or meat, before waiting. It lets the T-Rex decide based on different possibilities.",
    incorrectAnswersExplanation: {
      B: "A loop statement repeats actions, not checks multiple conditions.",
      C: "A variable statement stores data, not controls decisions.",
      D: "An output statement shows results, not decides actions.",
    },
    difficulty: "Hard",
    tags: ["logic", "coding", "conditionals"],
    timeEstimate: 90,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A student codes: ‘If a wolf is near a river, drink; else if it’s near a forest, hunt; else, rest’—what logic is this?",
    options: [
      "A) Nested conditional logic",
      "B) Loop logic",
      "C) Variable logic",
      "D) Output logic",
    ],
    correctAnswer: "A",
    hint: "Think about logic that checks multiple places before deciding.",
    correctAnswerExplanation:
      "Nested conditional logic checks multiple conditions, like river or forest, to decide drinking, hunting, or resting. It handles different scenarios in order.",
    incorrectAnswersExplanation: {
      B: "Loop logic repeats actions, not chooses based on location.",
      C: "Variable logic isn’t a term; variables store data.",
      D: "Output logic shows results, not decides actions.",
    },
    difficulty: "Hard",
    tags: ["logic", "coding", "conditionals"],
    timeEstimate: 90,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A dog’s code says: ‘If I have a bone, chew it; else, find one’—what controls the action?",
    options: [
      "A) If-else statement",
      "B) Loop statement",
      "C) Variable statement",
      "D) Output statement",
    ],
    correctAnswer: "A",
    hint: "Think about a statement that chooses between chewing or finding a bone.",
    correctAnswerExplanation:
      "An if-else statement checks if the dog has a bone to chew, or else it finds one. This logic structure decides the dog’s action.",
    incorrectAnswersExplanation: {
      B: "A loop statement repeats actions, not chooses between chew or find.",
      C: "A variable statement stores data, not controls actions.",
      D: "An output statement shows results, not decides what to do.",
    },
    difficulty: "Medium",
    tags: ["logic", "coding", "conditionals"],
    timeEstimate: 60,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A student codes a T-Rex to roar if it’s morning or evening—what logic operator is used?",
    options: ["A) OR", "B) AND", "C) NOT", "D) IF"],
    correctAnswer: "A",
    hint: "Think about a word that combines morning or evening as options.",
    correctAnswerExplanation:
      "The OR operator checks if it’s either morning or evening to make the T-Rex roar. It allows the condition to be true for either time.",
    incorrectAnswersExplanation: {
      B: "AND requires both morning and evening, which doesn’t make sense.",
      C: "NOT reverses a condition, not combines times.",
      D: "IF is a statement, not an operator.",
    },
    difficulty: "Hard",
    tags: ["logic", "coding", "operators"],
    timeEstimate: 90,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A wolf’s code says: ‘If I’m hungry and it’s night, hunt’—what logic operator is used?",
    options: ["A) AND", "B) OR", "C) NOT", "D) ELSE"],
    correctAnswer: "A",
    hint: "Think about a word that requires both hunger and night to hunt.",
    correctAnswerExplanation:
      "The AND operator checks if the wolf is both hungry and it’s night to hunt. Both conditions must be true for the action to happen.",
    incorrectAnswersExplanation: {
      B: "OR only needs one condition, not both.",
      C: "NOT reverses a condition, not combines them.",
      D: "ELSE is a statement, not an operator.",
    },
    difficulty: "Hard",
    tags: ["logic", "coding", "operators"],
    timeEstimate: 90,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A student codes a dog to sleep if it’s not daytime—what logic operator is used?",
    options: ["A) NOT", "B) AND", "C) OR", "D) IF"],
    correctAnswer: "A",
    hint: "Think about a word that reverses the condition of daytime.",
    correctAnswerExplanation:
      "The NOT operator reverses the condition, so if it’s not daytime, the dog sleeps. It changes the condition to its opposite.",
    incorrectAnswersExplanation: {
      B: "AND combines conditions, not reverses daytime.",
      C: "OR allows multiple conditions, not reverses one.",
      D: "IF is a statement, not an operator.",
    },
    difficulty: "Hard",
    tags: ["logic", "coding", "operators"],
    timeEstimate: 90,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A T-Rex codes: ‘If I’m full, rest; else if I’m thirsty, drink; else, eat’—how many conditions are checked?",
    options: ["A) Three", "B) One", "C) Two", "D) Four"],
    correctAnswer: "A",
    hint: "Count the ‘if’ and ‘else if’ parts in the code.",
    correctAnswerExplanation:
      "The code checks three conditions: if the T-Rex is full, if it’s thirsty, and else for eating. Each condition leads to a different action.",
    incorrectAnswersExplanation: {
      B: "One is too few; there are multiple conditions.",
      C: "Two misses the third condition (else).",
      D: "Four is too many; there are only three conditions.",
    },
    difficulty: "Hard",
    tags: ["logic", "coding", "conditionals"],
    timeEstimate: 90,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A student codes a wolf to howl if it’s night or if it sees a moon—what operator combines these?",
    options: ["A) OR", "B) AND", "C) NOT", "D) ELSE"],
    correctAnswer: "A",
    hint: "Think about a word that allows howling for either condition.",
    correctAnswerExplanation:
      "The OR operator checks if it’s night or the wolf sees a moon to howl. It makes the condition true if either is met.",
    incorrectAnswersExplanation: {
      B: "AND requires both conditions, not just one.",
      C: "NOT reverses a condition, not combines them.",
      D: "ELSE is a statement, not an operator.",
    },
    difficulty: "Hard",
    tags: ["logic", "coding", "operators"],
    timeEstimate: 90,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A dog’s code says: ‘If I’m tired, sleep; else, play’—what happens if the dog is tired?",
    options: [
      "A) The dog sleeps",
      "B) The dog plays",
      "C) The program stops",
      "D) The dog barks",
    ],
    correctAnswer: "A",
    hint: "Think about what the ‘if’ condition does when the dog is tired.",
    correctAnswerExplanation:
      "The if condition checks if the dog is tired, so it sleeps. This is how conditional logic decides the action.",
    incorrectAnswersExplanation: {
      B: "Playing happens only if the dog isn’t tired (else).",
      C: "The program doesn’t stop; it follows the condition.",
      D: "Barking isn’t part of the condition.",
    },
    difficulty: "Medium",
    tags: ["logic", "coding", "conditionals"],
    timeEstimate: 60,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A student codes a T-Rex to run if it’s being chased and it’s daytime—what operator is used?",
    options: ["A) AND", "B) OR", "C) NOT", "D) IF"],
    correctAnswer: "A",
    hint: "Think about a word that requires both being chased and daytime.",
    correctAnswerExplanation:
      "The AND operator checks if the T-Rex is both being chased and it’s daytime to run. Both conditions must be true for the action.",
    incorrectAnswersExplanation: {
      B: "OR only needs one condition, not both.",
      C: "NOT reverses a condition, not combines them.",
      D: "IF is a statement, not an operator.",
    },
    difficulty: "Hard",
    tags: ["logic", "coding", "operators"],
    timeEstimate: 90,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Logic",
    grade: 6,
    questionType: "MC",
    question:
      "A wolf’s code says: ‘If I’m not alone, howl’—what logic operator is used?",
    options: ["A) NOT", "B) AND", "C) OR", "D) ELSE"],
    correctAnswer: "A",
    hint: "Think about a word that reverses the condition of being alone.",
    correctAnswerExplanation:
      "The NOT operator reverses the condition, so if the wolf isn’t alone, it howls. It changes the condition to its opposite.",
    incorrectAnswersExplanation: {
      B: "AND combines conditions, not reverses being alone.",
      C: "OR allows multiple conditions, not reverses one.",
      D: "ELSE is a statement, not an operator.",
    },
    difficulty: "Hard",
    tags: ["logic", "coding", "operators"],
    timeEstimate: 90,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A wolf debugs a program for a school project, but the dog barks too many times—what should the wolf check?",
    options: [
      "A) Loop limit",
      "B) Variable name",
      "C) Output text",
      "D) Function name",
    ],
    correctAnswer: "A",
    hint: "Think about what controls how many times the dog barks.",
    correctAnswerExplanation:
      "The loop limit controls how many times the barking repeats, so checking it fixes the issue. If it’s set too high, the dog barks too much.",
    incorrectAnswersExplanation: {
      B: "A variable name doesn’t affect how many barks happen.",
      C: "Output text shows the bark, not controls its count.",
      D: "A function name doesn’t change the loop’s behavior.",
    },
    difficulty: "Medium",
    tags: ["debugging", "coding", "loops"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A student’s T-Rex program makes it roar when it shouldn’t—what should they check?",
    options: [
      "A) Condition logic",
      "B) Loop count",
      "C) Variable type",
      "D) Output color",
    ],
    correctAnswer: "A",
    hint: "Think about what decides when the T-Rex roars.",
    correctAnswerExplanation:
      "The condition logic controls when the T-Rex roars, so checking it fixes the issue. If the condition is wrong, it roars at the wrong time.",
    incorrectAnswersExplanation: {
      B: "Loop count affects repeats, not when roaring happens.",
      C: "Variable type stores data, not controls roaring.",
      D: "Output color changes appearance, not roaring logic.",
    },
    difficulty: "Medium",
    tags: ["debugging", "coding", "conditionals"],
    timeEstimate: 60,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A dog’s program to fetch toys stops too soon—what should the student check?",
    options: [
      "A) Loop condition",
      "B) Output text",
      "C) Function name",
      "D) Variable name",
    ],
    correctAnswer: "A",
    hint: "Think about what controls when the fetching stops.",
    correctAnswerExplanation:
      "The loop condition decides when the loop stops, so checking it ensures the dog fetches all toys. If it’s wrong, the program stops too early.",
    incorrectAnswersExplanation: {
      B: "Output text shows results, not controls stopping.",
      C: "A function name doesn’t affect the loop’s behavior.",
      D: "A variable name doesn’t change when the loop stops.",
    },
    difficulty: "Medium",
    tags: ["debugging", "coding", "loops"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A wolf’s program to howl at night doesn’t work—what should the student check first?",
    options: [
      "A) Condition for night",
      "B) Output sound",
      "C) Variable name",
      "D) Loop count",
    ],
    correctAnswer: "A",
    hint: "Think about what decides if the wolf howls at night.",
    correctAnswerExplanation:
      "The condition for night controls when the wolf howls, so checking it first finds the error. If it’s wrong, the howling won’t happen.",
    incorrectAnswersExplanation: {
      B: "Output sound plays the howl but doesn’t decide when.",
      C: "A variable name doesn’t affect the howling condition.",
      D: "Loop count affects repeats, not the night condition.",
    },
    difficulty: "Medium",
    tags: ["debugging", "coding", "conditionals"],
    timeEstimate: 60,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A T-Rex’s program to count fossils shows the wrong number—what should the student check?",
    options: [
      "A) Variable update",
      "B) Output color",
      "C) Function name",
      "D) Loop name",
    ],
    correctAnswer: "A",
    hint: "Think about what keeps track of the fossil count.",
    correctAnswerExplanation:
      "The variable update adds to the fossil count, so checking it ensures the right number. If it’s wrong, the count will be off.",
    incorrectAnswersExplanation: {
      B: "Output color changes appearance, not the count.",
      C: "A function name doesn’t affect the count.",
      D: "Loops don’t have names, and they don’t store counts.",
    },
    difficulty: "Medium",
    tags: ["debugging", "coding", "variables"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A student’s dog program barks even when it’s quiet—what should they fix?",
    options: [
      "A) Condition logic",
      "B) Loop count",
      "C) Variable type",
      "D) Output sound",
    ],
    correctAnswer: "A",
    hint: "Think about what controls when the dog barks.",
    correctAnswerExplanation:
      "The condition logic decides when the dog barks, so fixing it ensures barking only when it’s not quiet. If it’s wrong, the dog barks at the wrong time.",
    incorrectAnswersExplanation: {
      B: "Loop count affects repeats, not when barking happens.",
      C: "Variable type stores data, not controls barking.",
      D: "Output sound plays the bark, not decides when.",
    },
    difficulty: "Medium",
    tags: ["debugging", "coding", "conditionals"],
    timeEstimate: 60,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A wolf’s program to run from danger stops too soon—what should the student check?",
    options: [
      "A) Loop condition",
      "B) Output text",
      "C) Function name",
      "D) Variable name",
    ],
    correctAnswer: "A",
    hint: "Think about what controls when the running stops.",
    correctAnswerExplanation:
      "The loop condition decides when the wolf stops running, so checking it fixes the issue. If it’s wrong, the program stops too early.",
    incorrectAnswersExplanation: {
      B: "Output text shows results, not controls stopping.",
      C: "A function name doesn’t affect the loop’s behavior.",
      D: "A variable name doesn’t change when the loop stops.",
    },
    difficulty: "Medium",
    tags: ["debugging", "coding", "loops"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A T-Rex’s program to eat plants skips some plants—what should the student check?",
    options: [
      "A) Loop logic",
      "B) Output color",
      "C) Variable name",
      "D) Function name",
    ],
    correctAnswer: "A",
    hint: "Think about what controls eating all the plants.",
    correctAnswerExplanation:
      "The loop logic controls how the T-Rex eats plants, so checking it ensures no plants are skipped. If it’s wrong, the loop might miss some.",
    incorrectAnswersExplanation: {
      B: "Output color changes appearance, not eating logic.",
      C: "A variable name doesn’t affect the loop’s behavior.",
      D: "A function name doesn’t fix skipping plants.",
    },
    difficulty: "Hard",
    tags: ["debugging", "coding", "loops"],
    timeEstimate: 90,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A dog’s program to wag its tail shows no movement—what should the student check first?",
    options: [
      "A) Output command",
      "B) Loop name",
      "C) Variable type",
      "D) Function name",
    ],
    correctAnswer: "A",
    hint: "Think about what makes the tail wag appear on the screen.",
    correctAnswerExplanation:
      "The output command shows the tail wagging, so checking it first ensures the movement appears. If it’s missing or wrong, there’s no wag.",
    incorrectAnswersExplanation: {
      B: "Loops don’t have names, and they don’t show movement.",
      C: "Variable type stores data, not controls output.",
      D: "A function name doesn’t affect the output.",
    },
    difficulty: "Medium",
    tags: ["debugging", "coding", "output"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A student’s wolf program howls at the wrong time—what should they fix?",
    options: [
      "A) Condition logic",
      "B) Loop count",
      "C) Variable type",
      "D) Output sound",
    ],
    correctAnswer: "A",
    hint: "Think about what controls when the wolf howls.",
    correctAnswerExplanation:
      "The condition logic decides when the wolf howls, so fixing it ensures howling at the right time. If it’s wrong, the timing is off.",
    incorrectAnswersExplanation: {
      B: "Loop count affects repeats, not when howling happens.",
      C: "Variable type stores data, not controls timing.",
      D: "Output sound plays the howl, not decides when.",
    },
    difficulty: "Medium",
    tags: ["debugging", "coding", "conditionals"],
    timeEstimate: 60,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A T-Rex’s program to count steps counts too many—what should the student check?",
    options: [
      "A) Variable update",
      "B) Output text",
      "C) Function name",
      "D) Loop name",
    ],
    correctAnswer: "A",
    hint: "Think about what adds to the step count.",
    correctAnswerExplanation:
      "The variable update adds to the step count, so checking it ensures the right number. If it’s adding too much, the count is wrong.",
    incorrectAnswersExplanation: {
      B: "Output text shows the count, not adds to it.",
      C: "A function name doesn’t affect the count.",
      D: "Loops don’t have names, and they don’t store counts.",
    },
    difficulty: "Hard",
    tags: ["debugging", "coding", "variables"],
    timeEstimate: 90,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A dog’s program to bark at strangers doesn’t bark—what should the student check?",
    options: [
      "A) Condition for strangers",
      "B) Output color",
      "C) Variable name",
      "D) Loop count",
    ],
    correctAnswer: "A",
    hint: "Think about what decides if the dog barks at strangers.",
    correctAnswerExplanation:
      "The condition for strangers controls when the dog barks, so checking it fixes the issue. If it’s wrong, the barking won’t happen.",
    incorrectAnswersExplanation: {
      B: "Output color changes appearance, not barking logic.",
      C: "A variable name doesn’t affect the barking condition.",
      D: "Loop count affects repeats, not the stranger condition.",
    },
    difficulty: "Hard",
    tags: ["debugging", "coding", "conditionals"],
    timeEstimate: 90,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A wolf’s program to chase rabbits runs forever—what should the student fix?",
    options: [
      "A) Loop condition",
      "B) Output text",
      "C) Function name",
      "D) Variable name",
    ],
    correctAnswer: "A",
    hint: "Think about what controls when the chasing stops.",
    correctAnswerExplanation:
      "The loop condition decides when the chasing stops, so fixing it prevents the program from running forever. If it’s missing or wrong, the loop never ends.",
    incorrectAnswersExplanation: {
      B: "Output text shows results, not controls stopping.",
      C: "A function name doesn’t affect the loop’s behavior.",
      D: "A variable name doesn’t change when the loop stops.",
    },
    difficulty: "Hard",
    tags: ["debugging", "coding", "loops"],
    timeEstimate: 90,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A T-Rex’s program to roar at enemies doesn’t roar—what should the student check?",
    options: [
      "A) Condition for enemies",
      "B) Output sound",
      "C) Variable type",
      "D) Loop name",
    ],
    correctAnswer: "A",
    hint: "Think about what decides if the T-Rex roars at enemies.",
    correctAnswerExplanation:
      "The condition for enemies controls when the T-Rex roars, so checking it fixes the issue. If it’s wrong, the roaring won’t happen.",
    incorrectAnswersExplanation: {
      B: "Output sound plays the roar but doesn’t decide when.",
      C: "Variable type stores data, not controls roaring.",
      D: "Loops don’t have names, and they don’t control roaring.",
    },
    difficulty: "Hard",
    tags: ["debugging", "coding", "conditionals"],
    timeEstimate: 90,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A dog’s program to dig holes digs too many—what should the student check?",
    options: [
      "A) Loop limit",
      "B) Output text",
      "C) Function name",
      "D) Variable name",
    ],
    correctAnswer: "A",
    hint: "Think about what controls how many holes are dug.",
    correctAnswerExplanation:
      "The loop limit controls how many holes the dog digs, so checking it fixes the issue. If it’s too high, the dog digs too many holes.",
    incorrectAnswersExplanation: {
      B: "Output text shows results, not controls digging.",
      C: "A function name doesn’t affect the loop’s behavior.",
      D: "A variable name doesn’t change the loop limit.",
    },
    difficulty: "Hard",
    tags: ["debugging", "coding", "loops"],
    timeEstimate: 90,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A wolf’s program to count pack members shows zero—what should the student check?",
    options: [
      "A) Variable update",
      "B) Output color",
      "C) Function name",
      "D) Loop name",
    ],
    correctAnswer: "A",
    " signalling": "Think about what adds to the pack member count.",
    correctAnswerExplanation:
      "The variable update adds to the pack member count, so checking it ensures the right number. If it’s missing or wrong, the count stays zero.",
    incorrectAnswersExplanation: {
      B: "Output color changes appearance, not the count.",
      C: "A function name doesn’t affect the count.",
      D: "Loops don’t have names, and they don’t store counts.",
    },
    difficulty: "Hard",
    tags: ["debugging", "coding", "variables"],
    timeEstimate: 90,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Debugging",
    grade: 6,
    questionType: "MC",
    question:
      "A T-Rex’s program to chase prey runs in circles—what should the student check?",
    options: [
      "A) Loop logic",
      "B) Output text",
      "C) Variable name",
      "D) Function name",
    ],
    correctAnswer: "A",
    hint: "Think about what controls the chasing path.",
    correctAnswerExplanation:
      "The loop logic controls how the T-Rex chases, so checking it fixes the circling issue. If it’s wrong, the loop might repeat incorrectly.",
    incorrectAnswersExplanation: {
      B: "Output text shows results, not controls chasing.",
      C: "A variable name doesn’t affect the loop’s behavior.",
      D: "A function name doesn’t fix the chasing path.",
    },
    difficulty: "Hard",
    tags: ["debugging", "coding", "loops"],
    timeEstimate: 90,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Basic Programming Concepts",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Florida codes a dog to bark 3 times—what coding concept repeats the bark?",
    options: ["A) Loop", "B) Variable", "C) Condition", "D) Function"],
    correctAnswer: "A",
    hint: "Think about a concept that repeats an action multiple times.",
    correctAnswerExplanation:
      "A loop repeats the barking action 3 times, making the code efficient. It’s a basic programming concept for repeating tasks.",
    incorrectAnswersExplanation: {
      B: "A variable stores data, like the number of barks, not repeats.",
      C: "A condition checks something, like ‘if it’s loud,’ not repeats.",
      D: "A function groups code but doesn’t automatically repeat.",
    },
    difficulty: "Medium",
    tags: ["programming", "coding", "loops"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Basic Programming Concepts",
    grade: 6,
    questionType: "MC",
    question:
      "A T-Rex stores the number of fossils it found in a program—what concept is this?",
    options: ["A) Variable", "B) Loop", "C) Condition", "D) Output"],
    correctAnswer: "A",
    hint: "Think about something that holds data, like a number.",
    correctAnswerExplanation:
      "A variable stores data, like the number of fossils, for the program to use. It’s a basic programming concept for keeping track of information.",
    incorrectAnswersExplanation: {
      B: "A loop repeats actions, not stores data.",
      C: "A condition checks something, not holds data.",
      D: "Output shows data, not stores it.",
    },
    difficulty: "Medium",
    tags: ["programming", "coding", "variables"],
    timeEstimate: 60,
    webLink: "https://scratch.mit.edu/projects/editor/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Coding-AI",
    topic: "Basic Programming Concepts",
    grade: 6,
    questionType: "MC",
    question:
      "A wolf codes a program to howl if it sees a moon—what concept checks for the moon?",
    options: ["A) Condition", "B) Loop", "C) Variable", "D) Function"],
    correctAnswer: "A",
    hint: "Think about something that checks if a situation is true.",
    correctAnswerExplanation:
      "A condition checks if the moon is visible, then makes the wolf howl. It’s a basic programming concept for making decisions.",
    incorrectAnswersExplanation: {
      B: "A loop repeats actions, not checks for moons.",
      C: "A variable stores data, not checks conditions.",
      D: "A function groups code but doesn’t check for moons.",
    },
    difficulty: "Medium",
    tags: ["programming", "coding", "conditionals"],
    timeEstimate: 60,
    webLink: "https://code.org/learn",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
];

export default codingAiGrade6Questions;
