// lib/questions/english-grade6.ts
const englishGrade6Questions = [
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question: "Which sentence uses the correct form of the verb?",
    options: [
      "A) The dog run around the yard.",
      "B) The dogs runs around the yard.",
      "C) The dogs run around the yard.",
      "D) The dog running around the yard.",
    ],
    correctAnswer: "C",
    hint: "Remember that the subject and verb must agree in number.",
    correctAnswerExplanation:
      "The subject 'dogs' is plural, so it needs a plural verb form. The plural form of 'run' doesn't have an 's' at the end, so 'dogs run' is correct.",
    incorrectAnswersExplanation: {
      A: "The singular subject 'dog' requires the singular verb form 'runs,' not 'run.'",
      B: "The plural subject 'dogs' requires the plural verb form 'run,' not the singular 'runs.'",
      D: "This is a sentence fragment using the present participle 'running,' not a complete sentence with a proper verb.",
    },
    difficulty: "Medium",
    tags: ["grammar", "subject-verb agreement", "english"],
    timeEstimate: 60,
    webLink: "https://www.grammarly.com/blog/subject-verb-agreement/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question: "Which sentence contains a properly used apostrophe?",
    options: [
      "A) The dog's bowl is empty.",
      "B) The dogs bowl is empty.",
      "C) The dog's are barking loudly.",
      "D) The dog's bowl's are empty.",
    ],
    correctAnswer: "A",
    hint: "Apostrophes show possession or contractions.",
    correctAnswerExplanation:
      "The apostrophe in 'dog's bowl' correctly shows that the bowl belongs to the dog. This is the proper use of an apostrophe to show possession for a singular noun.",
    incorrectAnswersExplanation: {
      B: "This sentence is missing an apostrophe to show possession. It should be 'dog's bowl.'",
      C: "This incorrectly uses an apostrophe with a plural subject. 'Dogs' is plural and doesn't need an apostrophe unless showing possession.",
      D: "This uses too many apostrophes. 'Bowl's' should not have an apostrophe when making it plural.",
    },
    difficulty: "Medium",
    tags: ["grammar", "apostrophes", "english"],
    timeEstimate: 60,
    webLink:
      "https://owl.purdue.edu/owl/general_writing/punctuation/apostrophe_introduction.html",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question: "Which sentence uses the correct form of the pronoun?",
    options: [
      "A) Me and my friend went to the library.",
      "B) My friend and me went to the library.",
      "C) My friend and I went to the library.",
      "D) I and my friend went to the library.",
    ],
    correctAnswer: "C",
    hint: "Try removing the other person and see if the sentence still sounds right.",
    correctAnswerExplanation:
      "When referring to yourself and another person as the subject of a sentence, use 'I' not 'me.' Also, it's polite to put the other person first in the sentence. 'My friend and I went to the library' is correct.",
    incorrectAnswersExplanation: {
      A: "Using 'me' as a subject pronoun is incorrect. It should be 'I' when you're the subject of the sentence.",
      B: "Using 'me' as a subject pronoun is incorrect. It should be 'I' when you're the subject of the sentence.",
      D: "While using 'I' is correct, the polite form is to put yourself last in the list of subjects.",
    },
    difficulty: "Medium",
    tags: ["grammar", "pronouns", "english"],
    timeEstimate: 60,
    webLink: "https://www.grammarly.com/blog/i-vs-me/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question:
      "In the sentence, 'The wolf howled at the moon,' what is the subject?",
    options: ["A) wolf", "B) howled", "C) moon", "D) The wolf"],
    correctAnswer: "D",
    hint: "The subject is who or what is doing the action.",
    correctAnswerExplanation:
      "The subject of a sentence is who or what is performing the action. In this sentence, 'The wolf' is doing the howling, so 'The wolf' is the complete subject, which includes the article 'The' and the noun 'wolf.'",
    incorrectAnswersExplanation: {
      A: "While 'wolf' is the simple subject (the main noun), the complete subject includes the article 'The.'",
      B: "'Howled' is the verb in this sentence, not the subject.",
      C: "'Moon' is part of the prepositional phrase 'at the moon,' which is the object of the preposition, not the subject.",
    },
    difficulty: "Medium",
    tags: ["grammar", "subjects", "english"],
    timeEstimate: 60,
    webLink: "https://www.k12reader.com/term/simple-subject/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question: "Which sentence uses correct capitalization?",
    options: [
      "A) we visited the grand canyon last summer.",
      "B) We visited the grand canyon last Summer.",
      "C) We visited the Grand Canyon last summer.",
      "D) we Visited The Grand Canyon Last Summer.",
    ],
    correctAnswer: "C",
    hint: "Remember to capitalize proper nouns and the first word of a sentence.",
    correctAnswerExplanation:
      "This sentence correctly capitalizes the first word of the sentence ('We') and the proper noun 'Grand Canyon.' Seasons like 'summer' are not capitalized unless they are part of a proper name.",
    incorrectAnswersExplanation: {
      A: "This sentence fails to capitalize the first word of the sentence ('we') and the proper noun 'grand canyon.'",
      B: "While 'We' is correctly capitalized, 'grand canyon' should be capitalized as it's a proper noun, and 'Summer' should not be capitalized as seasons are not capitalized.",
      D: "This sentence incorrectly capitalizes words that should not be capitalized, like 'Visited,' 'The,' 'Last,' and 'Summer.'",
    },
    difficulty: "Medium",
    tags: ["grammar", "capitalization", "english"],
    timeEstimate: 60,
    webLink:
      "https://owl.purdue.edu/owl/general_writing/mechanics/help_with_capitals.html",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question: "Which of the following is a compound sentence?",
    options: [
      "A) The dog chased the ball across the yard.",
      "B) The dog chased the ball, and the cat watched from the window.",
      "C) Chasing the ball across the yard, the dog barked happily.",
      "D) The dog, a golden retriever, chased the ball across the yard.",
    ],
    correctAnswer: "B",
    hint: "A compound sentence has two independent clauses joined by a conjunction.",
    correctAnswerExplanation:
      "A compound sentence consists of two independent clauses joined by a coordinating conjunction. 'The dog chased the ball' and 'the cat watched from the window' are both independent clauses connected by the coordinating conjunction 'and.'",
    incorrectAnswersExplanation: {
      A: "This is a simple sentence with one independent clause, not a compound sentence.",
      C: "This sentence has a dependent clause ('Chasing the ball across the yard') followed by an independent clause, making it a complex sentence.",
      D: "This is a simple sentence with an appositive phrase ('a golden retriever') that gives more information about the dog.",
    },
    difficulty: "Hard",
    tags: ["grammar", "sentence types", "english"],
    timeEstimate: 90,
    webLink: "https://www.grammarly.com/blog/compound-sentence/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question: "Which sentence contains a verb in the past perfect tense?",
    options: [
      "A) The boy walks his dog every day.",
      "B) The boy walked his dog yesterday.",
      "C) The boy had walked his dog before dinner.",
      "D) The boy will walk his dog tomorrow.",
    ],
    correctAnswer: "C",
    hint: "Past perfect tense uses 'had' plus the past participle of the verb.",
    correctAnswerExplanation:
      "The past perfect tense uses 'had' plus the past participle form of the verb. In 'The boy had walked his dog before dinner,' 'had walked' is in the past perfect tense, indicating an action completed before another past action.",
    incorrectAnswersExplanation: {
      A: "This sentence uses the present tense 'walks,' not the past perfect tense.",
      B: "This sentence uses the simple past tense 'walked,' not the past perfect tense.",
      D: "This sentence uses the future tense 'will walk,' not the past perfect tense.",
    },
    difficulty: "Hard",
    tags: ["grammar", "verb tenses", "english"],
    timeEstimate: 90,
    webLink: "https://www.grammarly.com/blog/past-perfect/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question:
      "Where should a comma be placed in this sentence? 'After finishing her homework Sarah went to the park.'",
    options: [
      "A) After 'After'",
      "B) After 'homework'",
      "C) After 'Sarah'",
      "D) No comma is needed",
    ],
    correctAnswer: "B",
    hint: "A comma is needed after an introductory phrase.",
    correctAnswerExplanation:
      "When a sentence begins with an introductory phrase like 'After finishing her homework,' a comma should follow it to separate it from the main clause. The correct sentence is: 'After finishing her homework, Sarah went to the park.'",
    incorrectAnswersExplanation: {
      A: "Placing a comma after 'After' would incorrectly split the introductory phrase.",
      C: "Placing a comma after 'Sarah' would incorrectly separate the subject from its verb.",
      D: "A comma is definitely needed in this sentence to separate the introductory phrase from the main clause.",
    },
    difficulty: "Medium",
    tags: ["grammar", "punctuation", "english"],
    timeEstimate: 60,
    webLink:
      "https://owl.purdue.edu/owl/general_writing/punctuation/commas/index.html",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question: "Which of the following is a complete sentence?",
    options: [
      "A) Running through the forest.",
      "B) Because the dinosaur was hungry.",
      "C) The enormous T-Rex stomped loudly.",
      "D) After the storm passed.",
    ],
    correctAnswer: "C",
    hint: "A complete sentence needs a subject and a verb.",
    correctAnswerExplanation:
      "A complete sentence requires both a subject and a verb. 'The enormous T-Rex stomped loudly' has a subject ('The enormous T-Rex') and a verb ('stomped'), making it a complete sentence.",
    incorrectAnswersExplanation: {
      A: "This is a sentence fragment that lacks a subject and a main verb. It's just a participial phrase.",
      B: "This is a dependent clause starting with 'Because,' not a complete sentence. It needs an independent clause to be complete.",
      D: "This is a prepositional phrase without a subject or main verb, making it a sentence fragment.",
    },
    difficulty: "Medium",
    tags: ["grammar", "sentence structure", "english"],
    timeEstimate: 60,
    webLink:
      "https://owl.purdue.edu/owl/general_writing/grammar/sentence_structure/index.html",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question:
      "In the sentence, 'The wolf howled loudly at the full moon,' what part of speech is 'loudly'?",
    options: ["A) Noun", "B) Verb", "C) Adverb", "D) Adjective"],
    correctAnswer: "C",
    hint: "This word describes how the action was performed.",
    correctAnswerExplanation:
      "An adverb modifies a verb, adjective, or another adverb. In this sentence, 'loudly' tells us how the wolf howled, modifying the verb 'howled,' so it's an adverb.",
    incorrectAnswersExplanation: {
      A: "A noun is a person, place, thing, or idea. 'Loudly' is not a noun but describes how an action was performed.",
      B: "A verb shows action or state of being. 'Howled' is the verb in this sentence, not 'loudly.'",
      D: "An adjective modifies a noun or pronoun. 'Loudly' modifies the verb 'howled,' not a noun, so it's not an adjective.",
    },
    difficulty: "Medium",
    tags: ["grammar", "parts of speech", "english"],
    timeEstimate: 60,
    webLink: "https://www.grammarly.com/blog/adverb/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question: "Which sentence uses a relative pronoun correctly?",
    options: [
      "A) The book who I read was exciting.",
      "B) The dog which barked all night kept me awake.",
      "C) The teacher whom teaches science is my favorite.",
      "D) The girl whose bike was stolen reported it to the police.",
    ],
    correctAnswer: "D",
    hint: "Think about which relative pronoun fits based on whether it refers to a person or thing and its function in the clause.",
    correctAnswerExplanation:
      "'Whose' is the correct possessive relative pronoun to show that the bike belongs to the girl. The sentence correctly uses 'whose' to connect the main clause with the relative clause that provides more information about the noun 'girl.'",
    incorrectAnswersExplanation: {
      A: "'Who' should only be used for people, not for objects like books. The correct relative pronoun would be 'that' or 'which.'",
      B: "For animals like dogs, especially when referred to as pets with personality, 'that' is more commonly used than 'which.' Also, 'which' typically requires a comma before it in this context.",
      C: "'Whom' is incorrect here because it should be used as the object of a verb or preposition, not as the subject of a clause. 'Who' would be correct.",
    },
    difficulty: "Hard",
    tags: ["grammar", "relative pronouns", "english"],
    timeEstimate: 90,
    webLink: "https://www.grammarly.com/blog/relative-pronouns/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question:
      "Which sentence uses the correct form of the comparative adjective?",
    options: [
      "A) This book is more better than the last one.",
      "B) This book is gooder than the last one.",
      "C) This book is more good than the last one.",
      "D) This book is better than the last one.",
    ],
    correctAnswer: "D",
    hint: "Some adjectives have irregular comparative forms, and we don't use 'more' with these irregular forms.",
    correctAnswerExplanation:
      "'Better' is the correct comparative form of the adjective 'good.' Irregular adjectives like 'good' have special comparative forms ('better') rather than following the standard rule of adding '-er' or using 'more.'",
    incorrectAnswersExplanation: {
      A: "Using 'more' with 'better' is redundant and incorrect, as 'better' already includes the comparative meaning.",
      B: "'Gooder' is not a correct English word. The comparative form of 'good' is 'better.'",
      C: "We don't use 'more good' in English. The correct comparative form of 'good' is 'better.'",
    },
    difficulty: "Medium",
    tags: ["grammar", "adjectives", "english"],
    timeEstimate: 60,
    webLink:
      "https://www.grammarly.com/blog/comparative-superlative-adjectives/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question: "Which sentence uses parallel structure correctly?",
    options: [
      "A) I like swimming, biking, and to run.",
      "B) I like swimming, biking, and running.",
      "C) I like swimming, to bike, and running.",
      "D) I like to swim, biking, and to run.",
    ],
    correctAnswer: "B",
    hint: "Parallel structure means using the same grammatical form for similar elements in a sentence.",
    correctAnswerExplanation:
      "Parallel structure requires using the same grammatical form for elements in a series. In this sentence, all three activities are in the gerund form (ending in -ing): swimming, biking, and running.",
    incorrectAnswersExplanation: {
      A: "This sentence mixes gerunds ('swimming, biking') with an infinitive ('to run'), breaking parallel structure.",
      C: "This sentence mixes gerunds ('swimming, running') with an infinitive ('to bike'), breaking parallel structure.",
      D: "This sentence inconsistently uses infinitives ('to swim, to run') and a gerund ('biking'), breaking parallel structure.",
    },
    difficulty: "Hard",
    tags: ["grammar", "parallel structure", "english"],
    timeEstimate: 90,
    webLink:
      "https://owl.purdue.edu/owl/general_writing/grammar/parallel_structure.html",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question: "Which of the following is a proper noun?",
    options: ["A) girl", "B) city", "C) Chicago", "D) park"],
    correctAnswer: "C",
    hint: "A proper noun names a specific person, place, or thing and is always capitalized.",
    correctAnswerExplanation:
      "'Chicago' is a proper noun because it names a specific city. Proper nouns name specific people, places, or things and are always capitalized, unlike common nouns which name general things.",
    incorrectAnswersExplanation: {
      A: "'Girl' is a common noun that refers to any young female person, not a specific individual.",
      B: "'City' is a common noun that refers to any urban area, not a specific city.",
      D: "'Park' is a common noun that refers to any recreational area, not a specific park.",
    },
    difficulty: "Medium",
    tags: ["grammar", "nouns", "english"],
    timeEstimate: 60,
    webLink: "https://www.grammarly.com/blog/proper-nouns/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question: "Which of the following sentences contains a direct object?",
    options: [
      "A) The small dog barked loudly.",
      "B) The girl walked to school.",
      "C) The boy threw the ball.",
      "D) The dinosaur fossil was discovered yesterday.",
    ],
    correctAnswer: "C",
    hint: "A direct object receives the action of the verb.",
    correctAnswerExplanation:
      "A direct object receives the action of the verb and answers the question 'what?' or 'whom?' after the verb. In 'The boy threw the ball,' 'ball' is the direct object because it answers 'What did the boy throw?'",
    incorrectAnswersExplanation: {
      A: "This sentence has a subject ('dog') and an intransitive verb ('barked') modified by an adverb ('loudly'), but no direct object.",
      B: "This sentence contains a subject ('girl'), verb ('walked'), and a prepositional phrase ('to school'), but no direct object.",
      D: "This is a passive sentence where 'dinosaur fossil' is the subject, not a direct object.",
    },
    difficulty: "Hard",
    tags: ["grammar", "sentence structure", "english"],
    timeEstimate: 90,
    webLink: "https://www.grammarly.com/blog/direct-object/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question:
      "In what tense is the sentence: 'The wolves will be hunting tonight'?",
    options: [
      "A) Simple future",
      "B) Future progressive",
      "C) Present progressive",
      "D) Past progressive",
    ],
    correctAnswer: "B",
    hint: "Look at the helping verbs and the form of the main verb.",
    correctAnswerExplanation:
      "The future progressive tense uses 'will be' followed by a verb ending in '-ing.' In 'The wolves will be hunting tonight,' we see this exact structure, indicating an action that will be ongoing in the future.",
    incorrectAnswersExplanation: {
      A: "Simple future tense would be 'The wolves will hunt tonight,' without the 'be' and '-ing' form.",
      C: "Present progressive would be 'The wolves are hunting,' using 'are' instead of 'will be.'",
      D: "Past progressive would be 'The wolves were hunting,' using 'were' instead of 'will be.'",
    },
    difficulty: "Hard",
    tags: ["grammar", "verb tenses", "english"],
    timeEstimate: 90,
    webLink: "https://www.grammarly.com/blog/future-progressive-tense/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question: "Which sentence contains an adverb phrase?",
    options: [
      "A) The dog with the spotted fur ran away.",
      "B) The boy ran very quickly.",
      "C) The girl in the red dress is my sister.",
      "D) After the storm, we went outside.",
    ],
    correctAnswer: "D",
    hint: "An adverb phrase modifies a verb by telling when, where, how, or to what extent.",
    correctAnswerExplanation:
      "An adverb phrase is a group of words that functions as an adverb. 'After the storm' is an adverb phrase because it modifies the verb 'went' by telling when we went outside.",
    incorrectAnswersExplanation: {
      A: "'With the spotted fur' is an adjective phrase that modifies the noun 'dog,' not an adverb phrase.",
      B: "While 'very quickly' contains the adverb 'quickly,' it's not considered an adverb phrase but rather an adverb ('quickly') modified by an intensifier ('very').",
      C: "'In the red dress' is an adjective phrase that modifies the noun 'girl,' not an adverb phrase.",
    },
    difficulty: "Hard",
    tags: ["grammar", "phrases", "english"],
    timeEstimate: 90,
    webLink: "https://www.grammarly.com/blog/adverbial-phrase/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question: "Which sentence contains a preposition?",
    options: [
      "A) She quickly finished her homework.",
      "B) The dog ran around the yard.",
      "C) That cake looks delicious.",
      "D) He always arrives early.",
    ],
    correctAnswer: "B",
    hint: "Prepositions show relationships between words, often indicating location or direction.",
    correctAnswerExplanation:
      "A preposition shows the relationship between a noun or pronoun and other words in a sentence. In 'The dog ran around the yard,' 'around' is a preposition that shows the relationship between 'ran' and 'yard.'",
    incorrectAnswersExplanation: {
      A: "This sentence contains an adverb ('quickly') but no preposition.",
      C: "This sentence contains a subject ('That cake'), verb ('looks'), and adjective ('delicious'), but no preposition.",
      D: "This sentence contains an adverb ('always') and another adverb ('early'), but no preposition.",
    },
    difficulty: "Medium",
    tags: ["grammar", "parts of speech", "english"],
    timeEstimate: 60,
    webLink: "https://www.grammarly.com/blog/prepositions/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question: "Which sentence uses the correct form of the irregular verb?",
    options: [
      "A) Yesterday, I runned three miles.",
      "B) Yesterday, I ran three miles.",
      "C) Yesterday, I runed three miles.",
      "D) Yesterday, I running three miles.",
    ],
    correctAnswer: "B",
    hint: "Irregular verbs don't follow the standard -ed pattern for past tense.",
    correctAnswerExplanation:
      "'Ran' is the correct past tense form of the irregular verb 'run.' Unlike regular verbs that add -ed to form the past tense, irregular verbs like 'run' have unique past tense forms that must be memorized.",
    incorrectAnswersExplanation: {
      A: "'Runned' is incorrect. The verb 'run' is irregular and doesn't form its past tense by adding -ed.",
      C: "'Runed' is incorrect. The past tense of 'run' is 'ran,' not 'runed.'",
      D: "'Running' is the present participle form, not the past tense. This creates an incomplete sentence.",
    },
    difficulty: "Medium",
    tags: ["grammar", "irregular verbs", "english"],
    timeEstimate: 60,
    webLink: "https://www.grammarly.com/blog/irregular-verbs/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question:
      "What is the predicate in this sentence? 'The eager students completed their science projects.'",
    options: [
      "A) The eager students",
      "B) eager students",
      "C) completed their science projects",
      "D) science projects",
    ],
    correctAnswer: "C",
    hint: "The predicate tells what the subject does or is.",
    correctAnswerExplanation:
      "The predicate is the part of a sentence that contains the verb and tells something about the subject. In this sentence, 'completed their science projects' is the predicate because it contains the verb 'completed' and tells what the students did.",
    incorrectAnswersExplanation: {
      A: "'The eager students' is the complete subject of the sentence, not the predicate.",
      B: "'Eager students' is part of the subject but without the article 'The.' It's not the predicate.",
      D: "'Science projects' is the object of the verb 'completed,' which is part of the predicate but not the complete predicate.",
    },
    difficulty: "Hard",
    tags: ["grammar", "sentence structure", "english"],
    timeEstimate: 90,
    webLink: "https://www.grammarly.com/blog/complete-predicate/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question: "Which sentence uses quotation marks correctly?",
    options: [
      'A) "I love reading," said Maria "especially adventure stories."',
      'B) "I love reading", said Maria, "especially adventure stories."',
      'C) "I love reading," said Maria, "especially adventure stories."',
      'D) "I love reading" said Maria "especially adventure stories"',
    ],
    correctAnswer: "C",
    hint: "Check the placement of punctuation with quotation marks and commas.",
    correctAnswerExplanation:
      "In American English, commas go inside quotation marks. When a quote is interrupted by words like 'said Maria,' commas are needed before and after this phrase, and each part of the quote needs its own quotation marks.",
    incorrectAnswersExplanation: {
      A: "This is incorrect because it's missing a comma after 'Maria' before the second part of the quote.",
      B: "This is incorrect because in American English, the comma should go inside the quotation marks, not outside.",
      D: "This is incorrect because it's missing the necessary commas around 'said Maria' and after the first part of the quote.",
    },
    difficulty: "Hard",
    tags: ["grammar", "punctuation", "english"],
    timeEstimate: 90,
    webLink:
      "https://owl.purdue.edu/owl/general_writing/punctuation/quotation_marks/index.html",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Grammar",
    grade: 6,
    questionType: "MC",
    question: "Which sentence uses a semicolon correctly?",
    options: [
      "A) I have a big test tomorrow; so I need to study tonight.",
      "B) I have a big test tomorrow; I need to study tonight.",
      "C) I have a big test tomorrow; but I need to study tonight.",
      "D) I have a big test tomorrow; which means I need to study tonight.",
    ],
    correctAnswer: "B",
    hint: "A semicolon can join two closely related independent clauses without a conjunction.",
    correctAnswerExplanation:
      "A semicolon can connect two independent clauses (complete sentences) that are closely related without using a coordinating conjunction. Both 'I have a big test tomorrow' and 'I need to study tonight' are complete sentences that are related in meaning.",
    incorrectAnswersExplanation: {
      A: "When using 'so' after a semicolon, you should use a comma instead of a semicolon because 'so' is a coordinating conjunction.",
      C: "When using 'but' after a semicolon, you should use a comma instead of a semicolon because 'but' is a coordinating conjunction.",
      D: "'Which means I need to study tonight' is not an independent clause (it can't stand alone), so a semicolon isn't appropriate here.",
    },
    difficulty: "Hard",
    tags: ["grammar", "punctuation", "english"],
    timeEstimate: 90,
    webLink: "https://www.grammarly.com/blog/semicolon/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question: "What is the best way to begin the writing process?",
    options: [
      "A) Check your spelling",
      "B) Create a title page",
      "C) Brainstorm ideas",
      "D) Write the conclusion",
    ],
    correctAnswer: "C",
    hint: "Think about what you need to do before you can start drafting.",
    correctAnswerExplanation:
      "Brainstorming ideas is the best way to begin the writing process because it helps you generate thoughts, organize your thinking, and develop a direction for your writing. Starting with brainstorming ensures you have enough content to develop into a full piece of writing.",
    incorrectAnswersExplanation: {
      A: "Checking spelling is part of the editing phase, which comes after you've written your draft, not at the beginning of the writing process.",
      B: "Creating a title page is a formatting task that typically comes near the end of the writing process, after you know what your writing is about.",
      D: "Writing the conclusion should come after you've written the introduction and body of your work, not at the beginning of the process.",
    },
    difficulty: "Medium",
    tags: ["writing", "process", "english"],
    timeEstimate: 60,
    webLink:
      "https://owl.purdue.edu/owl/general_writing/the_writing_process/index.html",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question:
      "Which of the following is the best example of a topic sentence for a paragraph about dogs as pets?",
    options: [
      "A) Dogs have four legs and a tail.",
      "B) Dogs make wonderful pets for many reasons.",
      "C) I have a dog named Max.",
      "D) Dogs need to be walked every day.",
    ],
    correctAnswer: "B",
    hint: "A good topic sentence introduces the main idea of the paragraph.",
    correctAnswerExplanation:
      "A strong topic sentence presents the main idea of the paragraph and tells readers what to expect. 'Dogs make wonderful pets for many reasons' clearly introduces the topic (dogs as pets) and suggests that the paragraph will discuss several reasons why dogs are good pets.",
    incorrectAnswersExplanation: {
      A: "This sentence states a fact about dogs' physical characteristics but doesn't address dogs as pets, which is the stated topic.",
      C: "This is too specific and personal for a topic sentence. It focuses on one dog rather than introducing the general topic of dogs as pets.",
      D: "This sentence focuses on only one aspect of dog ownership (walking) rather than introducing the broader topic of dogs as pets.",
    },
    difficulty: "Medium",
    tags: ["writing", "paragraphs", "english"],
    timeEstimate: 60,
    webLink: "https://www.grammarly.com/blog/topic-sentence/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question:
      "Which transitional phrase would best show a contrast between ideas?",
    options: [
      "A) In addition",
      "B) For example",
      "C) However",
      "D) First of all",
    ],
    correctAnswer: "C",
    hint: "Look for a word that shows an opposite or different idea.",
    correctAnswerExplanation:
      "'However' is a transitional word that shows contrast between ideas. It signals to the reader that the information that follows will differ from or contradict what came before, making it perfect for showing contrast between ideas.",
    incorrectAnswersExplanation: {
      A: "'In addition' is used to add similar or supporting information, not to show contrast.",
      B: "'For example' is used to introduce an illustration or example of a point, not to show contrast.",
      D: "'First of all' is used to introduce the first item in a sequence or list, not to show contrast.",
    },
    difficulty: "Medium",
    tags: ["writing", "transitions", "english"],
    timeEstimate: 60,
    webLink: "https://www.grammarly.com/blog/transition-words-phrases/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question: "Which is the best example of descriptive writing?",
    options: [
      "A) The dog ran fast.",
      "B) The shaggy brown dog sprinted across the wet grass, his tongue flapping in the wind.",
      "C) The dog is brown and likes to run.",
      "D) Dogs run fast because they have four legs.",
    ],
    correctAnswer: "B",
    hint: "Descriptive writing uses vivid details that appeal to the senses.",
    correctAnswerExplanation:
      "Descriptive writing uses sensory details and vivid language to help readers visualize a scene. 'The shaggy brown dog sprinted across the wet grass, his tongue flapping in the wind' includes specific details about appearance ('shaggy brown'), movement ('sprinted'), setting ('wet grass'), and a vivid image ('tongue flapping').",
    incorrectAnswersExplanation: {
      A: "This sentence is too simple and lacks descriptive details about the dog or how it ran.",
      C: "This sentence provides only basic information without vivid details or sensory language.",
      D: "This sentence provides an explanation rather than description and doesn't include sensory details.",
    },
    difficulty: "Medium",
    tags: ["writing", "description", "english"],
    timeEstimate: 60,
    webLink: "https://www.grammarly.com/blog/descriptive-writing/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question: "Which of the following would be found in an informative essay?",
    options: [
      "A) 'Once upon a time in a land far away...'",
      "B) 'Buy our amazing new product today!'",
      "C) 'I think chocolate ice cream is the best flavor.'",
      "D) 'Scientists have discovered three new dinosaur species in the past decade.'",
    ],
    correctAnswer: "D",
    hint: "An informative essay provides facts and information on a topic.",
    correctAnswerExplanation:
      "An informative essay presents facts and information objectively. 'Scientists have discovered three new dinosaur species in the past decade' provides factual information about a topic without expressing opinions or trying to persuade the reader, making it appropriate for an informative essay.",
    incorrectAnswersExplanation: {
      A: "'Once upon a time in a land far away...' is a typical opening for a narrative or story, not an informative essay.",
      B: "'Buy our amazing new product today!' is persuasive or promotional language aimed at selling something, not informing.",
      C: "'I think chocolate ice cream is the best flavor' expresses a personal opinion, which is more appropriate for a persuasive essay than an informative one.",
    },
    difficulty: "Medium",
    tags: ["writing", "essay types", "english"],
    timeEstimate: 60,
    webLink:
      "https://owl.purdue.edu/owl/general_writing/academic_writing/essay_writing/expository_essays.html",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question:
      "Which sentence would make the best thesis statement for an essay?",
    options: [
      "A) Dogs are animals with four legs.",
      "B) I will tell you about three types of dogs.",
      "C) Border collies make excellent pets because they are intelligent, loyal, and energetic.",
      "D) This essay is about dogs.",
    ],
    correctAnswer: "C",
    hint: "A good thesis statement presents the main argument and outlines key points.",
    correctAnswerExplanation:
      "A strong thesis statement clearly presents the main argument and provides specific points that will be discussed. 'Border collies make excellent pets because they are intelligent, loyal, and energetic' presents a clear position (border collies make excellent pets) and outlines three specific qualities that will be explained in the essay.",
    incorrectAnswersExplanation: {
      A: "This statement is a simple fact without an argument or points to discuss in an essay.",
      B: "While this sentence hints at essay structure, it doesn't present a clear position or argument about dogs.",
      D: "This is too vague and simply announces the topic without providing an argument or specific points.",
    },
    difficulty: "Hard",
    tags: ["writing", "thesis statement", "english"],
    timeEstimate: 90,
    webLink:
      "https://owl.purdue.edu/owl/general_writing/the_writing_process/thesis_statement_tips.html",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question:
      "What type of writing would you most likely find this sentence in? 'Add 2 cups of flour to the bowl and mix thoroughly.'",
    options: [
      "A) A persuasive essay",
      "B) A narrative story",
      "C) A procedural text",
      "D) A descriptive paragraph",
    ],
    correctAnswer: "C",
    hint: "Think about what kind of text gives step-by-step instructions.",
    correctAnswerExplanation:
      "Procedural texts provide step-by-step instructions on how to do something. The sentence 'Add 2 cups of flour to the bowl and mix thoroughly' gives a clear instruction for a specific step in a process, which is characteristic of procedural writing like recipes or how-to guides.",
    incorrectAnswersExplanation: {
      A: "A persuasive essay tries to convince readers of an opinion or position, not provide instructions.",
      B: "A narrative story tells a tale with characters, setting, and plot, not step-by-step instructions.",
      D: "A descriptive paragraph uses sensory details to describe something, not to give instructions on a process.",
    },
    difficulty: "Medium",
    tags: ["writing", "text types", "english"],
    timeEstimate: 60,
    webLink: "https://www.literacyideas.com/procedural-text",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question: "What is revision in the writing process?",
    options: [
      "A) Checking spelling and grammar",
      "B) Making major changes to improve content and organization",
      "C) Sharing your work with others",
      "D) Creating a final draft with proper formatting",
    ],
    correctAnswer: "B",
    hint: "Revision focuses on improving the content rather than surface errors.",
    correctAnswerExplanation:
      "Revision involves making significant changes to improve the content, clarity, and organization of your writing. During revision, writers may add, delete, or rearrange parts of their writing to make their ideas clearer, more logical, or more effective.",
    incorrectAnswersExplanation: {
      A: "Checking spelling and grammar is part of the editing phase, which comes after revision and focuses on correcting surface-level errors.",
      C: "Sharing your work with others might be part of peer review, which can help with revision but is not revision itself.",
      D: "Creating a final draft with proper formatting happens at the end of the writing process, after both revision and editing are complete.",
    },
    difficulty: "Medium",
    tags: ["writing", "process", "english"],
    timeEstimate: 60,
    webLink:
      "https://owl.purdue.edu/owl/general_writing/the_writing_process/proofreading/index.html",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question: "Which sentence is the most concise?",
    options: [
      "A) The boy who is tall and has brown hair went to the store that sells groceries.",
      "B) The tall boy with brown hair went to the grocery store.",
      "C) The boy that is tall and the boy that has brown hair went to the store where they sell groceries.",
      "D) The boy, who happens to be tall and has hair that is brown in color, went to the store that specializes in selling various grocery items.",
    ],
    correctAnswer: "B",
    hint: "Concise writing uses the fewest necessary words to express an idea clearly.",
    correctAnswerExplanation:
      "Concise writing eliminates unnecessary words while maintaining clarity. 'The tall boy with brown hair went to the grocery store' communicates all the essential information using the fewest words, making it the most concise option.",
    incorrectAnswersExplanation: {
      A: "This sentence uses unnecessary phrases like 'who is' and 'that sells groceries' when simpler adjectives like 'tall' and 'grocery store' would suffice.",
      C: "This sentence is wordy and redundant, repeating 'the boy that' unnecessarily and using the verbose 'store where they sell groceries' instead of 'grocery store.'",
      D: "This sentence is extremely wordy, with unnecessary phrases like 'who happens to be,' 'hair that is brown in color,' and 'specializes in selling various grocery items.'",
    },
    difficulty: "Hard",
    tags: ["writing", "concision", "english"],
    timeEstimate: 90,
    webLink: "https://www.grammarly.com/blog/concise-writing/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question:
      "Which of the following is a characteristic of persuasive writing?",
    options: [
      "A) It tells a story with characters and plot.",
      "B) It provides step-by-step instructions.",
      "C) It presents an opinion and supports it with reasons.",
      "D) It defines and explains a concept objectively.",
    ],
    correctAnswer: "C",
    hint: "Persuasive writing tries to convince the reader of something.",
    correctAnswerExplanation:
      "Persuasive writing aims to convince readers to agree with a particular viewpoint or take a specific action. The key characteristic is that it presents an opinion or position and supports it with reasons, evidence, and appeals to logic or emotion.",
    incorrectAnswersExplanation: {
      A: "Telling a story with characters and plot is a characteristic of narrative writing, not persuasive writing.",
      B: "Providing step-by-step instructions is a characteristic of procedural or instructional writing, not persuasive writing.",
      D: "Defining and explaining concepts objectively is a characteristic of expository or informative writing, not persuasive writing.",
    },
    difficulty: "Medium",
    tags: ["writing", "persuasive", "english"],
    timeEstimate: 60,
    webLink:
      "https://owl.purdue.edu/owl/general_writing/academic_writing/essay_writing/argumentative_essays.html",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question:
      "In what order should a writer typically organize the parts of a formal letter?",
    options: [
      "A) Body, closing, signature, date, greeting, address",
      "B) Address, date, greeting, body, closing, signature",
      "C) Greeting, address, date, body, signature, closing",
      "D) Signature, closing, body, greeting, date, address",
    ],
    correctAnswer: "B",
    hint: "Think about the logical flow of a formal letter from top to bottom.",
    correctAnswerExplanation:
      "A formal letter typically follows a specific order: the sender's address at the top, followed by the date, greeting (salutation), body of the letter, closing (like 'Sincerely'), and finally the signature. This organization is the standard format for formal letters.",
    incorrectAnswersExplanation: {
      A: "This order is incorrect because the body should not come first, and the address and date belong at the beginning of the letter.",
      C: "This order is incorrect because the greeting should come after the address and date, not before them.",
      D: "This order is completely reversed from the standard format. The signature comes at the end, not the beginning.",
    },
    difficulty: "Medium",
    tags: ["writing", "letter", "english"],
    timeEstimate: 60,
    webLink:
      "https://owl.purdue.edu/owl/subject_specific_writing/professional_technical_writing/basic_business_letters/index.html",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question: "What is alliteration?",
    options: [
      "A) When words that are near each other have the same ending sounds",
      "B) When words that are near each other have the same beginning sounds",
      "C) When words have opposite meanings",
      "D) When words sound like what they describe",
    ],
    correctAnswer: "B",
    hint: "Think about tongue twisters like 'Peter Piper picked a peck of pickled peppers.'",
    correctAnswerExplanation:
      "Alliteration is the repetition of the same consonant sound at the beginning of nearby words. Examples include 'wild and wooly wolves' or 'Sally sells seashells.' Writers use alliteration to create rhythm and draw attention to certain words or phrases.",
    incorrectAnswersExplanation: {
      A: "This describes rhyme (especially end rhyme), not alliteration. Rhyme involves similar ending sounds, while alliteration involves similar beginning sounds.",
      C: "This describes antonyms, which are words with opposite meanings, not a sound pattern like alliteration.",
      D: "This describes onomatopoeia, where words imitate the sounds they represent, like 'buzz' or 'crash.'",
    },
    difficulty: "Hard",
    tags: ["writing", "literary devices", "english"],
    timeEstimate: 90,
    webLink: "https://www.grammarly.com/blog/alliteration/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question: "What is the purpose of an introduction paragraph in an essay?",
    options: [
      "A) To summarize all the main points of the essay",
      "B) To define key vocabulary words used in the essay",
      "C) To grab attention and introduce the main topic",
      "D) To explain why the author chose the topic",
    ],
    correctAnswer: "C",
    hint: "The introduction sets the stage for the rest of the essay.",
    correctAnswerExplanation:
      "The main purposes of an introduction paragraph are to capture the reader's interest, provide context for the topic, and introduce the main idea or thesis of the essay. A good introduction grabs attention and gives readers a clear idea of what to expect from the rest of the essay.",
    incorrectAnswersExplanation: {
      A: "Summarizing all main points is typically done in the conclusion, not the introduction. The introduction should introduce the topic, not summarize the whole essay.",
      B: "While you might define key terms in an introduction if necessary, this is not the primary purpose of an introduction paragraph.",
      D: "Explaining why you chose a topic might be included in some introductions, but it's not the main purpose of an introduction paragraph.",
    },
    difficulty: "Medium",
    tags: ["writing", "essay structure", "english"],
    timeEstimate: 60,
    webLink:
      "https://owl.purdue.edu/owl/general_writing/academic_writing/essay_writing/introductions_conclusions_and_titles.html",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question: "Which sentence best demonstrates the use of imagery?",
    options: [
      "A) The dog is brown.",
      "B) The dog ran fast.",
      "C) The dog has four legs.",
      "D) The rusty-colored retriever bounded through the tall grass, sending dewdrops flying into the morning sunlight.",
    ],
    correctAnswer: "D",
    hint: "Imagery uses sensory details to create a vivid picture.",
    correctAnswerExplanation:
      "Imagery uses descriptive language to create vivid mental pictures that appeal to the reader's senses. The sentence about the 'rusty-colored retriever' uses visual details ('rusty-colored,' 'tall grass'), movement ('bounded'), and light effects ('dewdrops flying into the morning sunlight') to create a rich sensory image.",
    incorrectAnswersExplanation: {
      A: "This sentence provides only one basic visual detail ('brown') without creating a vivid sensory experience.",
      B: "This sentence tells rather than shows, using the general adjective 'fast' instead of descriptive language that creates a mental image.",
      C: "This sentence simply states a fact without using any imagery or sensory details.",
    },
    difficulty: "Hard",
    tags: ["writing", "imagery", "english"],
    timeEstimate: 90,
    webLink: "https://www.grammarly.com/blog/imagery/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question: "What is a metaphor?",
    options: [
      "A) A comparison using 'like' or 'as'",
      "B) A direct comparison that states one thing is another",
      "C) The repetition of consonant sounds at the beginning of words",
      "D) An exaggeration for effect",
    ],
    correctAnswer: "B",
    hint: "A metaphor makes a direct comparison without using words like 'like' or 'as'.",
    correctAnswerExplanation:
      "A metaphor directly compares two unlike things by stating that one thing is another, without using words like 'like' or 'as.' For example, 'Her smile is sunshine' directly states that the smile is sunshine rather than saying it's like sunshine.",
    incorrectAnswersExplanation: {
      A: "This describes a simile, which makes a comparison using 'like' or 'as,' not a metaphor.",
      C: "This describes alliteration, which is the repetition of beginning consonant sounds, not a metaphor.",
      D: "This describes hyperbole, which is an extreme exaggeration not meant to be taken literally.",
    },
    difficulty: "Hard",
    tags: ["writing", "figurative language", "english"],
    timeEstimate: 90,
    webLink: "https://www.grammarly.com/blog/metaphor/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question:
      "What is the best description of the writing technique used in this sentence? 'The ancient T-Rex stomped through the jungle, crushing everything in its path.'",
    options: [
      "A) Personification",
      "B) Imagery",
      "C) Alliteration",
      "D) Onomatopoeia",
    ],
    correctAnswer: "B",
    hint: "This technique creates a vivid mental picture for the reader.",
    correctAnswerExplanation:
      "Imagery uses descriptive language to create vivid mental pictures that appeal to the senses. This sentence uses strong visual and auditory imagery with words like 'stomped' and 'crushing' to help readers imagine the T-Rex moving through the jungle.",
    incorrectAnswersExplanation: {
      A: "Personification gives human qualities to non-human things. Nothing in this sentence attributes human characteristics to the T-Rex beyond what dinosaurs actually did.",
      C: "Alliteration repeats initial consonant sounds in consecutive words. While 'through' and 'the' share the 'th' sound, this is not significant enough to be considered alliteration.",
      D: "Onomatopoeia uses words that imitate sounds. While 'stomped' suggests a sound, it's not directly imitating the sound itself like 'boom' or 'crash' would.",
    },
    difficulty: "Hard",
    tags: ["writing", "techniques", "english"],
    timeEstimate: 90,
    webLink: "https://www.grammarly.com/blog/sensory-imagery/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "English",
    topic: "Writing",
    grade: 6,
    questionType: "MC",
    question:
      "Which of these would most likely be found in a personal narrative?",
    options: [
      "A) 'Mix the ingredients until the batter is smooth.'",
      "B) 'The heart pumps blood throughout the body.'",
      "C) 'My hands trembled as I opened the letter from my pen pal.'",
      "D) 'Dinosaurs lived during the Mesozoic Era.'",
    ],
    correctAnswer: "C",
    hint: "A personal narrative tells a story from the first-person point of view.",
    correctAnswerExplanation:
      "A personal narrative is a story told from the first-person perspective about something that happened to the writer. 'My hands trembled as I opened the letter from my pen pal' uses first-person perspective ('my', 'I') and describes a personal experience with emotion, typical of personal narratives.",
    incorrectAnswersExplanation: {
      A: "This is an instructional sentence that would appear in procedural writing like a recipe, not a personal narrative.",
      B: "This is a factual statement that would appear in informational or expository writing, not a personal narrative.",
      D: "This is a factual statement about history that would appear in informational writing, not a personal narrative.",
    },
    difficulty: "Medium",
    tags: ["writing", "narrative", "english"],
    timeEstimate: 60,
    webLink: "https://www.literacyideas.com/personal-narrative",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
];

export default englishGrade6Questions;
