// lib/questions/history-grade6.ts
const historyGrade6Questions = [
  {
    subject: "History",
    topic: "Ancient Civilizations",
    grade: 6,
    questionType: "MC",
    question:
      "A T-Rex skeleton is found near ancient Egyptian ruins—what were the pyramids used for?",
    options: [
      "A) Tombs for pharaohs",
      "B) Dinosaur shelters",
      "C) Ancient schools",
      "D) Marketplaces",
    ],
    correctAnswer: "A",
    hint: "The pyramids were built as tombs for Egyptian pharaohs.",
    correctAnswerExplanation:
      "The pyramids were built as tombs for Egyptian pharaohs.",
    incorrectAnswersExplanation: {
      B: "Dinosaurs lived millions of years before humans, so they didn't use pyramids.",
      C: "Pyramids were not schools; they were burial sites.",
      D: "Pyramids were not marketplaces; they had a religious purpose.",
    },
    difficulty: "Medium",
    tags: ["ancient civilizations", "egypt", "pyramids"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/ancient-egypt.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Ancient Civilizations",
    grade: 6,
    questionType: "MC",
    question:
      "Ancient Egyptians wrote about dinosaur fossils—what does this tell us?",
    options: [
      "A) They knew about dinosaurs",
      "B) They found fossils",
      "C) They saw live dinosaurs",
      "D) They made up stories",
    ],
    correctAnswer: "B",
    hint: "Ancient Egyptians found fossils and recorded them.",
    correctAnswerExplanation:
      "Ancient Egyptians found fossils and recorded them, but they didn't see live dinosaurs.",
    incorrectAnswersExplanation: {
      A: "They didn't know about dinosaurs as we do today.",
      C: "Dinosaurs were extinct long before Egyptians.",
      D: "They recorded fossils, not just stories.",
    },
    difficulty: "Medium",
    tags: ["ancient civilizations", "fossils", "egypt"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/ancient-egypt.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Ancient Civilizations",
    grade: 6,
    questionType: "MC",
    question:
      "What animal was sacred to ancient Egyptians and often mummified?",
    options: ["A) Wolf", "B) Cat", "C) Dog", "D) Hawk"],
    correctAnswer: "B",
    hint: "Cats were associated with the goddess Bastet.",
    correctAnswerExplanation:
      "Cats were sacred to Egyptians and often mummified to honor Bastet, the goddess of home and fertility.",
    incorrectAnswersExplanation: {
      A: "Wolves were not significant in Egyptian culture.",
      C: "Dogs were pets but not sacred.",
      D: "Hawks symbolized Horus, but cats were more commonly mummified.",
    },
    difficulty: "Hard",
    tags: ["ancient civilizations", "egypt", "religion"],
    timeEstimate: 90,
    webLink: "https://www.historyforkids.net/egyptian-gods.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Ancient Civilizations",
    grade: 6,
    questionType: "MC",
    question: "Which ancient civilization built the Great Wall of China?",
    options: ["A) Romans", "B) Greeks", "C) Chinese Dynasties", "D) Aztecs"],
    correctAnswer: "C",
    hint: "The Great Wall was built over many Chinese dynasties.",
    correctAnswerExplanation:
      "The Great Wall was constructed by multiple Chinese dynasties to protect against invasions.",
    incorrectAnswersExplanation: {
      A: "Romans built structures like the Colosseum, not the Great Wall.",
      B: "Greeks built the Parthenon, not the Great Wall.",
      D: "Aztecs built temples in Mexico, not the Great Wall.",
    },
    difficulty: "Hard",
    tags: ["ancient civilizations", "china", "architecture"],
    timeEstimate: 90,
    webLink: "https://www.historyforkids.net/great-wall-of-china.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Ancient Civilizations",
    grade: 6,
    questionType: "MC",
    question: "Which writing system did ancient Mesopotamians use?",
    options: [
      "A) Hieroglyphs",
      "B) Cuneiform",
      "C) Alphabet",
      "D) Pictographs",
    ],
    correctAnswer: "B",
    hint: "Mesopotamians used wedge-shaped writing on clay tablets.",
    correctAnswerExplanation:
      "Cuneiform was the wedge-shaped writing system used in Mesopotamia.",
    incorrectAnswersExplanation: {
      A: "Hieroglyphs were used in Egypt.",
      C: "Alphabets developed later in history.",
      D: "Pictographs were simpler symbols used earlier.",
    },
    difficulty: "Medium",
    tags: ["ancient civilizations", "mesopotamia", "writing"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/mesopotamia.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Middle Ages",
    grade: 6,
    questionType: "MC",
    question:
      "A knight says his castle is ‘paws-itively’ huge—who worked the land around it?",
    options: ["A) Kings", "B) Serfs", "C) Merchants", "D) Monks"],
    correctAnswer: "B",
    hint: "Serfs were peasants who worked for lords in exchange for protection.",
    correctAnswerExplanation:
      "Serfs farmed the land and owed labor to the lord of the castle.",
    incorrectAnswersExplanation: {
      A: "Kings ruled but didn’t work the land.",
      C: "Merchants traded goods, not farmed.",
      D: "Monks focused on religious duties.",
    },
    difficulty: "Medium",
    tags: ["middle ages", "feudalism", "humor"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/middle-ages.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Middle Ages",
    grade: 6,
    questionType: "MC",
    question: "What was the main purpose of a medieval castle?",
    options: ["A) Host parties", "B) Defense", "C) Farming", "D) Education"],
    correctAnswer: "B",
    hint: "Castles were built to protect against attacks.",
    correctAnswerExplanation:
      "Castles were fortified structures designed for defense during wars.",
    incorrectAnswersExplanation: {
      A: "Parties were rare; defense was the priority.",
      C: "Farming happened outside the castle.",
      D: "Education occurred in monasteries or schools.",
    },
    difficulty: "Hard",
    tags: ["middle ages", "castles", "defense"],
    timeEstimate: 90,
    webLink: "https://www.historyforkids.net/medieval-castles.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Middle Ages",
    grade: 6,
    questionType: "MC",
    question: "Which disease killed millions in Europe during the Middle Ages?",
    options: ["A) Smallpox", "B) Black Death", "C) Influenza", "D) Cholera"],
    correctAnswer: "B",
    hint: "This disease was spread by fleas on rats.",
    correctAnswerExplanation:
      "The Black Death (bubonic plague) killed about 1/3 of Europe’s population in the 14th century.",
    incorrectAnswersExplanation: {
      A: "Smallpox arrived later during colonization.",
      C: "Influenza was common but less deadly.",
      D: "Cholera outbreaks occurred in the 19th century.",
    },
    difficulty: "Hard",
    tags: ["middle ages", "disease", "black death"],
    timeEstimate: 90,
    webLink: "https://www.historyforkids.net/black-death.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Middle Ages",
    grade: 6,
    questionType: "MC",
    question: "What was a jester’s role in a medieval court?",
    options: [
      "A) Train knights",
      "B) Entertain the king",
      "C) Cook meals",
      "D) Lead armies",
    ],
    correctAnswer: "B",
    hint: "Jesters told jokes and performed tricks.",
    correctAnswerExplanation:
      "Jesters entertained royalty with music, jokes, and acrobatics.",
    incorrectAnswersExplanation: {
      A: "Knights trained with other knights.",
      C: "Cooks prepared meals in the kitchen.",
      D: "Kings or generals led armies.",
    },
    difficulty: "Medium",
    tags: ["middle ages", "culture", "humor"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/medieval-jesters.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Middle Ages",
    grade: 6,
    questionType: "MC",
    question: "What was the primary crop grown by medieval peasants?",
    options: ["A) Corn", "B) Wheat", "C) Potatoes", "D) Tomatoes"],
    correctAnswer: "B",
    hint: "This grain was used to make bread.",
    correctAnswerExplanation:
      "Wheat was the main crop for bread, a staple food in medieval Europe.",
    incorrectAnswersExplanation: {
      A: "Corn came to Europe from the Americas after 1492.",
      C: "Potatoes were introduced after the Columbian Exchange.",
      D: "Tomatoes also originated in the Americas.",
    },
    difficulty: "Hard",
    tags: ["middle ages", "agriculture", "economy"],
    timeEstimate: 90,
    webLink: "https://www.historyforkids.net/medieval-farming.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Middle Ages",
    grade: 6,
    questionType: "MC",
    question: "Which document limited the king's power in 1215 England?",
    options: [
      "A) Declaration of Independence",
      "B) Magna Carta",
      "C) Bill of Rights",
      "D) Domesday Book",
    ],
    correctAnswer: "B",
    hint: "This document was signed by King John.",
    correctAnswerExplanation:
      "The Magna Carta limited royal power and established legal rights.",
    incorrectAnswersExplanation: {
      A: "The Declaration of Independence is a U.S. document.",
      C: "The Bill of Rights came later in English history.",
      D: "The Domesday Book recorded land ownership.",
    },
    difficulty: "Medium",
    tags: ["middle ages", "england", "law"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/magna-carta.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Middle Ages",
    grade: 6,
    questionType: "MC",
    question: "What architectural style is Notre-Dame Cathedral?",
    options: ["A) Baroque", "B) Gothic", "C) Romanesque", "D) Renaissance"],
    correctAnswer: "B",
    hint: "Known for pointed arches and stained glass.",
    correctAnswerExplanation:
      "Notre-Dame is a classic example of Gothic architecture.",
    incorrectAnswersExplanation: {
      A: "Baroque emerged in the 17th century.",
      C: "Romanesque had thicker walls and round arches.",
      D: "Renaissance architecture came later.",
    },
    difficulty: "Hard",
    tags: ["middle ages", "architecture", "france"],
    timeEstimate: 90,
    webLink: "https://www.historyforkids.net/notre-dame-cathedral.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Middle Ages",
    grade: 6,
    questionType: "MC",
    question: "Who was Charlemagne?",
    options: [
      "A) A Viking leader",
      "B) King of the Franks",
      "C) A Roman emperor",
      "D) A Byzantine monk",
    ],
    correctAnswer: "B",
    hint: "He was crowned 'Emperor of the Romans' in 800 CE.",
    correctAnswerExplanation:
      "Charlemagne united much of Western Europe and promoted education.",
    incorrectAnswersExplanation: {
      A: "Vikings raided Europe; Charlemagne fought them.",
      C: "He ruled after the Roman Empire fell.",
      D: "He was a ruler, not a monk.",
    },
    difficulty: "Medium",
    tags: ["middle ages", "charlemagne", "frankish empire"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/charlemagne.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Middle Ages",
    grade: 6,
    questionType: "MC",
    question: "What was a guild in medieval towns?",
    options: [
      "A) A type of castle",
      "B) A trade association",
      "C) A religious group",
      "D) A farming tool",
    ],
    correctAnswer: "B",
    hint: "Guilds set standards for crafts like blacksmithing.",
    correctAnswerExplanation:
      "Guilds regulated trades and trained apprentices.",
    incorrectAnswersExplanation: {
      A: "Castles were military structures.",
      C: "Monks and nuns were in religious orders.",
      D: "Farming tools included plows and sickles.",
    },
    difficulty: "Medium",
    tags: ["middle ages", "economy", "guilds"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/medieval-guilds.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "World History",
    grade: 6,
    questionType: "MC",
    question: "Which empire built Machu Picchu?",
    options: ["A) Aztec", "B) Maya", "C) Inca", "D) Olmec"],
    correctAnswer: "C",
    hint: "This empire was in the Andes Mountains.",
    correctAnswerExplanation:
      "The Inca built Machu Picchu as a royal estate in Peru.",
    incorrectAnswersExplanation: {
      A: "The Aztec built Tenochtitlán in Mexico.",
      B: "The Maya built cities like Chichén Itzá.",
      D: "The Olmec were earlier and lived in Mexico.",
    },
    difficulty: "Hard",
    tags: ["world history", "inca", "architecture"],
    timeEstimate: 90,
    webLink: "https://www.historyforkids.net/machu-picchu.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "World History",
    grade: 6,
    questionType: "MC",
    question: "Which explorer reached the Americas in 1492?",
    options: [
      "A) Vasco da Gama",
      "B) Ferdinand Magellan",
      "C) Christopher Columbus",
      "D) Marco Polo",
    ],
    correctAnswer: "C",
    hint: "He sailed under the Spanish flag.",
    correctAnswerExplanation:
      "Columbus reached the Bahamas, believing he had found Asia.",
    incorrectAnswersExplanation: {
      A: "Vasco da Gama sailed to India.",
      B: "Magellan’s crew circumnavigated the globe.",
      D: "Marco Polo traveled to China earlier.",
    },
    difficulty: "Medium",
    tags: ["world history", "exploration", "americas"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/christopher-columbus.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "World History",
    grade: 6,
    questionType: "MC",
    question: "What was the Silk Road?",
    options: [
      "A) A trade route",
      "B) A wall in China",
      "C) A type of ship",
      "D) A religious path",
    ],
    correctAnswer: "A",
    hint: "It connected Asia and Europe.",
    correctAnswerExplanation:
      "The Silk Road was a network of trade routes for goods like silk and spices.",
    incorrectAnswersExplanation: {
      B: "The Great Wall of China was defensive.",
      C: "Ships like junks were used on seas.",
      D: "Religious pilgrimages followed different routes.",
    },
    difficulty: "Medium",
    tags: ["world history", "trade", "silk road"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/silk-road.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "World History",
    grade: 6,
    questionType: "MC",
    question: "Which civilization invented paper?",
    options: ["A) Greeks", "B) Chinese", "C) Egyptians", "D) Romans"],
    correctAnswer: "B",
    hint: "Paper was invented around 100 BCE.",
    correctAnswerExplanation:
      "The Chinese invented paper using materials like hemp and tree bark.",
    incorrectAnswersExplanation: {
      A: "Greeks used papyrus or parchment.",
      C: "Egyptians used papyrus, not paper.",
      D: "Romans used parchment and wax tablets.",
    },
    difficulty: "Hard",
    tags: ["world history", "china", "inventions"],
    timeEstimate: 90,
    webLink: "https://www.historyforkids.net/chinese-inventions.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "World History",
    grade: 6,
    questionType: "MC",
    question: "Which civilization built the Colosseum?",
    options: ["A) Greeks", "B) Egyptians", "C) Romans", "D) Persians"],
    correctAnswer: "C",
    hint: "The Colosseum hosted gladiator fights.",
    correctAnswerExplanation:
      "The Romans built the Colosseum in Rome for public spectacles.",
    incorrectAnswersExplanation: {
      A: "Greeks built theaters like the Parthenon.",
      B: "Egyptians built pyramids and temples.",
      D: "Persians built palaces like Persepolis.",
    },
    difficulty: "Hard",
    tags: ["world history", "rome", "architecture"],
    timeEstimate: 90,
    webLink: "https://www.historyforkids.net/roman-colosseum.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "World History",
    grade: 6,
    questionType: "MC",
    question: "Who wrote the epic poem 'The Odyssey'?",
    options: ["A) Virgil", "B) Homer", "C) Socrates", "D) Plato"],
    correctAnswer: "B",
    hint: "This poet also wrote 'The Iliad'.",
    correctAnswerExplanation:
      "Homer composed 'The Odyssey', an epic about Odysseus's journey home.",
    incorrectAnswersExplanation: {
      A: "Virgil wrote 'The Aeneid'.",
      C: "Socrates was a philosopher, not a poet.",
      D: "Plato wrote philosophical dialogues.",
    },
    difficulty: "Medium",
    tags: ["world history", "greece", "literature"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/homer.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "World History",
    grade: 6,
    questionType: "MC",
    question: "Which ancient civilization developed democracy?",
    options: ["A) Rome", "B) Egypt", "C) Athens", "D) Persia"],
    correctAnswer: "C",
    hint: "This city-state allowed male citizens to vote.",
    correctAnswerExplanation:
      "Athens developed democracy, where citizens could participate in government.",
    incorrectAnswersExplanation: {
      A: "Rome had a republic with elected senators.",
      B: "Egypt was ruled by pharaohs.",
      D: "Persia was a monarchy.",
    },
    difficulty: "Hard",
    tags: ["world history", "greece", "government"],
    timeEstimate: 90,
    webLink: "https://www.historyforkids.net/athenian-democracy.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "World History",
    grade: 6,
    questionType: "MC",
    question: "What was the primary religion of the Byzantine Empire?",
    options: [
      "A) Islam",
      "B) Roman Catholicism",
      "C) Eastern Orthodox Christianity",
      "D) Judaism",
    ],
    correctAnswer: "C",
    hint: "The Byzantine Empire split from the Roman Catholic Church.",
    correctAnswerExplanation:
      "The Byzantine Empire followed Eastern Orthodox Christianity after the Great Schism of 1054.",
    incorrectAnswersExplanation: {
      A: "Islam spread later in the Middle East.",
      B: "Roman Catholicism was centered in Rome.",
      D: "Judaism was practiced by smaller communities.",
    },
    difficulty: "Hard",
    tags: ["world history", "byzantine empire", "religion"],
    timeEstimate: 90,
    webLink: "https://www.historyforkids.net/byzantine-empire.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "World History",
    grade: 6,
    questionType: "MC",
    question: "Which empire was ruled by Genghis Khan?",
    options: ["A) Ottoman", "B) Mongol", "C) Persian", "D) Aztec"],
    correctAnswer: "B",
    hint: "This empire spanned from Asia to Europe.",
    correctAnswerExplanation:
      "Genghis Khan founded the Mongol Empire, the largest land empire in history.",
    incorrectAnswersExplanation: {
      A: "The Ottoman Empire rose later.",
      C: "The Persian Empire existed earlier.",
      D: "The Aztec were in Mesoamerica.",
    },
    difficulty: "Medium",
    tags: ["world history", "mongol empire", "genghis khan"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/mongol-empire.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "US History",
    grade: 6,
    questionType: "MC",
    question: "Who wrote the Declaration of Independence?",
    options: [
      "A) George Washington",
      "B) Thomas Jefferson",
      "C) Benjamin Franklin",
      "D) John Adams",
    ],
    correctAnswer: "B",
    hint: "He later became the third U.S. president.",
    correctAnswerExplanation:
      "Thomas Jefferson drafted the Declaration of Independence in 1776.",
    incorrectAnswersExplanation: {
      A: "Washington led the Continental Army.",
      C: "Franklin helped edit the document.",
      D: "Adams supported independence but didn’t write it.",
    },
    difficulty: "Medium",
    tags: ["us history", "american revolution", "government"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/declaration-of-independence.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "US History",
    grade: 6,
    questionType: "MC",
    question: "Which event started the American Revolutionary War?",
    options: [
      "A) Boston Tea Party",
      "B) Battle of Bunker Hill",
      "C) Battles of Lexington and Concord",
      "D) Signing of the Constitution",
    ],
    correctAnswer: "C",
    hint: "The 'shot heard round the world' occurred here.",
    correctAnswerExplanation:
      "The Battles of Lexington and Concord in 1775 marked the first military clashes.",
    incorrectAnswersExplanation: {
      A: "The Tea Party protested taxes in 1773.",
      B: "Bunker Hill occurred after the war started.",
      D: "The Constitution was signed in 1787.",
    },
    difficulty: "Hard",
    tags: ["us history", "american revolution", "war"],
    timeEstimate: 90,
    webLink: "https://www.historyforkids.net/american-revolution.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "US History",
    grade: 6,
    questionType: "MC",
    question: "What was the main purpose of the Lewis and Clark Expedition?",
    options: [
      "A) Fight British troops",
      "B) Explore the Louisiana Territory",
      "C) Establish a new colony",
      "D) Map the Atlantic coast",
    ],
    correctAnswer: "B",
    hint: "They traveled west with Sacagawea.",
    correctAnswerExplanation:
      "Lewis and Clark explored the Louisiana Purchase to map routes and document resources.",
    incorrectAnswersExplanation: {
      A: "The War of 1812 involved fighting the British.",
      C: "They explored, didn’t colonize.",
      D: "The Atlantic coast was already mapped.",
    },
    difficulty: "Hard",
    tags: ["us history", "westward expansion", "exploration"],
    timeEstimate: 90,
    webLink: "https://www.historyforkids.net/lewis-and-clark.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "US History",
    grade: 6,
    questionType: "MC",
    question: "Which document outlines the U.S. government’s structure?",
    options: [
      "A) Declaration of Independence",
      "B) Articles of Confederation",
      "C) Constitution",
      "D) Bill of Rights",
    ],
    correctAnswer: "C",
    hint: "It begins with 'We the People'.",
    correctAnswerExplanation:
      "The Constitution establishes the three branches of government.",
    incorrectAnswersExplanation: {
      A: "The Declaration announced independence.",
      B: "The Articles were replaced by the Constitution.",
      D: "The Bill of Rights lists individual freedoms.",
    },
    difficulty: "Medium",
    tags: ["us history", "government", "constitution"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/us-constitution.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "US History",
    grade: 6,
    questionType: "MC",
    question: "What was the main cause of the Civil War?",
    options: [
      "A) Taxation without representation",
      "B) Slavery",
      "C) Land disputes with Native Americans",
      "D) Trade with Europe",
    ],
    correctAnswer: "B",
    hint: "Southern states wanted to keep this practice.",
    correctAnswerExplanation:
      "The North and South disagreed over slavery, leading to the Civil War.",
    incorrectAnswersExplanation: {
      A: "This was a cause of the American Revolution.",
      C: "Land disputes existed but weren’t the primary cause.",
      D: "Trade disputes were secondary issues.",
    },
    difficulty: "Hard",
    tags: ["us history", "civil war", "slavery"],
    timeEstimate: 90,
    webLink: "https://www.historyforkids.net/civil-war.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "US History",
    grade: 6,
    questionType: "MC",
    question: "Which amendment abolished slavery in the U.S.?",
    options: ["A) 13th", "B) 14th", "C) 15th", "D) 16th"],
    correctAnswer: "A",
    hint: "It was passed after the Civil War.",
    correctAnswerExplanation:
      "The 13th Amendment (1865) abolished slavery in the U.S.",
    incorrectAnswersExplanation: {
      B: "The 14th granted citizenship and equal protection.",
      C: "The 15th gave voting rights to Black men.",
      D: "The 16th allowed income taxes.",
    },
    difficulty: "Hard",
    tags: ["us history", "civil war", "amendments"],
    timeEstimate: 90,
    webLink: "https://www.historyforkids.net/13th-amendment.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "US History",
    grade: 6,
    questionType: "MC",
    question: "Who led the Underground Railroad?",
    options: [
      "A) Frederick Douglass",
      "B) Harriet Tubman",
      "C) Abraham Lincoln",
      "D) Sojourner Truth",
    ],
    correctAnswer: "B",
    hint: "She was called 'Moses' for guiding people to freedom.",
    correctAnswerExplanation:
      "Harriet Tubman led enslaved people to freedom via the Underground Railroad.",
    incorrectAnswersExplanation: {
      A: "Douglass was an abolitionist speaker.",
      C: "Lincoln issued the Emancipation Proclamation.",
      D: "Truth was an abolitionist and women’s rights activist.",
    },
    difficulty: "Medium",
    tags: ["us history", "slavery", "abolition"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/harriet-tubman.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "US History",
    grade: 6,
    questionType: "MC",
    question: "What was the Louisiana Purchase?",
    options: [
      "A) A battle in the Civil War",
      "B) Land bought from France",
      "C) A treaty with Native Americans",
      "D) A tax on tea",
    ],
    correctAnswer: "B",
    hint: "It doubled the size of the U.S.",
    correctAnswerExplanation:
      "The U.S. bought the Louisiana Territory from France in 1803.",
    incorrectAnswersExplanation: {
      A: "The Civil War occurred decades later.",
      C: "Treaties with Native Americans were separate.",
      D: "The Tea Act led to the Boston Tea Party.",
    },
    difficulty: "Medium",
    tags: ["us history", "westward expansion", "geography"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/louisiana-purchase.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "US History",
    grade: 6,
    questionType: "MC",
    question: "Which president signed the Emancipation Proclamation?",
    options: [
      "A) George Washington",
      "B) Thomas Jefferson",
      "C) Abraham Lincoln",
      "D) Ulysses S. Grant",
    ],
    correctAnswer: "C",
    hint: "He was president during the Civil War.",
    correctAnswerExplanation:
      "Lincoln signed it in 1863 to free enslaved people in Confederate states.",
    incorrectAnswersExplanation: {
      A: "Washington was the first president.",
      B: "Jefferson wrote the Declaration of Independence.",
      D: "Grant led Union armies, then became president.",
    },
    difficulty: "Medium",
    tags: ["us history", "civil war", "slavery"],
    timeEstimate: 60,
    webLink: "https://www.historyforkids.net/emancipation-proclamation.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Geography",
    grade: 6,
    questionType: "MC",
    question:
      "A dog hikes in Yellowstone National Park—which US state is it in?",
    options: ["A) Wyoming", "B) Montana", "C) Idaho", "D) Colorado"],
    correctAnswer: "A",
    hint: "Most of Yellowstone is in this state.",
    correctAnswerExplanation:
      "Yellowstone is mostly in Wyoming, with small parts in Montana and Idaho.",
    incorrectAnswersExplanation: {
      B: "Montana has part of Yellowstone.",
      C: "Idaho has a tiny portion.",
      D: "Colorado has Rocky Mountain National Park.",
    },
    difficulty: "Medium",
    tags: ["geography", "us states", "national parks"],
    timeEstimate: 60,
    webLink: "https://www.nps.gov/yell/index.htm",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Geography",
    grade: 6,
    questionType: "MC",
    question: "Which river is the longest in the United States?",
    options: ["A) Mississippi", "B) Missouri", "C) Colorado", "D) Rio Grande"],
    correctAnswer: "B",
    hint: "It starts in Montana and flows into the Mississippi.",
    correctAnswerExplanation:
      "The Missouri River is 2,341 miles long, longer than the Mississippi.",
    incorrectAnswersExplanation: {
      A: "The Mississippi is shorter but carries more water.",
      C: "The Colorado carved the Grand Canyon.",
      D: "The Rio Grande forms the U.S.-Mexico border.",
    },
    difficulty: "Hard",
    tags: ["geography", "rivers", "us"],
    timeEstimate: 90,
    webLink: "https://www.nps.gov/miss/riverfacts.htm",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Geography",
    grade: 6,
    questionType: "MC",
    question: "Which state is known as the 'Sunshine State'?",
    options: ["A) California", "B) Texas", "C) Florida", "D) Arizona"],
    correctAnswer: "C",
    hint: "It’s home to Disney World and Miami.",
    correctAnswerExplanation:
      "Florida has sunny weather year-round, earning its nickname.",
    incorrectAnswersExplanation: {
      A: "California is the 'Golden State'.",
      B: "Texas is the 'Lone Star State'.",
      D: "Arizona is known for deserts, not beaches.",
    },
    difficulty: "Medium",
    tags: ["geography", "us states", "nicknames"],
    timeEstimate: 60,
    webLink: "https://www.visittheusa.com/state/florida",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Geography",
    grade: 6,
    questionType: "MC",
    question: "Which Great Lake is entirely within the U.S.?",
    options: [
      "A) Lake Superior",
      "B) Lake Michigan",
      "C) Lake Huron",
      "D) Lake Erie",
    ],
    correctAnswer: "B",
    hint: "It’s the only one not shared with Canada.",
    correctAnswerExplanation:
      "Lake Michigan is the only Great Lake entirely within the U.S.",
    incorrectAnswersExplanation: {
      A: "Superior is shared with Canada.",
      C: "Huron borders Canada.",
      D: "Erie is shared with Canada.",
    },
    difficulty: "Hard",
    tags: ["geography", "great lakes", "us"],
    timeEstimate: 90,
    webLink: "https://www.nps.gov/glac/learn/nature/great-lakes.htm",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Geography",
    grade: 6,
    questionType: "MC",
    question: "Which U.S. state has the most active volcanoes?",
    options: ["A) Hawaii", "B) Alaska", "C) California", "D) Washington"],
    correctAnswer: "B",
    hint: "It’s the largest state by area.",
    correctAnswerExplanation:
      "Alaska has over 130 volcanoes, more than any other state.",
    incorrectAnswersExplanation: {
      A: "Hawaii has active volcanoes like Kilauea.",
      C: "California has Mount Shasta but fewer volcanoes.",
      D: "Washington has Mount St. Helens but fewer active ones.",
    },
    difficulty: "Hard",
    tags: ["geography", "volcanoes", "us"],
    timeEstimate: 90,
    webLink: "https://www.usgs.gov/observatories/avo",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Geography",
    grade: 6,
    questionType: "MC",
    question: "What is the capital of the United States?",
    options: [
      "A) New York",
      "B) Washington, D.C.",
      "C) Philadelphia",
      "D) Boston",
    ],
    correctAnswer: "B",
    hint: "It’s named after the first president.",
    correctAnswerExplanation: "Washington, D.C., became the capital in 1800.",
    incorrectAnswersExplanation: {
      A: "New York was briefly the capital in the 1780s.",
      C: "Philadelphia hosted early government meetings.",
      D: "Boston is a historic city but not the capital.",
    },
    difficulty: "Medium",
    tags: ["geography", "us capitals", "government"],
    timeEstimate: 60,
    webLink: "https://www.nps.gov/nr/travel/wash/",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Geography",
    grade: 6,
    questionType: "MC",
    question: "Which river forms part of the U.S.-Mexico border?",
    options: ["A) Mississippi", "B) Colorado", "C) Rio Grande", "D) Missouri"],
    correctAnswer: "C",
    hint: "Its name means 'Big River' in Spanish.",
    correctAnswerExplanation: "The Rio Grande separates Texas from Mexico.",
    incorrectAnswersExplanation: {
      A: "The Mississippi flows through the central U.S.",
      B: "The Colorado carved the Grand Canyon.",
      D: "The Missouri is a tributary of the Mississippi.",
    },
    difficulty: "Medium",
    tags: ["geography", "rivers", "us-mexico"],
    timeEstimate: 60,
    webLink: "https://www.nps.gov/rigr/index.htm",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Geography",
    grade: 6,
    questionType: "MC",
    question: "Which mountain range runs along the eastern U.S.?",
    options: [
      "A) Rocky Mountains",
      "B) Sierra Nevada",
      "C) Appalachian Mountains",
      "D) Cascade Range",
    ],
    correctAnswer: "C",
    hint: "They’re older and shorter than the Rockies.",
    correctAnswerExplanation: "The Appalachians stretch from Georgia to Maine.",
    incorrectAnswersExplanation: {
      A: "The Rockies are in the western U.S.",
      B: "The Sierra Nevada are in California.",
      D: "The Cascades are in the Pacific Northwest.",
    },
    difficulty: "Hard",
    tags: ["geography", "mountains", "us"],
    timeEstimate: 90,
    webLink: "https://www.nps.gov/appa/index.htm",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Geography",
    grade: 6,
    questionType: "MC",
    question: "Which U.S. state is known as 'The Grand Canyon State'?",
    options: ["A) Utah", "B) Colorado", "C) Arizona", "D) Nevada"],
    correctAnswer: "C",
    hint: "The Grand Canyon is carved by the Colorado River.",
    correctAnswerExplanation:
      "Arizona’s Grand Canyon is one of the Seven Natural Wonders.",
    incorrectAnswersExplanation: {
      A: "Utah has Zion and Bryce Canyon.",
      B: "Colorado has the Rocky Mountains.",
      D: "Nevada is home to Las Vegas.",
    },
    difficulty: "Medium",
    tags: ["geography", "us states", "national parks"],
    timeEstimate: 60,
    webLink: "https://www.nps.gov/grca/index.htm",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Geography",
    grade: 6,
    questionType: "MC",
    question: "Which U.S. city is nicknamed 'The Big Apple'?",
    options: ["A) Los Angeles", "B) Chicago", "C) New York City", "D) Miami"],
    correctAnswer: "C",
    hint: "It’s home to the Statue of Liberty.",
    correctAnswerExplanation:
      "New York City earned the nickname in the 1920s jazz era.",
    incorrectAnswersExplanation: {
      A: "Los Angeles is called 'The City of Angels'.",
      B: "Chicago is the 'Windy City'.",
      D: "Miami is the 'Magic City'.",
    },
    difficulty: "Medium",
    tags: ["geography", "us cities", "nicknames"],
    timeEstimate: 60,
    webLink: "https://www.nycgo.com/",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Geography",
    grade: 6,
    questionType: "MC",
    question: "Which U.S. state is the smallest by area?",
    options: ["A) Delaware", "B) Rhode Island", "C) Connecticut", "D) Hawaii"],
    correctAnswer: "B",
    hint: "It’s nicknamed the 'Ocean State'.",
    correctAnswerExplanation: "Rhode Island covers just 1,214 square miles.",
    incorrectAnswersExplanation: {
      A: "Delaware is the second-smallest.",
      C: "Connecticut is larger than Rhode Island.",
      D: "Hawaii is an archipelago but not the smallest.",
    },
    difficulty: "Hard",
    tags: ["geography", "us states", "size"],
    timeEstimate: 90,
    webLink: "https://www.ri.gov/",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Geography",
    grade: 6,
    questionType: "MC",
    question:
      "Which two states are part of the continental U.S. but not connected to the rest?",
    options: [
      "A) Alaska and Hawaii",
      "B) Florida and Texas",
      "C) California and Washington",
      "D) Maine and Vermont",
    ],
    correctAnswer: "A",
    hint: "One is in the Arctic, the other in the Pacific.",
    correctAnswerExplanation:
      "Alaska (northwest of Canada) and Hawaii (Pacific) are not connected to the 48 contiguous states.",
    incorrectAnswersExplanation: {
      B: "Florida and Texas are connected.",
      C: "California and Washington are West Coast states.",
      D: "Maine and Vermont are in New England.",
    },
    difficulty: "Medium",
    tags: ["geography", "us states", "regions"],
    timeEstimate: 60,
    webLink:
      "https://www.census.gov/programs-surveys/geography/guidance/geo-areas.html",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "History",
    topic: "Geography",
    grade: 6,
    questionType: "MC",
    question: "Which U.S. national park is famous for its geysers?",
    options: ["A) Yosemite", "B) Yellowstone", "C) Grand Canyon", "D) Zion"],
    correctAnswer: "B",
    hint: "Old Faithful is located here.",
    correctAnswerExplanation:
      "Yellowstone has over 500 geysers, including Old Faithful.",
    incorrectAnswersExplanation: {
      A: "Yosemite is known for granite cliffs.",
      C: "Grand Canyon is famous for its vast canyon.",
      D: "Zion has red rock formations.",
    },
    difficulty: "Medium",
    tags: ["geography", "national parks", "us"],
    timeEstimate: 60,
    webLink: "https://www.nps.gov/yell/index.htm",
    source: "Perplexity",
    lastUpdated: "2025-04-23",
  },
];

export default historyGrade6Questions;
