// lib/questions/logic-puzzles-grade6.ts
const logicPuzzlesGrade6Questions = [
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "I’m a dinosaur at the Chicago Museum who writes without a pen and reads without a book—what am I?",
    options: ["A) A librarian", "B) A tablet", "C) A T-Rex", "D) A fossil"],
    correctAnswer: "B",
    hint: "Think about a device that can store writing and books digitally.",
    correctAnswerExplanation:
      "A tablet is the correct answer because it allows you to write notes or stories digitally without a pen and read e-books without a physical book. It fits the riddle perfectly for a museum setting where technology might be used to display dinosaur facts.",
    incorrectAnswersExplanation: {
      A: "A librarian organizes books but still uses pens and reads physical books, so it doesn’t fit the riddle.",
      C: "A T-Rex is a dinosaur but doesn’t write or read in the way described.",
      D: "A fossil is a dinosaur remain, not something that writes or reads.",
    },
    difficulty: "Medium",
    tags: ["riddles", "dinosaurs", "technology"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "In a Texas library, I’m a dog who says a riddle is ‘paws-itively’ tricky: I speak without a mouth and hear without ears—what am I?",
    options: ["A) A book", "B) An echo", "C) A wolf", "D) A phone"],
    correctAnswer: "B",
    hint: "Think about something that repeats sounds without having a body.",
    correctAnswerExplanation:
      "An echo is correct because it ‘speaks’ by repeating sounds without a mouth and ‘hears’ by detecting sound waves without ears. This riddle uses a fun dog pun to make it engaging!",
    incorrectAnswersExplanation: {
      A: "A book contains words but doesn’t speak or hear on its own.",
      C: "A wolf has a mouth and ears, so it doesn’t fit the riddle.",
      D: "A phone needs speakers and microphones, which act like mouths and ears.",
    },
    difficulty: "Hard",
    tags: ["riddles", "dogs", "humor"],
    timeEstimate: 90,
    webLink: "https://www.brainpop.com/games/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "At a New York fossil exhibit, a T-Rex says: I’m tall when I’m young, but short when I’m old—what am I?",
    options: ["A) A candle", "B) A tree", "C) A pencil", "D) A dinosaur"],
    correctAnswer: "A",
    hint: "Think of something that gets shorter as it’s used over time.",
    correctAnswerExplanation:
      "A candle is correct because it’s tall when ‘young’ (newly made) and gets shorter as it’s burned, fitting the riddle. The T-Rex makes it fun by connecting to a museum setting.",
    incorrectAnswersExplanation: {
      B: "A tree grows taller as it ages, not shorter.",
      C: "A pencil gets shorter with use, but it’s not naturally ‘tall’ when young.",
      D: "A dinosaur doesn’t change height in this way as it ages.",
    },
    difficulty: "Medium",
    tags: ["riddles", "dinosaurs", "museums"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "In a Florida zoo, a wolf howls: I’m always running but never move—what am I?",
    options: ["A) A river", "B) A clock", "C) A dog", "D) A car"],
    correctAnswer: "B",
    hint: "Think of something that tracks time without moving from its spot.",
    correctAnswerExplanation:
      "A clock is correct because its hands ‘run’ around the face to show time, but the clock itself stays still. The wolf’s howl adds a fun zoo theme!",
    incorrectAnswersExplanation: {
      A: "A river flows but moves water, not itself, so it’s not a perfect fit.",
      C: "A dog runs and moves its body, so it doesn’t match the riddle.",
      D: "A car moves when it runs, unlike the riddle’s description.",
    },
    difficulty: "Hard",
    tags: ["riddles", "wolves", "time"],
    timeEstimate: 90,
    webLink: "https://www.brainpop.com/games/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "At a California book fair, a dog barks: I have cities but no houses, forests but no trees—what am I?",
    options: ["A) A map", "B) A painting", "C) A book", "D) A globe"],
    correctAnswer: "A",
    hint: "Think of something that shows places without real buildings or plants.",
    correctAnswerExplanation:
      "A map is correct because it shows cities without individual houses and forests with symbols, not real trees. The dog at a book fair makes it a fun setting!",
    incorrectAnswersExplanation: {
      B: "A painting might show houses or trees, not just cities or forests.",
      C: "A book has stories, not maps of cities and forests without details.",
      D: "A globe shows continents but not always cities or forests clearly.",
    },
    difficulty: "Medium",
    tags: ["riddles", "dogs", "maps"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "In a Boston museum, a T-Rex roars: I’m light as a feather, but even the strongest can’t hold me for long—what am I?",
    options: ["A) Air", "B) Breath", "C) A cloud", "D) A balloon"],
    correctAnswer: "B",
    hint: "Think of something light that you can’t keep in your body for long.",
    correctAnswerExplanation:
      "Breath is correct because air in your lungs is light like a feather, but you can’t hold your breath for long before exhaling. The T-Rex in a museum adds a fun twist!",
    incorrectAnswersExplanation: {
      A: "Air is everywhere and not held like the riddle suggests.",
      C: "A cloud is light but not something you hold in your hands or body.",
      D: "A balloon is light but can be held for a long time if tied.",
    },
    difficulty: "Hard",
    tags: ["riddles", "dinosaurs", "science"],
    timeEstimate: 90,
    webLink: "https://www.brainpop.com/games/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "At a Seattle library, a wolf says: I have keys but no locks—what am I?",
    options: ["A) A piano", "B) A car", "C) A typewriter", "D) A map"],
    correctAnswer: "A",
    hint: "Think of something with keys you press, not for opening anything.",
    correctAnswerExplanation:
      "A piano is correct because it has keys for playing music, not for locks. The wolf in a library makes it a cool setting for this riddle!",
    incorrectAnswersExplanation: {
      B: "A car has keys for starting it, which work like locks.",
      C: "A typewriter has keys, but they’re less common and not as clear a fit as a piano.",
      D: "A map doesn’t have keys, so it doesn’t fit the riddle.",
    },
    difficulty: "Medium",
    tags: ["riddles", "wolves", "music"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "In a Denver park, a dog digs and says: The more you take, the more you leave behind—what am I?",
    options: ["A) Footprints", "B) Bones", "C) Dirt", "D) Toys"],
    correctAnswer: "A",
    hint: "Think of something you leave when you walk away.",
    correctAnswerExplanation:
      "Footprints are correct because the more steps you take, the more footprints you leave behind. The dog digging in a park makes this riddle fun and relatable!",
    incorrectAnswersExplanation: {
      B: "Bones aren’t left behind by taking more steps or actions.",
      C: "Dirt might be moved, but you don’t leave more by taking it.",
      D: "Toys are carried, not left behind by taking more.",
    },
    difficulty: "Hard",
    tags: ["riddles", "dogs", "nature"],
    timeEstimate: 90,
    webLink: "https://www.brainpop.com/games/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "At a Los Angeles fossil dig, a T-Rex says: I’m full of holes, yet I hold water—what am I?",
    options: ["A) A sponge", "B) A bucket", "C) A net", "D) A bone"],
    correctAnswer: "A",
    hint: "Think of something that soaks up liquid even with holes.",
    correctAnswerExplanation:
      "A sponge is correct because it has holes but can hold water by absorbing it. The T-Rex at a fossil dig makes this riddle exciting for a 6th grader!",
    incorrectAnswersExplanation: {
      B: "A bucket holds water but doesn’t have holes unless it’s broken.",
      C: "A net has holes but lets water pass through, not holding it.",
      D: "A bone has no holes that hold water in this way.",
    },
    difficulty: "Medium",
    tags: ["riddles", "dinosaurs", "science"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "In a Phoenix zoo, a wolf howls: I’m taken from a mine and shut in a wooden case—what am I?",
    options: ["A) Coal", "B) A pencil", "C) A book", "D) A cage"],
    correctAnswer: "B",
    hint: "Think of something in a pencil that comes from the ground.",
    correctAnswerExplanation:
      "A pencil is correct because its graphite (often called lead) is mined and encased in a wooden pencil. The wolf in a zoo adds a wild twist to this riddle!",
    incorrectAnswersExplanation: {
      A: "Coal is mined but not typically put in a wooden case.",
      C: "A book has paper from trees, not mined materials.",
      D: "A cage is wooden or metal but doesn’t hold mined material this way.",
    },
    difficulty: "Hard",
    tags: ["riddles", "wolves", "writing"],
    timeEstimate: 90,
    webLink: "https://www.brainpop.com/games/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "At a Miami book club, a dog barks: I have a neck but no head—what am I?",
    options: ["A) A bottle", "B) A shirt", "C) A wolf", "D) A book"],
    correctAnswer: "B",
    hint: "Think of clothing that has a neck area but no head part.",
    correctAnswerExplanation:
      "A shirt is correct because it has a neck opening for your head but no ‘head’ of its own. The dog in a book club makes this a fun riddle!",
    incorrectAnswersExplanation: {
      A: "A bottle has a neck and a cap, which could be seen as a head.",
      C: "A wolf has both a neck and a head, so it doesn’t fit.",
      D: "A book doesn’t have a neck or head in this sense.",
    },
    difficulty: "Medium",
    tags: ["riddles", "dogs", "clothing"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "In a Chicago fossil exhibit, a T-Rex roars: I’m alive without breath—what am I?",
    options: ["A) A plant", "B) A fish", "C) A fossil", "D) A robot"],
    correctAnswer: "A",
    hint: "Think of a living thing that doesn’t breathe air like animals do.",
    correctAnswerExplanation:
      "A plant is correct because it’s alive but uses photosynthesis, not breathing, to live. The T-Rex in a fossil exhibit makes this riddle exciting!",
    incorrectAnswersExplanation: {
      B: "A fish breathes through gills, so it doesn’t fit the riddle.",
      C: "A fossil is not alive, so it can’t be the answer.",
      D: "A robot isn’t alive, even if it doesn’t breathe.",
    },
    difficulty: "Hard",
    tags: ["riddles", "dinosaurs", "science"],
    timeEstimate: 90,
    webLink: "https://www.brainpop.com/games/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "At an Atlanta library, a wolf says: The more of me you take, the more you leave behind—what am I?",
    options: ["A) Footsteps", "B) Books", "C) Shadows", "D) Words"],
    correctAnswer: "A",
    hint: "Think of something you leave behind when you move.",
    correctAnswerExplanation:
      "Footsteps are correct because the more steps you take, the more footprints you leave. The wolf in a library adds a cool twist to this riddle!",
    incorrectAnswersExplanation: {
      B: "Taking books doesn’t leave more books behind.",
      C: "Shadows don’t increase by taking more of them.",
      D: "Words might be spoken, but they don’t leave physical traces like footsteps.",
    },
    difficulty: "Medium",
    tags: ["riddles", "wolves", "movement"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "In a Houston museum, a dog barks: I’m weightless, but you can see me—put me in a bucket, and I’ll make it lighter—what am I?",
    options: ["A) A hole", "B) Air", "C) Light", "D) A feather"],
    correctAnswer: "A",
    hint: "Think of something that removes weight when added.",
    correctAnswerExplanation:
      "A hole is correct because it has no weight, can be seen as an absence, and adding a hole to a bucket (by cutting it) makes it lighter. The dog in a museum makes this fun!",
    incorrectAnswersExplanation: {
      B: "Air has weight and doesn’t make a bucket lighter when added.",
      C: "Light is visible but doesn’t affect a bucket’s weight this way.",
      D: "A feather has weight, even if it’s small.",
    },
    difficulty: "Hard",
    tags: ["riddles", "dogs", "science"],
    timeEstimate: 90,
    webLink: "https://www.brainpop.com/games/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "At a San Diego zoo, a T-Rex says: I have branches but no fruit—what am I?",
    options: ["A) A bank", "B) A tree", "C) A library", "D) A vine"],
    correctAnswer: "A",
    hint: "Think of a place with ‘branches’ that aren’t part of a plant.",
    correctAnswerExplanation:
      "A bank is correct because it has branches (locations) but no fruit, unlike a tree. The T-Rex in a zoo makes this riddle exciting!",
    incorrectAnswersExplanation: {
      B: "A tree has branches and can have fruit, so it doesn’t fit.",
      C: "A library might have sections, but they aren’t called branches in this way.",
      D: "A vine can have fruit like grapes, so it’s not correct.",
    },
    difficulty: "Medium",
    tags: ["riddles", "dinosaurs", "business"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "In a Dallas library, a wolf howls: I’m tall when I’m born, but I get shorter as I grow—what am I?",
    options: ["A) A pencil", "B) A candle", "C) A book", "D) A wolf"],
    correctAnswer: "B",
    hint: "Think of something that burns down over time.",
    correctAnswerExplanation:
      "A candle is correct because it’s tall when made (‘born’) and gets shorter as it’s used. The wolf in a library adds a wild twist!",
    incorrectAnswersExplanation: {
      A: "A pencil gets shorter with use, but it’s not ‘born’ tall in the same way.",
      C: "A book doesn’t change height as it’s used or ages.",
      D: "A wolf grows taller, not shorter, as it ages.",
    },
    difficulty: "Hard",
    tags: ["riddles", "wolves", "objects"],
    timeEstimate: 90,
    webLink: "https://www.brainpop.com/games/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "At a Philadelphia museum, a dog barks: I have a heart that doesn’t beat—what am I?",
    options: ["A) An artichoke", "B) A stone", "C) A T-Rex", "D) A book"],
    correctAnswer: "A",
    hint: "Think of a vegetable with a part called a ‘heart.’",
    correctAnswerExplanation:
      "An artichoke is correct because it has a ‘heart’ (the tender center) that doesn’t beat like an animal’s heart. The dog in a museum makes this fun!",
    incorrectAnswersExplanation: {
      B: "A stone doesn’t have a heart at all, so it doesn’t fit.",
      C: "A T-Rex had a beating heart when alive, unlike the riddle.",
      D: "A book doesn’t have a heart in this sense.",
    },
    difficulty: "Medium",
    tags: ["riddles", "dogs", "food"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "In a Detroit zoo, a T-Rex roars: I fly without wings and cry without eyes—what am I?",
    options: ["A) A cloud", "B) A bird", "C) A plane", "D) A kite"],
    correctAnswer: "A",
    hint: "Think of something in the sky that moves and makes water.",
    correctAnswerExplanation:
      "A cloud is correct because it ‘flies’ through the sky with the wind and ‘cries’ by producing rain, without wings or eyes. The T-Rex in a zoo makes this exciting!",
    incorrectAnswersExplanation: {
      B: "A bird has wings and eyes, so it doesn’t fit the riddle.",
      C: "A plane has wings and doesn’t cry, so it’s not correct.",
      D: "A kite flies but needs a string and doesn’t cry.",
    },
    difficulty: "Hard",
    tags: ["riddles", "dinosaurs", "weather"],
    timeEstimate: 90,
    webLink: "https://www.brainpop.com/games/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Riddles",
    grade: 6,
    questionType: "MC",
    question:
      "In a St. Louis museum, a dog barks: I have teeth but no mouth—what am I?",
    options: ["A) A comb", "B) A wolf", "C) A fossil", "D) A book"],

    correctAnswer: "A",
    hint: "Think of something with teeth used for grooming, not eating.",
    correctAnswerExplanation:
      "A comb is correct because it has teeth for brushing hair, but no mouth. The dog in a museum makes this a fun riddle!",
    incorrectAnswersExplanation: {
      B: "A wolf has teeth and a mouth, so it doesn’t fit.",
      C: "A fossil might have teeth, but it’s not a complete creature anymore.",
      D: "A book doesn’t have teeth or a mouth.",
    },
    difficulty: "Hard",
    tags: ["riddles", "dogs", "grooming"],
    timeEstimate: 90,
    webLink: "https://www.brainpop.com/games/riddles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "At a New York library, a dog notices a pattern in book numbers: 2, 4, 6—what’s the next number?",
    options: ["A) 7", "B) 8", "C) 9", "D) 10"],
    correctAnswer: "B",
    hint: "Look for a simple rule that increases each number.",
    correctAnswerExplanation:
      "The pattern is adding 2 to each number: 2 + 2 = 4, 4 + 2 = 6, so 6 + 2 = 8. The dog in a library makes this pattern fun to spot!",
    incorrectAnswersExplanation: {
      A: "Adding 5 would break the pattern of increasing by 2.",
      C: "Adding 3 doesn’t match the consistent +2 rule.",
      D: "Adding 4 skips the correct step of +2.",
    },
    difficulty: "Medium",
    tags: ["patterns", "dogs", "math"],
    timeEstimate: 60,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "In a Chicago museum, a T-Rex sees fossil display numbers: 1, 3, 6, 10—what’s the next number?",
    options: ["A) 12", "B) 15", "C) 18", "D) 21"],
    correctAnswer: "B",
    hint: "Notice how the difference between numbers increases by 1 each time.",
    correctAnswerExplanation:
      "The pattern is triangular numbers: 1, 1+2=3, 3+3=6, 6+4=10, so 10+5=15. The T-Rex in a museum makes this pattern exciting to solve!",
    incorrectAnswersExplanation: {
      A: "Adding 2 doesn’t follow the increasing difference pattern.",
      C: "Adding 8 skips the correct +5 step.",
      D: "Adding 11 is too large for the pattern.",
    },
    difficulty: "Hard",
    tags: ["patterns", "dinosaurs", "math"],
    timeEstimate: 90,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "At a Florida zoo, a wolf sees a feeding schedule: 9 AM, 11 AM, 1 PM—what’s the next time?",
    options: ["A) 2 PM", "B) 3 PM", "C) 4 PM", "D) 5 PM"],
    correctAnswer: "B",
    hint: "Check the time difference between each feeding.",
    correctAnswerExplanation:
      "The pattern is every 2 hours: 9 AM to 11 AM is 2 hours, 11 AM to 1 PM is 2 hours, so 1 PM + 2 hours = 3 PM. The wolf in a zoo makes this fun to figure out!",
    incorrectAnswersExplanation: {
      A: "1 hour after 1 PM is too short for the 2-hour pattern.",
      C: "3 hours after 1 PM skips the 2-hour rule.",
      D: "4 hours after 1 PM is too long.",
    },
    difficulty: "Medium",
    tags: ["patterns", "wolves", "time"],
    timeEstimate: 60,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "In a Texas library, a dog sees book stack heights: 4, 7, 11—what’s the next height?",
    options: ["A) 12", "B) 14", "C) 16", "D) 18"],
    correctAnswer: "C",
    hint: "Look at the difference between each stack height.",
    correctAnswerExplanation:
      "The pattern is adding 3, then 4, then 5: 4 + 3 = 7, 7 + 4 = 11, so 11 + 5 = 16. The dog in a library makes this pattern fun!",
    incorrectAnswersExplanation: {
      A: "Adding 1 doesn’t match the increasing difference pattern.",
      B: "Adding 3 again breaks the +1 difference increase.",
      D: "Adding 7 is too large for the pattern.",
    },
    difficulty: "Hard",
    tags: ["patterns", "dogs", "math"],
    timeEstimate: 90,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "At a California fossil dig, a T-Rex counts bones: 5, 10, 20—what’s the next number?",
    options: ["A) 25", "B) 30", "C) 40", "D) 50"],
    correctAnswer: "C",
    hint: "Check if the numbers are doubling each time.",
    correctAnswerExplanation:
      "The pattern is doubling: 5 × 2 = 10, 10 × 2 = 20, so 20 × 2 = 40. The T-Rex at a fossil dig makes this pattern exciting!",
    incorrectAnswersExplanation: {
      A: "Adding 5 doesn’t follow the doubling rule.",
      B: "Adding 10 is less than doubling 20.",
      D: "Adding 30 overshoots the doubling pattern.",
    },
    difficulty: "Medium",
    tags: ["patterns", "dinosaurs", "math"],
    timeEstimate: 60,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "In a Seattle zoo, a wolf sees exhibit signs: 3, 6, 12—what’s the next number?",
    options: ["A) 15", "B) 18", "C) 24", "D) 30"],
    correctAnswer: "C",
    hint: "Look for a pattern where each number is multiplied.",
    correctAnswerExplanation:
      "The pattern is doubling: 3 × 2 = 6, 6 × 2 = 12, so 12 × 2 = 24. The wolf in a zoo makes this pattern fun to spot!",
    incorrectAnswersExplanation: {
      A: "Adding 3 doesn’t match the doubling pattern.",
      B: "Adding 6 is less than doubling 12.",
      D: "Adding 18 overshoots the doubling rule.",
    },
    difficulty: "Hard",
    tags: ["patterns", "wolves", "math"],
    timeEstimate: 90,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "At a Boston library, a dog sees book page counts: 10, 20, 30—what’s the next number?",
    options: ["A) 35", "B) 40", "C) 45", "D) 50"],
    correctAnswer: "B",
    hint: "Check the difference between each page count.",
    correctAnswerExplanation:
      "The pattern is adding 10 each time: 10 + 10 = 20, 20 + 10 = 30, so 30 + 10 = 40. The dog in a library makes this easy to follow!",
    incorrectAnswersExplanation: {
      A: "Adding 5 breaks the +10 pattern.",
      C: "Adding 15 is too much for the pattern.",
      D: "Adding 20 overshoots the +10 rule.",
    },
    difficulty: "Medium",
    tags: ["patterns", "dogs", "reading"],
    timeEstimate: 60,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "In a Denver museum, a T-Rex sees exhibit years: 1800, 1850, 1900—what’s the next year?",
    options: ["A) 1925", "B) 1950", "C) 1975", "D) 2000"],
    correctAnswer: "B",
    hint: "Look at the gap between each year.",
    correctAnswerExplanation:
      "The pattern is adding 50 years: 1800 + 50 = 1850, 1850 + 50 = 1900, so 1900 + 50 = 1950. The T-Rex in a museum makes this historical pattern fun!",
    incorrectAnswersExplanation: {
      A: "Adding 25 years is too short for the 50-year pattern.",
      C: "Adding 75 years is too long.",
      D: "Adding 100 years skips the 50-year rule.",
    },
    difficulty: "Hard",
    tags: ["patterns", "dinosaurs", "history"],
    timeEstimate: 90,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "At a Miami zoo, a wolf counts visitors: 4, 8, 12—what’s the next number?",
    options: ["A) 14", "B) 16", "C) 18", "D) 20"],
    correctAnswer: "B",
    hint: "Check how much is added each time.",
    correctAnswerExplanation:
      "The pattern is adding 4 each time: 4 + 4 = 8, 8 + 4 = 12, so 12 + 4 = 16. The wolf in a zoo makes this pattern easy to spot!",
    incorrectAnswersExplanation: {
      A: "Adding 2 breaks the +4 pattern.",
      C: "Adding 6 is too much for the pattern.",
      D: "Adding 8 overshoots the +4 rule.",
    },
    difficulty: "Medium",
    tags: ["patterns", "wolves", "math"],
    timeEstimate: 60,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "In a Los Angeles library, a dog sees book codes: A1, B2, C3—what’s the next code?",
    options: ["A) C4", "B) D3", "C) D4", "D) E4"],
    correctAnswer: "C",
    hint: "Look at how the letter and number change together.",
    correctAnswerExplanation:
      "The pattern is the next letter and number: A1 (1st letter, 1), B2 (2nd letter, 2), C3 (3rd letter, 3), so D4 (4th letter, 4). The dog in a library makes this fun!",
    incorrectAnswersExplanation: {
      A: "C4 uses the wrong letter (C instead of D).",
      B: "D3 uses the wrong number (3 instead of 4).",
      D: "E4 skips to the 5th letter, not the 4th.",
    },
    difficulty: "Hard",
    tags: ["patterns", "dogs", "codes"],
    timeEstimate: 90,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "At a Phoenix museum, a T-Rex sees artifact ages: 100, 200, 400—what’s the next number?",
    options: ["A) 500", "B) 600", "C) 700", "D) 800"],
    correctAnswer: "D",
    hint: "Check if the numbers are doubling or increasing in a pattern.",
    correctAnswerExplanation:
      "The pattern is doubling: 100 × 2 = 200, 200 × 2 = 400, so 400 × 2 = 800. The T-Rex in a museum makes this pattern exciting!",
    incorrectAnswersExplanation: {
      A: "Adding 100 doesn’t follow the doubling rule.",
      B: "Adding 200 is less than doubling 400.",
      C: "Adding 300 is still less than doubling.",
    },
    difficulty: "Medium",
    tags: ["patterns", "dinosaurs", "math"],
    timeEstimate: 60,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "In a San Diego zoo, a wolf sees animal tags: Z1, Y2, X3—what’s the next tag?",
    options: ["A) W4", "B) X4", "C) Y4", "D) Z4"],
    correctAnswer: "A",
    hint: "Notice the letter goes backward and the number goes forward.",
    correctAnswerExplanation:
      "The pattern is the previous letter and next number: Z1 (26th letter, 1), Y2 (25th letter, 2), X3 (24th letter, 3), so W4 (23rd letter, 4). The wolf in a zoo makes this fun!",
    incorrectAnswersExplanation: {
      B: "X4 uses the wrong letter (X instead of W).",
      C: "Y4 uses the wrong letter (Y instead of W).",
      D: "Z4 uses the wrong letter (Z instead of W).",
    },
    difficulty: "Hard",
    tags: ["patterns", "wolves", "codes"],
    timeEstimate: 90,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "At a Dallas library, a dog sees book prices: $5, $10, $20—what’s the next price?",
    options: ["A) $25", "B) $30", "C) $40", "D) $50"],
    correctAnswer: "C",
    hint: "Check if the prices are doubling each time.",
    correctAnswerExplanation:
      "The pattern is doubling: $5 × 2 = $10, $10 × 2 = $20, so $20 × 2 = $40. The dog in a library makes this pattern fun to spot!",
    incorrectAnswersExplanation: {
      A: "Adding $5 doesn’t follow the doubling rule.",
      B: "Adding $10 is less than doubling $20.",
      D: "Adding $30 overshoots the doubling pattern.",
    },
    difficulty: "Medium",
    tags: ["patterns", "dogs", "math"],
    timeEstimate: 60,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "In a Philadelphia museum, a T-Rex sees exhibit sizes: 2 ft, 4 ft, 8 ft—what’s the next size?",
    options: ["A) 10 ft", "B) 12 ft", "C) 16 ft", "D) 20 ft"],
    correctAnswer: "C",
    hint: "Look for a pattern where the size doubles.",
    correctAnswerExplanation:
      "The pattern is doubling: 2 × 2 = 4, 4 × 2 = 8, so 8 × 2 = 16. The T-Rex in a museum makes this pattern exciting!",
    incorrectAnswersExplanation: {
      A: "Adding 2 ft doesn’t follow the doubling rule.",
      B: "Adding 4 ft is less than doubling 8 ft.",
      D: "Adding 12 ft overshoots the doubling pattern.",
    },
    difficulty: "Hard",
    tags: ["patterns", "dinosaurs", "measurement"],
    timeEstimate: 90,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "At a Houston zoo, a wolf sees feeding amounts: 1 lb, 3 lb, 6 lb—what’s the next amount?",
    options: ["A) 8 lb", "B) 10 lb", "C) 12 lb", "D) 15 lb"],
    correctAnswer: "B",
    hint: "Notice the differences between the amounts increase by 1.",
    correctAnswerExplanation:
      "The pattern is triangular numbers: 1, 1+2=3, 3+3=6, so 6+4=10. The wolf in a zoo makes this pattern fun to solve!",
    incorrectAnswersExplanation: {
      A: "Adding 2 lb doesn’t follow the increasing difference pattern.",
      C: "Adding 6 lb skips the +4 step.",
      D: "Adding 9 lb is too large for the pattern.",
    },
    difficulty: "Medium",
    tags: ["patterns", "wolves", "math"],
    timeEstimate: 60,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "In a Nashville library, a dog sees book editions: 1st, 3rd, 6th—what’s the next edition?",
    options: ["A) 7th", "B) 8th", "C) 10th", "D) 12th"],
    correctAnswer: "C",
    hint: "Check the differences between the edition numbers.",
    correctAnswerExplanation:
      "The pattern is adding 2, then 3, then 4: 1 + 2 = 3, 3 + 3 = 6, so 6 + 4 = 10. The dog in a library makes this pattern fun!",
    incorrectAnswersExplanation: {
      A: "Adding 1 doesn’t match the increasing difference pattern.",
      B: "Adding 2 breaks the +1 difference increase.",
      D: "Adding 6 is too large for the pattern.",
    },
    difficulty: "Hard",
    tags: ["patterns", "dogs", "reading"],
    timeEstimate: 90,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "At a St. Louis museum, a T-Rex sees fossil weights: 10 kg, 20 kg, 40 kg—what’s the next weight?",
    options: ["A) 50 kg", "B) 60 kg", "C) 80 kg", "D) 100 kg"],
    correctAnswer: "C",
    hint: "Check if the weights are doubling each time.",
    correctAnswerExplanation:
      "The pattern is doubling: 10 × 2 = 20, 20 × 2 = 40, so 40 × 2 = 80. The T-Rex in a museum makes this pattern exciting!",
    incorrectAnswersExplanation: {
      A: "Adding 10 kg doesn’t follow the doubling rule.",
      B: "Adding 20 kg is less than doubling 40 kg.",
      D: "Adding 60 kg overshoots the doubling pattern.",
    },
    difficulty: "Medium",
    tags: ["patterns", "dinosaurs", "measurement"],
    timeEstimate: 60,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Patterns",
    grade: 6,
    questionType: "MC",
    question:
      "In a Detroit zoo, a wolf sees animal heights: 2 ft, 5 ft, 11 ft—what’s the next height?",
    options: ["A) 14 ft", "B) 20 ft", "C) 26 ft", "D) 32 ft"],
    correctAnswer: "B",
    hint: "Notice the differences between heights increase in a pattern.",
    correctAnswerExplanation:
      "The pattern is adding 3, then 6, then 9: 2 + 3 = 5, 5 + 6 = 11, so 11 + 9 = 20. The wolf in a zoo makes this pattern fun!",
    incorrectAnswersExplanation: {
      A: "Adding 3 again breaks the increasing difference pattern.",
      C: "Adding 15 is too large for the +9 step.",
      D: "Adding 21 overshoots the pattern.",
    },
    difficulty: "Hard",
    tags: ["patterns", "wolves", "measurement"],
    timeEstimate: 90,
    webLink: "https://www.mathplayground.com/logic_games.html",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Logic Problems",
    grade: 6,
    questionType: "MC",
    question:
      "At an Ohio school, a T-Rex, a wolf, and a dog are lined up. The T-Rex is taller than the dog but shorter than the wolf. Who’s tallest?",
    options: ["A) T-Rex", "B) Wolf", "C) Dog", "D) All are the same"],
    correctAnswer: "B",
    hint: "Compare the heights based on the clues given.",
    correctAnswerExplanation:
      "The wolf is tallest because the T-Rex is shorter than the wolf, and the dog is shorter than the T-Rex. So, wolf > T-Rex > dog.",
    incorrectAnswersExplanation: {
      A: "The T-Rex is shorter than the wolf, so it’s not tallest.",
      C: "The dog is shorter than the T-Rex, so it’s not tallest.",
      D: "The clues show different heights, so they aren’t the same.",
    },
    difficulty: "Medium",
    tags: ["logic problems", "dinosaurs", "wolves", "dogs"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/logic-puzzles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Logic Problems",
    grade: 6,
    questionType: "MC",
    question:
      "In a Chicago library, three books (A, B, C) are on a shelf. Book A is to the left of Book B, and Book C is to the right of Book B. Which book is in the middle?",
    options: ["A) Book A", "B) Book B", "C) Book C", "D) None"],
    correctAnswer: "B",
    hint: "Arrange the books based on their positions relative to each other.",
    correctAnswerExplanation:
      "Book B is in the middle because Book A is to its left and Book C is to its right, making the order A, B, C. The library setting makes this puzzle fun!",
    incorrectAnswersExplanation: {
      A: "Book A is on the left, not in the middle.",
      C: "Book C is on the right, not in the middle.",
      D: "There is a middle book, so ‘none’ is incorrect.",
    },
    difficulty: "Hard",
    tags: ["logic problems", "books", "ordering"],
    timeEstimate: 90,
    webLink: "https://www.puzzlebaron.com/logic-puzzles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Logic Problems",
    grade: 6,
    questionType: "MC",
    question:
      "At a Florida zoo, a dog, a wolf, and a T-Rex each have a favorite food: bone, fish, or steak. The dog doesn’t like fish. The T-Rex likes steak. What is the wolf’s favorite food?",
    options: ["A) Bone", "B) Fish", "C) Steak", "D) None"],
    correctAnswer: "B",
    hint: "Use the clues to eliminate foods for each animal.",
    correctAnswerExplanation:
      "The T-Rex likes steak, so steak is taken. The dog doesn’t like fish, so the dog must like the bone. This leaves fish as the wolf’s favorite food.",
    incorrectAnswersExplanation: {
      A: "The bone is the dog’s favorite, not the wolf’s.",
      C: "Steak is the T-Rex’s favorite, not the wolf’s.",
      D: "The wolf has a favorite food, so ‘none’ is wrong.",
    },
    difficulty: "Medium",
    tags: ["logic problems", "dogs", "wolves", "dinosaurs"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/logic-puzzles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Logic Problems",
    grade: 6,
    questionType: "MC",
    question:
      "In a Texas museum, three fossils (A, B, C) are displayed. Fossil A is older than Fossil B, and Fossil B is older than Fossil C. Which fossil is the youngest?",
    options: [
      "A) Fossil A",
      "B) Fossil B",
      "C) Fossil C",
      "D) All are the same",
    ],
    correctAnswer: "C",
    hint: "Compare the ages based on the clues.",
    correctAnswerExplanation:
      "Fossil C is the youngest because Fossil A is older than Fossil B, and Fossil B is older than Fossil C, so A > B > C. The museum setting makes this fun!",
    incorrectAnswersExplanation: {
      A: "Fossil A is the oldest, not the youngest.",
      B: "Fossil B is older than C, so it’s not the youngest.",
      D: "The fossils have different ages, so they aren’t the same.",
    },
    difficulty: "Hard",
    tags: ["logic problems", "fossils", "ordering"],
    timeEstimate: 90,
    webLink: "https://www.puzzlebaron.com/logic-puzzles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Logic Problems",
    grade: 6,
    questionType: "MC",
    question:
      "At a California school, a dog, a wolf, and a T-Rex are in a play. The dog is not the hero. The T-Rex is the villain. Who is the hero?",
    options: ["A) Dog", "B) Wolf", "C) T-Rex", "D) None"],
    correctAnswer: "B",
    hint: "Eliminate roles based on the clues.",
    correctAnswerExplanation:
      "The T-Rex is the villain, so it’s not the hero. The dog is not the hero, leaving the wolf as the hero. The school play setting makes this fun!",
    incorrectAnswersExplanation: {
      A: "The dog is not the hero, so it can’t be the answer.",
      C: "The T-Rex is the villain, not the hero.",
      D: "There is a hero, so ‘none’ is incorrect.",
    },
    difficulty: "Medium",
    tags: ["logic problems", "dogs", "wolves", "dinosaurs"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/logic-puzzles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Logic Problems",
    grade: 6,
    questionType: "MC",
    question:
      "In a Seattle library, three students (A, B, C) borrow books. Student A borrows a dinosaur book. Student B does not borrow a wolf book. Student C borrows a dog book. What does Student B borrow?",
    options: ["A) Dinosaur book", "B) Wolf book", "C) Dog book", "D) None"],
    correctAnswer: "D",
    hint: "List the books and match them with the students.",
    correctAnswerExplanation:
      "Student A has the dinosaur book, and Student C has the dog book. Student B doesn’t borrow the wolf book, and since the other books are taken, B borrows none. The library setting makes this tricky but fun!",
    incorrectAnswersExplanation: {
      A: "The dinosaur book is taken by Student A.",
      B: "Student B does not borrow the wolf book.",
      C: "The dog book is taken by Student C.",
    },
    difficulty: "Hard",
    tags: ["logic problems", "books", "students"],
    timeEstimate: 90,
    webLink: "https://www.puzzlebaron.com/logic-puzzles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Logic Problems",
    grade: 6,
    questionType: "MC",
    question:
      "At a Boston zoo, three animals (dog, wolf, T-Rex) are in pens 1, 2, 3. The dog is not in pen 1. The T-Rex is in pen 3. Where is the wolf?",
    options: ["A) Pen 1", "B) Pen 2", "C) Pen 3", "D) None"],
    correctAnswer: "B",
    hint: "Place each animal in a pen based on the clues.",
    correctAnswerExplanation:
      "The T-Rex is in pen 3, so pen 3 is taken. The dog is not in pen 1, so the dog must be in pen 2, leaving pen 1 for the wolf. The zoo setting makes this fun!",
    incorrectAnswersExplanation: {
      A: "The wolf is not in pen 1 because the dog is not in pen 1, and pen 2 is taken.",
      C: "Pen 3 is taken by the T-Rex.",
      D: "The wolf is in a pen, so ‘none’ is wrong.",
    },
    difficulty: "Medium",
    tags: ["logic problems", "dogs", "wolves", "dinosaurs"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/logic-puzzles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Logic Problems",
    grade: 6,
    questionType: "MC",
    question:
      "In a Denver museum, three artifacts (A, B, C) are in cases 1, 2, 3. Artifact A is not in case 2. Artifact C is in case 3. Where is Artifact B?",
    options: ["A) Case 1", "B) Case 2", "C) Case 3", "D) None"],
    correctAnswer: "B",
    hint: "Assign artifacts to cases using the clues.",
    correctAnswerExplanation:
      "Artifact C is in case 3, so case 3 is taken. Artifact A is not in case 2, so A must be in case 1, leaving case 2 for Artifact B. The museum setting makes this fun!",
    incorrectAnswersExplanation: {
      A: "Case 1 has Artifact A, not B.",
      C: "Case 3 has Artifact C, not B.",
      D: "Artifact B is in a case, so ‘none’ is wrong.",
    },
    difficulty: "Hard",
    tags: ["logic problems", "artifacts", "ordering"],
    timeEstimate: 90,
    webLink: "https://www.puzzlebaron.com/logic-puzzles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Logic Problems",
    grade: 6,
    questionType: "MC",
    question:
      "At a Miami school, three students (A, B, C) write stories about a dog, a wolf, or a T-Rex. Student A doesn’t write about a dog. Student C writes about a T-Rex. What does Student B write about?",
    options: ["A) Dog", "B) Wolf", "C) T-Rex", "D) None"],
    correctAnswer: "A",
    hint: "Match each student to a story topic.",
    correctAnswerExplanation:
      "Student C writes about a T-Rex, so T-Rex is taken. Student A doesn’t write about a dog, so A writes about a wolf, leaving the dog for Student B. The school setting makes this fun!",
    incorrectAnswersExplanation: {
      B: "The wolf is taken by Student A.",
      C: "The T-Rex is taken by Student C.",
      D: "Student B writes a story, so ‘none’ is wrong.",
    },
    difficulty: "Medium",
    tags: ["logic problems", "students", "writing"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/logic-puzzles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Logic Problems",
    grade: 6,
    questionType: "MC",
    question:
      "In a Los Angeles zoo, three animals (dog, wolf, T-Rex) have colors: red, blue, green. The dog is not red. The T-Rex is green. What color is the wolf?",
    options: ["A) Red", "B) Blue", "C) Green", "D) None"],
    correctAnswer: "B",
    hint: "Assign colors based on the clues.",
    correctAnswerExplanation:
      "The T-Rex is green, so green is taken. The dog is not red, so the dog is blue, leaving red for the wolf. The zoo setting makes this colorful puzzle fun!",
    incorrectAnswersExplanation: {
      A: "Red is not the wolf’s color; it’s likely the dog’s.",
      C: "Green is taken by the T-Rex.",
      D: "The wolf has a color, so ‘none’ is wrong.",
    },
    difficulty: "Hard",
    tags: ["logic problems", "dogs", "wolves", "dinosaurs"],
    timeEstimate: 90,
    webLink: "https://www.puzzlebaron.com/logic-puzzles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Logic Problems",
    grade: 6,
    questionType: "MC",
    question:
      "At a Phoenix library, three books (A, B, C) are on shelves 1, 2, 3. Book A is not on shelf 3. Book C is on shelf 2. Where is Book B?",
    options: ["A) Shelf 1", "B) Shelf 2", "C) Shelf 3", "D) None"],
    correctAnswer: "C",
    hint: "Place each book on a shelf using the clues.",
    correctAnswerExplanation:
      "Book C is on shelf 2, so shelf 2 is taken. Book A is not on shelf 3, so A must be on shelf 1, leaving shelf 3 for Book B. The library setting makes this fun!",
    incorrectAnswersExplanation: {
      A: "Shelf 1 has Book A, not B.",
      B: "Shelf 2 has Book C, not B.",
      D: "Book B is on a shelf, so ‘none’ is wrong.",
    },
    difficulty: "Medium",
    tags: ["logic problems", "books", "ordering"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/logic-puzzles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Logic Problems",
    grade: 6,
    questionType: "MC",
    question:
      "In a San Diego museum, three fossils (A, B, C) are from different eras: Jurassic, Cretaceous, Triassic. Fossil A is not from the Jurassic. Fossil C is from the Triassic. What era is Fossil B from?",
    options: ["A) Jurassic", "B) Cretaceous", "C) Triassic", "D) None"],
    correctAnswer: "A",
    hint: "Match each fossil to an era using the clues.",
    correctAnswerExplanation:
      "Fossil C is from the Triassic, so Triassic is taken. Fossil A is not from the Jurassic, so A is from the Cretaceous, leaving the Jurassic for Fossil B. The museum setting makes this fun!",
    incorrectAnswersExplanation: {
      B: "Cretaceous is taken by Fossil A.",
      C: "Triassic is taken by Fossil C.",
      D: "Fossil B is from an era, so ‘none’ is wrong.",
    },
    difficulty: "Hard",
    tags: ["logic problems", "fossils", "dinosaurs"],
    timeEstimate: 90,
    webLink: "https://www.puzzlebaron.com/logic-puzzles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Logic Problems",
    grade: 6,
    questionType: "MC",
    question:
      "At a Dallas zoo, three animals (dog, wolf, T-Rex) are in shows at 1 PM, 2 PM, 3 PM. The dog is not at 1 PM. The T-Rex is at 3 PM. What time is the wolf’s show?",
    options: ["A) 1 PM", "B) 2 PM", "C) 3 PM", "D) None"],
    correctAnswer: "A",
    hint: "Assign each animal to a show time using the clues.",
    correctAnswerExplanation:
      "The T-Rex is at 3 PM, so 3 PM is taken. The dog is not at 1 PM, so the dog is at 2 PM, leaving 1 PM for the wolf. The zoo setting makes this fun!",
    incorrectAnswersExplanation: {
      B: "2 PM has the dog, not the wolf.",
      C: "3 PM has the T-Rex, not the wolf.",
      D: "The wolf has a show, so ‘none’ is wrong.",
    },
    difficulty: "Medium",
    tags: ["logic problems", "dogs", "wolves", "dinosaurs"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/logic-puzzles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Logic Problems",
    grade: 6,
    questionType: "MC",
    question:
      "In a Philadelphia library, three students (A, B, C) read books about dogs, wolves, or T-Rexes. Student A doesn’t read about wolves. Student C reads about dogs. What does Student B read about?",
    options: ["A) Dogs", "B) Wolves", "C) T-Rexes", "D) None"],
    correctAnswer: "C",
    hint: "Match each student to a book topic.",
    correctAnswerExplanation:
      "Student C reads about dogs, so dogs are taken. Student A doesn’t read about wolves, so A reads about T-Rexes, leaving wolves for Student B. The library setting makes this fun!",
    incorrectAnswersExplanation: {
      A: "Dogs are taken by Student C.",
      B: "Wolves are not read by Student A, but by B.",
      D: "Student B reads a book, so ‘none’ is wrong.",
    },
    difficulty: "Hard",
    tags: ["logic problems", "students", "reading"],
    timeEstimate: 90,
    webLink: "https://www.puzzlebaron.com/logic-puzzles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Logic Puzzles",
    topic: "Logic Problems",
    grade: 6,
    questionType: "MC",
    question:
      "At a Houston museum, three artifacts (A, B, C) are in rooms 1, 2, 3. Artifact A is not in room 1. Artifact C is in room 2. Where is Artifact B?",
    options: ["A) Room 1", "B) Room 2", "C) Room 3", "D) None"],
    correctAnswer: "A",
    hint: "Place each artifact in a room using the clues.",
    correctAnswerExplanation:
      "Artifact C is in room 2, so room 2 is taken. Artifact A is not in room 1, so A is in room 3, leaving room 1 for Artifact B. The museum setting makes this fun!",
    incorrectAnswersExplanation: {
      B: "Room 2 has Artifact C, not B.",
      C: "Room 3 has Artifact A, not B.",
      D: "Artifact B is in a room, so ‘none’ is wrong.",
    },
    difficulty: "Medium",
    tags: ["logic problems", "artifacts", "ordering"],
    timeEstimate: 60,
    webLink: "https://www.puzzlebaron.com/logic-puzzles/",
    source: "Grok",
    lastUpdated: "2025-04-23",
  },
];

export default logicPuzzlesGrade6Questions;
