const mathematicsGrade6Questions = [
  {
    subject: "Mathematics",
    topic: "Fractions",
    grade: 6,
    questionType: "MC",
    question: "Sample question #1 on fractions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["fractions"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-adding-fractions/v/adding-fractions-with-different-denominators",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Fractions",
    grade: 6,
    questionType: "MC",
    question: "Sample question #2 on fractions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["fractions"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-adding-fractions/v/adding-fractions-with-different-denominators",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Fractions",
    grade: 6,
    questionType: "MC",
    question: "Sample question #3 on fractions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["fractions"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-adding-fractions/v/adding-fractions-with-different-denominators",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Fractions",
    grade: 6,
    questionType: "MC",
    question: "Sample question #4 on fractions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["fractions"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-adding-fractions/v/adding-fractions-with-different-denominators",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Fractions",
    grade: 6,
    questionType: "MC",
    question: "Sample question #5 on fractions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["fractions"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-adding-fractions/v/adding-fractions-with-different-denominators",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Fractions",
    grade: 6,
    questionType: "MC",
    question: "Sample question #6 on fractions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["fractions"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-adding-fractions/v/adding-fractions-with-different-denominators",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Fractions",
    grade: 6,
    questionType: "MC",
    question: "Sample question #7 on fractions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["fractions"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-adding-fractions/v/adding-fractions-with-different-denominators",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Fractions",
    grade: 6,
    questionType: "MC",
    question: "Sample question #8 on fractions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["fractions"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-adding-fractions/v/adding-fractions-with-different-denominators",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Fractions",
    grade: 6,
    questionType: "MC",
    question: "Sample question #9 on fractions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["fractions"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-adding-fractions/v/adding-fractions-with-different-denominators",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Fractions",
    grade: 6,
    questionType: "MC",
    question: "Sample question #10 on fractions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["fractions"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-adding-fractions/v/adding-fractions-with-different-denominators",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Decimals",
    grade: 6,
    questionType: "MC",
    question: "Sample question #11 on decimals with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["decimals"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-dividing-decimals/v/dividing-a-decimal-by-a-decimal",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Decimals",
    grade: 6,
    questionType: "MC",
    question: "Sample question #12 on decimals with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["decimals"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-dividing-decimals/v/dividing-a-decimal-by-a-decimal",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Decimals",
    grade: 6,
    questionType: "MC",
    question: "Sample question #13 on decimals with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["decimals"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-dividing-decimals/v/dividing-a-decimal-by-a-decimal",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Decimals",
    grade: 6,
    questionType: "MC",
    question: "Sample question #14 on decimals with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["decimals"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-dividing-decimals/v/dividing-a-decimal-by-a-decimal",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Decimals",
    grade: 6,
    questionType: "MC",
    question: "Sample question #15 on decimals with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["decimals"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-dividing-decimals/v/dividing-a-decimal-by-a-decimal",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Decimals",
    grade: 6,
    questionType: "MC",
    question: "Sample question #16 on decimals with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["decimals"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-dividing-decimals/v/dividing-a-decimal-by-a-decimal",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Decimals",
    grade: 6,
    questionType: "MC",
    question: "Sample question #17 on decimals with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["decimals"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-dividing-decimals/v/dividing-a-decimal-by-a-decimal",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Decimals",
    grade: 6,
    questionType: "MC",
    question: "Sample question #18 on decimals with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["decimals"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-dividing-decimals/v/dividing-a-decimal-by-a-decimal",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Decimals",
    grade: 6,
    questionType: "MC",
    question: "Sample question #19 on decimals with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["decimals"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-dividing-decimals/v/dividing-a-decimal-by-a-decimal",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Decimals",
    grade: 6,
    questionType: "MC",
    question: "Sample question #20 on decimals with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["decimals"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-dividing-decimals/v/dividing-a-decimal-by-a-decimal",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Ratios and Proportions",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #21 on ratios and proportions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["ratios-and-proportions"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Ratios and Proportions",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #22 on ratios and proportions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["ratios-and-proportions"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Ratios and Proportions",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #23 on ratios and proportions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["ratios-and-proportions"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Ratios and Proportions",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #24 on ratios and proportions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["ratios-and-proportions"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Ratios and Proportions",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #25 on ratios and proportions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["ratios-and-proportions"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Ratios and Proportions",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #26 on ratios and proportions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["ratios-and-proportions"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Ratios and Proportions",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #27 on ratios and proportions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["ratios-and-proportions"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Ratios and Proportions",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #28 on ratios and proportions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["ratios-and-proportions"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Ratios and Proportions",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #29 on ratios and proportions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["ratios-and-proportions"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Ratios and Proportions",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #30 on ratios and proportions with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["ratios-and-proportions"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Percentages",
    grade: 6,
    questionType: "MC",
    question: "Sample question #31 on percentages with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["percentages"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-percent-word-problems/v/percent-word-problems-example-1",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Percentages",
    grade: 6,
    questionType: "MC",
    question: "Sample question #32 on percentages with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["percentages"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-percent-word-problems/v/percent-word-problems-example-1",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Percentages",
    grade: 6,
    questionType: "MC",
    question: "Sample question #33 on percentages with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["percentages"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-percent-word-problems/v/percent-word-problems-example-1",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Percentages",
    grade: 6,
    questionType: "MC",
    question: "Sample question #34 on percentages with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["percentages"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-percent-word-problems/v/percent-word-problems-example-1",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Percentages",
    grade: 6,
    questionType: "MC",
    question: "Sample question #35 on percentages with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["percentages"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-percent-word-problems/v/percent-word-problems-example-1",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Percentages",
    grade: 6,
    questionType: "MC",
    question: "Sample question #36 on percentages with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["percentages"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-percent-word-problems/v/percent-word-problems-example-1",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Percentages",
    grade: 6,
    questionType: "MC",
    question: "Sample question #37 on percentages with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["percentages"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-percent-word-problems/v/percent-word-problems-example-1",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Percentages",
    grade: 6,
    questionType: "MC",
    question: "Sample question #38 on percentages with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["percentages"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-percent-word-problems/v/percent-word-problems-example-1",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Percentages",
    grade: 6,
    questionType: "MC",
    question: "Sample question #39 on percentages with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["percentages"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-percent-word-problems/v/percent-word-problems-example-1",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Percentages",
    grade: 6,
    questionType: "MC",
    question: "Sample question #40 on percentages with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["percentages"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-percent-word-problems/v/percent-word-problems-example-1",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Geometry",
    grade: 6,
    questionType: "MC",
    question: "Sample question #41 on geometry with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["geometry"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Geometry",
    grade: 6,
    questionType: "MC",
    question: "Sample question #42 on geometry with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["geometry"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Geometry",
    grade: 6,
    questionType: "MC",
    question: "Sample question #43 on geometry with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["geometry"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Geometry",
    grade: 6,
    questionType: "MC",
    question: "Sample question #44 on geometry with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["geometry"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Geometry",
    grade: 6,
    questionType: "MC",
    question: "Sample question #45 on geometry with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["geometry"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Geometry",
    grade: 6,
    questionType: "MC",
    question: "Sample question #46 on geometry with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["geometry"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Geometry",
    grade: 6,
    questionType: "MC",
    question: "Sample question #47 on geometry with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["geometry"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Geometry",
    grade: 6,
    questionType: "MC",
    question: "Sample question #48 on geometry with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["geometry"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Geometry",
    grade: 6,
    questionType: "MC",
    question: "Sample question #49 on geometry with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["geometry"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Geometry",
    grade: 6,
    questionType: "MC",
    question: "Sample question #50 on geometry with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["geometry"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Algebra",
    grade: 6,
    questionType: "MC",
    question: "Sample question #51 on algebra with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["algebra"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Algebra",
    grade: 6,
    questionType: "MC",
    question: "Sample question #52 on algebra with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["algebra"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Algebra",
    grade: 6,
    questionType: "MC",
    question: "Sample question #53 on algebra with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["algebra"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Algebra",
    grade: 6,
    questionType: "MC",
    question: "Sample question #54 on algebra with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["algebra"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Algebra",
    grade: 6,
    questionType: "MC",
    question: "Sample question #55 on algebra with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["algebra"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Algebra",
    grade: 6,
    questionType: "MC",
    question: "Sample question #56 on algebra with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["algebra"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Algebra",
    grade: 6,
    questionType: "MC",
    question: "Sample question #57 on algebra with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["algebra"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Algebra",
    grade: 6,
    questionType: "MC",
    question: "Sample question #58 on algebra with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["algebra"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Algebra",
    grade: 6,
    questionType: "MC",
    question: "Sample question #59 on algebra with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["algebra"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Algebra",
    grade: 6,
    questionType: "MC",
    question: "Sample question #60 on algebra with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["algebra"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Word Problems",
    grade: 6,
    questionType: "MC",
    question: "Sample question #61 on word problems with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["word-problems"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-math-word-problems/v/multi-step-word-problems-with-whole-numbers",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Word Problems",
    grade: 6,
    questionType: "MC",
    question: "Sample question #62 on word problems with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["word-problems"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-math-word-problems/v/multi-step-word-problems-with-whole-numbers",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Word Problems",
    grade: 6,
    questionType: "MC",
    question: "Sample question #63 on word problems with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["word-problems"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-math-word-problems/v/multi-step-word-problems-with-whole-numbers",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Word Problems",
    grade: 6,
    questionType: "MC",
    question: "Sample question #64 on word problems with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["word-problems"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-math-word-problems/v/multi-step-word-problems-with-whole-numbers",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Word Problems",
    grade: 6,
    questionType: "MC",
    question: "Sample question #65 on word problems with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["word-problems"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-math-word-problems/v/multi-step-word-problems-with-whole-numbers",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Word Problems",
    grade: 6,
    questionType: "MC",
    question: "Sample question #66 on word problems with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["word-problems"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-math-word-problems/v/multi-step-word-problems-with-whole-numbers",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Word Problems",
    grade: 6,
    questionType: "MC",
    question: "Sample question #67 on word problems with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["word-problems"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-math-word-problems/v/multi-step-word-problems-with-whole-numbers",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Word Problems",
    grade: 6,
    questionType: "MC",
    question: "Sample question #68 on word problems with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["word-problems"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-math-word-problems/v/multi-step-word-problems-with-whole-numbers",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Word Problems",
    grade: 6,
    questionType: "MC",
    question: "Sample question #69 on word problems with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["word-problems"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-math-word-problems/v/multi-step-word-problems-with-whole-numbers",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Word Problems",
    grade: 6,
    questionType: "MC",
    question: "Sample question #70 on word problems with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["word-problems"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-math-word-problems/v/multi-step-word-problems-with-whole-numbers",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Number Sense",
    grade: 6,
    questionType: "MC",
    question: "Sample question #71 on number sense with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["number-sense"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/arithmetic/arith-review-place-value/arith-review-place-value-intro/v/place-value",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Number Sense",
    grade: 6,
    questionType: "MC",
    question: "Sample question #72 on number sense with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["number-sense"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/arithmetic/arith-review-place-value/arith-review-place-value-intro/v/place-value",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Number Sense",
    grade: 6,
    questionType: "MC",
    question: "Sample question #73 on number sense with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["number-sense"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/arithmetic/arith-review-place-value/arith-review-place-value-intro/v/place-value",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Number Sense",
    grade: 6,
    questionType: "MC",
    question: "Sample question #74 on number sense with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["number-sense"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/arithmetic/arith-review-place-value/arith-review-place-value-intro/v/place-value",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Number Sense",
    grade: 6,
    questionType: "MC",
    question: "Sample question #75 on number sense with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["number-sense"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/arithmetic/arith-review-place-value/arith-review-place-value-intro/v/place-value",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Number Sense",
    grade: 6,
    questionType: "MC",
    question: "Sample question #76 on number sense with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["number-sense"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/arithmetic/arith-review-place-value/arith-review-place-value-intro/v/place-value",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Number Sense",
    grade: 6,
    questionType: "MC",
    question: "Sample question #77 on number sense with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["number-sense"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/arithmetic/arith-review-place-value/arith-review-place-value-intro/v/place-value",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Number Sense",
    grade: 6,
    questionType: "MC",
    question: "Sample question #78 on number sense with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["number-sense"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/arithmetic/arith-review-place-value/arith-review-place-value-intro/v/place-value",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Number Sense",
    grade: 6,
    questionType: "MC",
    question: "Sample question #79 on number sense with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["number-sense"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/arithmetic/arith-review-place-value/arith-review-place-value-intro/v/place-value",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Number Sense",
    grade: 6,
    questionType: "MC",
    question: "Sample question #80 on number sense with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["number-sense"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/arithmetic/arith-review-place-value/arith-review-place-value-intro/v/place-value",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Data and Statistics",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #81 on data and statistics with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["data-and-statistics"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Data and Statistics",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #82 on data and statistics with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["data-and-statistics"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Data and Statistics",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #83 on data and statistics with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["data-and-statistics"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Data and Statistics",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #84 on data and statistics with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["data-and-statistics"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Data and Statistics",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #85 on data and statistics with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["data-and-statistics"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Data and Statistics",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #86 on data and statistics with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["data-and-statistics"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Data and Statistics",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #87 on data and statistics with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["data-and-statistics"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Data and Statistics",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #88 on data and statistics with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["data-and-statistics"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Data and Statistics",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #89 on data and statistics with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["data-and-statistics"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Data and Statistics",
    grade: 6,
    questionType: "MC",
    question:
      "Sample question #90 on data and statistics with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["data-and-statistics"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Integers",
    grade: 6,
    questionType: "MC",
    question: "Sample question #91 on integers with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["integers"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-number-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Integers",
    grade: 6,
    questionType: "MC",
    question: "Sample question #92 on integers with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["integers"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-number-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Integers",
    grade: 6,
    questionType: "MC",
    question: "Sample question #93 on integers with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["integers"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-number-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Integers",
    grade: 6,
    questionType: "MC",
    question: "Sample question #94 on integers with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["integers"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-number-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Integers",
    grade: 6,
    questionType: "MC",
    question: "Sample question #95 on integers with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Medium",
    tags: ["integers"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-number-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Integers",
    grade: 6,
    questionType: "MC",
    question: "Sample question #96 on integers with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["integers"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-number-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Integers",
    grade: 6,
    questionType: "MC",
    question: "Sample question #97 on integers with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["integers"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-number-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Integers",
    grade: 6,
    questionType: "MC",
    question: "Sample question #98 on integers with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["integers"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-number-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Integers",
    grade: 6,
    questionType: "MC",
    question: "Sample question #99 on integers with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["integers"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-number-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Mathematics",
    topic: "Integers",
    grade: 6,
    questionType: "MC",
    question: "Sample question #100 on integers with a realistic scenario.",
    options: ["A) Option 1", "B) Option 2", "C) Option 3", "D) Option 4"],
    correctAnswer: "B",
    hint: "Think carefully about the math operation needed.",
    correctAnswerExplanation:
      "Option B is correct because it follows the proper steps to solve the question.",
    incorrectAnswersExplanation: {
      A: "This option is incorrect because it uses the wrong operation.",
      C: "This option is incorrect because it includes a calculation mistake.",
      D: "This option is incorrect due to misinterpreting the problem.",
    },
    difficulty: "Hard",
    tags: ["integers"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-number-topic",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
];
export default mathematicsGrade6Questions;
