const mathematicsGrade6Questions = [
  {
    subject: "Mathematics",
    topic: "Fractions",
    grade: 6,
    questionType: "MC",
    question: "What is 1/3 + 1/6?",
    options: ["A) 1/2", "B) 2/9", "C) 3/6", "D) 1/18"],
    correctAnswer: "A",
    hint: "Find a common denominator for the fractions.",
    correctAnswerExplanation:
      "To add 1/3 and 1/6, find a common denominator: the least common multiple of 3 and 6 is 6. Convert 1/3 to 2/6, then add 2/6 + 1/6 = 3/6, which simplifies to 1/2. So, the answer is A) 1/2.",
    incorrectAnswersExplanation: {
      B: "B) 2/9 is incorrect because it results from multiplying the fractions instead of adding them.",
      C: "C) 3/6 is incorrect because it doesn't simplify to the lowest terms, which is 1/2.",
      D: "D) 1/18 is incorrect because it comes from incorrectly multiplying the numerators and denominators.",
    },
    difficulty: "Medium",
    tags: ["fractions", "arithmetic"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-adding-fractions/v/adding-fractions-with-different-denominators",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Fractions",
    grade: 6,
    questionType: "MC",
    question:
      "A dog ‘paws-itively’ splits his bone into 3 equal parts and eats 2 parts. What fraction of the bone is left?",
    options: ["A) 1/3", "B) 2/3", "C) 1/2", "D) 3/3"],
    correctAnswer: "A",
    hint: "Subtract the fraction eaten from the whole bone.",
    correctAnswerExplanation:
      "The whole bone is 3/3. If the dog eats 2/3, subtract: 3/3 - 2/3 = 1/3. So, the answer is A) 1/3.",
    incorrectAnswersExplanation: {
      B: "B) 2/3 is incorrect because it represents the amount eaten, not what's left.",
      C: "C) 1/2 is incorrect because the bone was divided into thirds, not halves.",
      D: "D) 3/3 is incorrect because it represents the whole bone before any was eaten.",
    },
    difficulty: "Medium",
    tags: ["fractions", "subtraction"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-adding-fractions/v/subtracting-fractions",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Fractions",
    grade: 6,
    questionType: "MC",
    question: "What is 3/4 × 2/3?",
    options: ["A) 5/7", "B) 1/2", "C) 6/7", "D) 3/6"],
    correctAnswer: "B",
    hint: "Multiply the numerators and denominators separately.",
    correctAnswerExplanation:
      "To multiply 3/4 and 2/3, multiply the numerators (3 × 2 = 6) and denominators (4 × 3 = 12), so 6/12 = 1/2. So, the answer is B) 1/2.",
    incorrectAnswersExplanation: {
      A: "A) 5/7 is incorrect because it comes from adding the fractions instead of multiplying.",
      C: "C) 6/7 is incorrect because the denominator was miscalculated.",
      D: "D) 3/6 is incorrect because it uses the wrong numerators and denominators.",
    },
    difficulty: "Hard",
    tags: ["fractions", "multiplication"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-multiplying-fractions/v/multiplying-fractions",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Fractions",
    grade: 6,
    questionType: "MC",
    question: "What is 5/6 ÷ 1/3?",
    options: ["A) 5/18", "B) 2/5", "C) 5/2", "D) 1/2"],
    correctAnswer: "C",
    hint: "Multiply by the reciprocal of the second fraction.",
    correctAnswerExplanation:
      "To divide 5/6 by 1/3, multiply 5/6 by the reciprocal of 1/3, which is 3/1: (5/6) × (3/1) = 15/6 = 5/2. So, the answer is C) 5/2.",
    incorrectAnswersExplanation: {
      A: "A) 5/18 is incorrect because it results from multiplying without using the reciprocal.",
      B: "B) 2/5 is incorrect because it uses the wrong reciprocal.",
      D: "D) 1/2 is incorrect because it miscalculates the numerator and denominator.",
    },
    difficulty: "Hard",
    tags: ["fractions", "division"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-dividing-fractions/v/dividing-fractions",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Fractions",
    grade: 6,
    questionType: "MC",
    question: "Which fraction is equivalent to 4/8?",
    options: ["A) 1/4", "B) 1/2", "C) 2/3", "D) 3/4"],
    correctAnswer: "B",
    hint: "Simplify the fraction by dividing the numerator and denominator.",
    correctAnswerExplanation:
      "To find an equivalent fraction to 4/8, divide both the numerator and denominator by their greatest common factor, 4: 4 ÷ 4 = 1, 8 ÷ 4 = 2, so 4/8 = 1/2. So, the answer is B) 1/2.",
    incorrectAnswersExplanation: {
      A: "A) 1/4 is incorrect because it results from dividing by a different factor.",
      C: "C) 2/3 is incorrect because it is not equivalent to 4/8.",
      D: "D) 3/4 is incorrect because it is not equivalent to 4/8.",
    },
    difficulty: "Medium",
    tags: ["fractions", "equivalent fractions"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-equivalent-fractions/v/equivalent-fractions",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Decimals",
    grade: 6,
    questionType: "MC",
    question: "What is 0.25 + 0.75?",
    options: ["A) 0.1", "B) 1.0", "C) 0.5", "D) 1.5"],
    correctAnswer: "B",
    hint: "Line up the decimal points and add.",
    correctAnswerExplanation:
      "To add 0.25 and 0.75, align the decimals and add: 0.25 + 0.75 = 1.00, or 1.0. So, the answer is B) 1.0.",
    incorrectAnswersExplanation: {
      A: "A) 0.1 is incorrect because it underestimates the sum.",
      C: "C) 0.5 is incorrect because it results from subtracting instead of adding.",
      D: "D) 1.5 is incorrect because it overestimates the sum.",
    },
    difficulty: "Medium",
    tags: ["decimals", "addition"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-adding-decimals/v/adding-decimals",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Decimals",
    grade: 6,
    questionType: "MC",
    question: "What is 3.2 × 0.5?",
    options: ["A) 1.6", "B) 16.0", "C) 0.16", "D) 6.4"],
    correctAnswer: "A",
    hint: "Multiply as whole numbers, then adjust the decimal point.",
    correctAnswerExplanation:
      "To multiply 3.2 by 0.5, treat them as 32 × 5 = 160, then adjust for one decimal place (3.2 has one, 0.5 has one, so 160 has two): 160 ÷ 100 = 1.6. So, the answer is A) 1.6.",
    incorrectAnswersExplanation: {
      B: "B) 16.0 is incorrect because it misplaces the decimal point.",
      C: "C) 0.16 is incorrect because it uses too many decimal places.",
      D: "D) 6.4 is incorrect because it doubles the correct product.",
    },
    difficulty: "Hard",
    tags: ["decimals", "multiplication"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-multiplying-decimals/v/multiplying-decimals",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Decimals",
    grade: 6,
    questionType: "MC",
    question: "What is 4.8 ÷ 0.6?",
    options: ["A) 0.8", "B) 8.0", "C) 80.0", "D) 0.08"],
    correctAnswer: "B",
    hint: "Convert the decimals to whole numbers by multiplying both by 10.",
    correctAnswerExplanation:
      "To divide 4.8 by 0.6, multiply both by 10 to get 48 ÷ 6 = 8. So, the answer is B) 8.0.",
    incorrectAnswersExplanation: {
      A: "A) 0.8 is incorrect because it results from incorrect decimal placement.",
      C: "C) 80.0 is incorrect because it overestimates the quotient.",
      D: "D) 0.08 is incorrect because it underestimates the quotient.",
    },
    difficulty: "Hard",
    tags: ["decimals", "division"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-dividing-decimals/v/dividing-decimals",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Decimals",
    grade: 6,
    questionType: "MC",
    question: "Which decimal is equivalent to 7/10?",
    options: ["A) 0.07", "B) 0.7", "C) 7.0", "D) 0.007"],
    correctAnswer: "B",
    hint: "Divide the numerator by the denominator.",
    correctAnswerExplanation:
      "To convert 7/10 to a decimal, divide 7 by 10: 7 ÷ 10 = 0.7. So, the answer is B) 0.7.",
    incorrectAnswersExplanation: {
      A: "A) 0.07 is incorrect because it represents 7/100, not 7/10.",
      C: "C) 7.0 is incorrect because it represents 70/10.",
      D: "D) 0.007 is incorrect because it represents 7/1000.",
    },
    difficulty: "Medium",
    tags: ["decimals", "fractions"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-fractions-as-decimals/v/fractions-as-decimals",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Decimals",
    grade: 6,
    questionType: "MC",
    question: "What is 0.9 - 0.34?",
    options: ["A) 0.56", "B) 0.66", "C) 0.46", "D) 0.76"],
    correctAnswer: "A",
    hint: "Align the decimals and subtract carefully.",
    correctAnswerExplanation:
      "To subtract 0.34 from 0.9, write 0.9 as 0.90, then subtract: 0.90 - 0.34 = 0.56. So, the answer is A) 0.56.",
    incorrectAnswersExplanation: {
      B: "B) 0.66 is incorrect because it overestimates the difference.",
      C: "C) 0.46 is incorrect because it underestimates the difference.",
      D: "D) 0.76 is incorrect because it results from adding instead of subtracting.",
    },
    difficulty: "Medium",
    tags: ["decimals", "subtraction"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-adding-decimals/v/subtracting-decimals",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Ratios and Proportions",
    grade: 6,
    questionType: "MC",
    question: "If 2 apples cost $1, how much do 6 apples cost?",
    options: ["A) $2", "B) $3", "C) $4", "D) $6"],
    correctAnswer: "B",
    hint: "Find the unit price and multiply by the number of apples.",
    correctAnswerExplanation:
      "The ratio is 2 apples for $1, so 1 apple costs $0.50. For 6 apples, multiply: 6 × $0.50 = $3. So, the answer is B) $3.",
    incorrectAnswersExplanation: {
      A: "A) $2 is incorrect because it assumes a lower cost per apple.",
      C: "C) $4 is incorrect because it overestimates the cost.",
      D: "D) $6 is incorrect because it assumes each apple costs $1.",
    },
    difficulty: "Medium",
    tags: ["ratios", "proportions"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-rates/v/introduction-to-rates",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Ratios and Proportions",
    grade: 6,
    questionType: "MC",
    question:
      "If 3 pencils cost $0.75, how many pencils can you buy for $2.25?",
    options: ["A) 6", "B) 9", "C) 12", "D) 15"],
    correctAnswer: "B",
    hint: "Use a proportion to find the number of pencils.",
    correctAnswerExplanation:
      "Set up a proportion: 3 pencils/$0.75 = x pencils/$2.25. Simplify: 3/0.75 = x/2.25, so 4 = x/2.25, and x = 4 × 2.25 = 9. So, the answer is B) 9.",
    incorrectAnswersExplanation: {
      A: "A) 6 is incorrect because it underestimates the number of pencils.",
      C: "C) 12 is incorrect because it overestimates the number of pencils.",
      D: "D) 15 is incorrect because it assumes a lower cost per pencil.",
    },
    difficulty: "Hard",
    tags: ["ratios", "proportions"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-rates/v/solving-ratio-problems-with-tables",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Ratios and Proportions",
    grade: 6,
    questionType: "MC",
    question: "What is the ratio of 12 books to 18 books in simplest form?",
    options: ["A) 2:3", "B) 3:2", "C) 4:6", "D) 6:9"],
    correctAnswer: "A",
    hint: "Divide both numbers by their greatest common factor.",
    correctAnswerExplanation:
      "The ratio of 12 books to 18 books is 12:18. Divide both by their greatest common factor, 6: 12 ÷ 6 = 2, 18 ÷ 6 = 3, so the ratio is 2:3. So, the answer is A) 2:3.",
    incorrectAnswersExplanation: {
      B: "B) 3:2 is incorrect because it reverses the order of the ratio.",
      C: "C) 4:6 is incorrect because it is not fully simplified.",
      D: "D) 6:9 is incorrect because it is not fully simplified.",
    },
    difficulty: "Medium",
    tags: ["ratios", "simplification"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-ratios/v/intro-to-ratios",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Ratios and Proportions",
    grade: 6,
    questionType: "MC",
    question:
      "If a recipe uses 2 cups of flour for 8 cookies, how many cups of flour are needed for 24 cookies?",
    options: ["A) 4", "B) 6", "C) 8", "D) 10"],
    correctAnswer: "B",
    hint: "Set up a proportion to find the amount of flour.",
    correctAnswerExplanation:
      "Set up a proportion: 2 cups/8 cookies = x cups/24 cookies. Simplify: 2/8 = x/24, so 1/4 = x/24, and x = 24/4 = 6. So, the answer is B) 6.",
    incorrectAnswersExplanation: {
      A: "A) 4 is incorrect because it underestimates the flour needed.",
      C: "C) 8 is incorrect because it overestimates the flour needed.",
      D: "D) 10 is incorrect because it assumes a higher ratio.",
    },
    difficulty: "Hard",
    tags: ["ratios", "proportions"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-rates/v/solving-ratio-problems-with-tables",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Ratios and Proportions",
    grade: 6,
    questionType: "MC",
    question: "Are the ratios 4:5 and 8:10 equivalent?",
    options: ["A) Yes", "B) No", "C) Sometimes", "D) Cannot determine"],
    correctAnswer: "A",
    hint: "Simplify both ratios to compare them.",
    correctAnswerExplanation:
      "Simplify 4:5 (already simplified) and 8:10 by dividing by 2: 8 ÷ 2 = 4, 10 ÷ 2 = 5, so 8:10 = 4:5. Since they are the same, the answer is A) Yes.",
    incorrectAnswersExplanation: {
      B: "B) No is incorrect because the ratios are equivalent after simplification.",
      C: "C) Sometimes is incorrect because ratios are either equivalent or not.",
      D: "D) Cannot determine is incorrect because we can simplify and compare.",
    },
    difficulty: "Medium",
    tags: ["ratios", "equivalent ratios"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-ratios/v/equivalent-ratios",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Percentages",
    grade: 6,
    questionType: "MC",
    question: "What is 25% of 80?",
    options: ["A) 20", "B) 25", "C) 30", "D) 15"],
    correctAnswer: "A",
    hint: "Convert the percentage to a decimal and multiply.",
    correctAnswerExplanation:
      "To find 25% of 80, convert 25% to 0.25 and multiply: 0.25 × 80 = 20. So, the answer is A) 20.",
    incorrectAnswersExplanation: {
      B: "B) 25 is incorrect because it uses the percentage value itself.",
      C: "C) 30 is incorrect because it overestimates the result.",
      D: "D) 15 is incorrect because it underestimates the result.",
    },
    difficulty: "Medium",
    tags: ["percentages", "multiplication"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-percentages/v/finding-a-percent-of-a-number",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Percentages",
    grade: 6,
    questionType: "MC",
    question:
      "If a shirt costs $40 and is on sale for 20% off, what is the sale price?",
    options: ["A) $32", "B) $36", "C) $30", "D) $28"],
    correctAnswer: "A",
    hint: "Find the discount amount and subtract it from the original price.",
    correctAnswerExplanation:
      "To find the sale price, calculate 20% of $40: 0.20 × 40 = 8. Subtract the discount: $40 - $8 = $32. So, the answer is A) $32.",
    incorrectAnswersExplanation: {
      B: "B) $36 is incorrect because it underestimates the discount.",
      C: "C) $30 is incorrect because it overestimates the discount.",
      D: "D) $28 is incorrect because it assumes a larger discount.",
    },
    difficulty: "Hard",
    tags: ["percentages", "discounts"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-percent-word-problems/v/discount-tax-and-tip-word-problems",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Percentages",
    grade: 6,
    questionType: "MC",
    question: "What is 60% as a fraction in simplest form?",
    options: ["A) 6/10", "B) 3/5", "C) 60/100", "D) 3/10"],
    correctAnswer: "B",
    hint: "Write the percentage as a fraction over 100 and simplify.",
    correctAnswerExplanation:
      "To convert 60% to a fraction, write 60/100. Simplify by dividing by 20: 60 ÷ 20 = 3, 100 ÷ 20 = 5, so 60/100 = 3/5. So, the answer is B) 3/5.",
    incorrectAnswersExplanation: {
      A: "A) 6/10 is incorrect because it is not fully simplified.",
      C: "C) 60/100 is incorrect because it is not simplified.",
      D: "D) 3/10 is incorrect because it represents 30%, not 60%.",
    },
    difficulty: "Medium",
    tags: ["percentages", "fractions"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-percentages/v/percent-to-fraction",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Percentages",
    grade: 6,
    questionType: "MC",
    question: "If 15 out of 25 students passed a test, what percentage passed?",
    options: ["A) 50%", "B) 60%", "C) 75%", "D) 80%"],
    correctAnswer: "B",
    hint: "Divide the number who passed by the total and multiply by 100.",
    correctAnswerExplanation:
      "To find the percentage, divide 15 by 25: 15 ÷ 25 = 0.6. Multiply by 100: 0.6 × 100 = 60%. So, the answer is B) 60%.",
    incorrectAnswersExplanation: {
      A: "A) 50% is incorrect because it underestimates the proportion.",
      C: "C) 75% is incorrect because it overestimates the proportion.",
      D: "D) 80% is incorrect because it assumes a higher number passed.",
    },
    difficulty: "Hard",
    tags: ["percentages", "proportions"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-percentages/v/finding-percents",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Percentages",
    grade: 6,
    questionType: "MC",
    question: "What is 40% as a decimal?",
    options: ["A) 0.4", "B) 4.0", "C) 0.04", "D) 40.0"],
    correctAnswer: "A",
    hint: "Divide the percentage by 100 to convert to a decimal.",
    correctAnswerExplanation:
      "To convert 40% to a decimal, divide by 100: 40 ÷ 100 = 0.4. So, the answer is A) 0.4.",
    incorrectAnswersExplanation: {
      B: "B) 4.0 is incorrect because it represents 400%.",
      C: "C) 0.04 is incorrect because it represents 4%.",
      D: "D) 40.0 is incorrect because it represents 4000%.",
    },
    difficulty: "Medium",
    tags: ["percentages", "decimals"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-percentages/v/percent-to-decimal",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Geometry",
    grade: 6,
    questionType: "MC",
    question:
      "What is the area of a rectangle with length 8 cm and width 3 cm?",
    options: ["A) 24 cm²", "B) 22 cm²", "C) 11 cm²", "D) 48 cm²"],
    correctAnswer: "A",
    hint: "Multiply the length by the width to find the area.",
    correctAnswerExplanation:
      "The area of a rectangle is length × width. So, 8 cm × 3 cm = 24 cm². The answer is A) 24 cm².",
    incorrectAnswersExplanation: {
      B: "B) 22 cm² is incorrect because it miscalculates the product.",
      C: "C) 11 cm² is incorrect because it adds instead of multiplies.",
      D: "D) 48 cm² is incorrect because it overestimates the area.",
    },
    difficulty: "Medium",
    tags: ["geometry", "area"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic/cc-6th-area/v/rectangle-area-as-product-of-dimensions",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Geometry",
    grade: 6,
    questionType: "MC",
    question:
      "What is the perimeter of a square with a side length of 5 meters?",
    options: ["A) 10 m", "B) 15 m", "C) 20 m", "D) 25 m"],
    correctAnswer: "C",
    hint: "Add up the lengths of all four sides of the square.",
    correctAnswerExplanation:
      "The perimeter of a square is 4 × side length. So, 4 × 5 m = 20 m. The answer is C) 20 m.",
    incorrectAnswersExplanation: {
      A: "A) 10 m is incorrect because it only accounts for two sides.",
      B: "B) 15 m is incorrect because it underestimates the perimeter.",
      D: "D) 25 m is incorrect because it overestimates the perimeter.",
    },
    difficulty: "Medium",
    tags: ["geometry", "perimeter"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic/cc-6th-perimeter/v/perimeter-of-a-square",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Geometry",
    grade: 6,
    questionType: "MC",
    question:
      "What is the area of a triangle with a base of 6 cm and a height of 4 cm?",
    options: ["A) 12 cm²", "B) 24 cm²", "C) 10 cm²", "D) 15 cm²"],
    correctAnswer: "A",
    hint: "Use the formula for the area of a triangle: (base × height) ÷ 2.",
    correctAnswerExplanation:
      "The area of a triangle is (base × height) ÷ 2. So, (6 cm × 4 cm) ÷ 2 = 24 cm² ÷ 2 = 12 cm². The answer is A) 12 cm².",
    incorrectAnswersExplanation: {
      B: "B) 24 cm² is incorrect because it forgets to divide by 2.",
      C: "C) 10 cm² is incorrect because it miscalculates the product or division.",
      D: "D) 15 cm² is incorrect because it uses the wrong formula.",
    },
    difficulty: "Hard",
    tags: ["geometry", "area"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic/cc-6th-area/v/triangle-area",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Geometry",
    grade: 6,
    questionType: "MC",
    question: "How many degrees are in the interior angles of a triangle?",
    options: ["A) 180°", "B) 360°", "C) 90°", "D) 270°"],
    correctAnswer: "A",
    hint: "The sum of the interior angles of a triangle is always the same.",
    correctAnswerExplanation:
      "The sum of the interior angles of any triangle is always 180°. So, the answer is A) 180°.",
    incorrectAnswersExplanation: {
      B: "B) 360° is incorrect because it applies to quadrilaterals, not triangles.",
      C: "C) 90° is incorrect because it applies to one right angle, not the sum.",
      D: "D) 270° is incorrect because it overestimates the angle sum.",
    },
    difficulty: "Medium",
    tags: ["geometry", "angles"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic/cc-6th-angles/v/angle-basics",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Geometry",
    grade: 6,
    questionType: "MC",
    question:
      "What is the volume of a rectangular prism with length 4 cm, width 3 cm, and height 2 cm?",
    options: ["A) 24 cm³", "B) 18 cm³", "C) 12 cm³", "D) 36 cm³"],
    correctAnswer: "A",
    hint: "Multiply length, width, and height to find the volume.",
    correctAnswerExplanation:
      "The volume of a rectangular prism is length × width × height. So, 4 cm × 3 cm × 2 cm = 24 cm³. The answer is A) 24 cm³.",
    incorrectAnswersExplanation: {
      B: "B) 18 cm³ is incorrect because it miscalculates the product.",
      C: "C) 12 cm³ is incorrect because it only accounts for two dimensions.",
      D: "D) 36 cm³ is incorrect because it overestimates the volume.",
    },
    difficulty: "Hard",
    tags: ["geometry", "volume"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic/cc-6th-volume/v/volume-of-a-rectangular-prism",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Algebra",
    grade: 6,
    questionType: "MC",
    question: "What is the value of x if 2x = 10?",
    options: ["A) 5", "B) 2", "C) 10", "D) 20"],
    correctAnswer: "A",
    hint: "Divide both sides of the equation by 2.",
    correctAnswerExplanation:
      "To solve 2x = 10, divide both sides by 2: 2x ÷ 2 = 10 ÷ 2, so x = 5. The answer is A) 5.",
    incorrectAnswersExplanation: {
      B: "B) 2 is incorrect because it uses the coefficient instead of solving.",
      C: "C) 10 is incorrect because it uses the right-hand side without dividing.",
      D: "D) 20 is incorrect because it multiplies instead of divides.",
    },
    difficulty: "Medium",
    tags: ["algebra", "equations"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-equations-and-inequalities/cc-6th-one-step-equations/v/solving-one-step-equations",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Algebra",
    grade: 6,
    questionType: "MC",
    question: "What is the value of 3x + 4 when x = 2?",
    options: ["A) 10", "B) 7", "C) 12", "D) 8"],
    correctAnswer: "A",
    hint: "Substitute x with 2 and evaluate the expression.",
    correctAnswerExplanation:
      "Substitute x = 2 into 3x + 4: 3(2) + 4 = 6 + 4 = 10. The answer is A) 10.",
    incorrectAnswersExplanation: {
      B: "B) 7 is incorrect because it miscalculates the multiplication or addition.",
      C: "C) 12 is incorrect because it overestimates the expression.",
      D: "D) 8 is incorrect because it underestimates the expression.",
    },
    difficulty: "Medium",
    tags: ["algebra", "expressions"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables/cc-6th-evaluating-expressions/v/evaluating-expressions-in-one-variable",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Algebra",
    grade: 6,
    questionType: "MC",
    question: "Solve for x: x + 7 = 12.",
    options: ["A) 5", "B) 7", "C) 19", "D) 12"],
    correctAnswer: "A",
    hint: "Subtract 7 from both sides of the equation.",
    correctAnswerExplanation:
      "To solve x + 7 = 12, subtract 7 from both sides: x + 7 - 7 = 12 - 7, so x = 5. The answer is A) 5.",
    incorrectAnswersExplanation: {
      B: "B) 7 is incorrect because it uses the number added instead of solving.",
      C: "C) 19 is incorrect because it adds instead of subtracts.",
      D: "D) 12 is incorrect because it uses the right-hand side without solving.",
    },
    difficulty: "Medium",
    tags: ["algebra", "equations"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-equations-and-inequalities/cc-6th-one-step-equations/v/solving-one-step-equations",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Algebra",
    grade: 6,
    questionType: "MC",
    question: "Which expression is equivalent to 4(x + 2)?",
    options: ["A) 4x + 8", "B) 4x + 2", "C) x + 8", "D) 4x + 4"],
    correctAnswer: "A",
    hint: "Distribute the 4 to both terms inside the parentheses.",
    correctAnswerExplanation:
      "To find an equivalent expression, distribute: 4(x + 2) = 4x + 4 × 2 = 4x + 8. The answer is A) 4x + 8.",
    incorrectAnswersExplanation: {
      B: "B) 4x + 2 is incorrect because it does not distribute the 4 to the 2.",
      C: "C) x + 8 is incorrect because it ignores the 4 entirely.",
      D: "D) 4x + 4 is incorrect because it miscalculates the distribution.",
    },
    difficulty: "Hard",
    tags: ["algebra", "distributive property"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-expressions-and-variables/cc-6th-distributive-property/v/distributive-property",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Algebra",
    grade: 6,
    questionType: "MC",
    question: "Solve for x: 3x - 5 = 4.",
    options: ["A) 3", "B) 5", "C) 1", "D) 9"],
    correctAnswer: "A",
    hint: "Add 5 to both sides, then divide by 3.",
    correctAnswerExplanation:
      "To solve 3x - 5 = 4, add 5 to both sides: 3x - 5 + 5 = 4 + 5, so 3x = 9. Divide by 3: 3x ÷ 3 = 9 ÷ 3, so x = 3. The answer is A) 3.",
    incorrectAnswersExplanation: {
      B: "B) 5 is incorrect because it miscalculates the division or addition.",
      C: "C) 1 is incorrect because it underestimates the solution.",
      D: "D) 9 is incorrect because it uses the sum before division.",
    },
    difficulty: "Hard",
    tags: ["algebra", "equations"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-equations-and-inequalities/cc-6th-one-step-equations/v/solving-one-step-equations",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Word Problems",
    grade: 6,
    questionType: "MC",
    question: "A store sells 3 pens for $6. How much would 9 pens cost?",
    options: ["A) $12", "B) $18", "C) $15", "D) $21"],
    correctAnswer: "B",
    hint: "Find the cost of one pen and multiply by 9.",
    correctAnswerExplanation:
      "The cost of 1 pen is $6 ÷ 3 = $2. For 9 pens, multiply: 9 × $2 = $18. The answer is B) $18.",
    incorrectAnswersExplanation: {
      A: "A) $12 is incorrect because it underestimates the cost.",
      C: "C) $15 is incorrect because it miscalculates the total.",
      D: "D) $21 is incorrect because it overestimates the cost.",
    },
    difficulty: "Medium",
    tags: ["word problems", "ratios"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-rates/v/rates-and-unit-rates",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Word Problems",
    grade: 6,
    questionType: "MC",
    question:
      "A car travels 120 miles in 2 hours. How far will it travel in 5 hours at the same speed?",
    options: ["A) 300 miles", "B) 240 miles", "C) 360 miles", "D) 200 miles"],
    correctAnswer: "A",
    hint: "Find the speed and multiply by the new time.",
    correctAnswerExplanation:
      "The speed is 120 miles ÷ 2 hours = 60 miles per hour. For 5 hours, multiply: 60 × 5 = 300 miles. The answer is A) 300 miles.",
    incorrectAnswersExplanation: {
      B: "B) 240 miles is incorrect because it underestimates the distance.",
      C: "C) 360 miles is incorrect because it overestimates the distance.",
      D: "D) 200 miles is incorrect because it miscalculates the speed.",
    },
    difficulty: "Hard",
    tags: ["word problems", "rates"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-ratios-prop-topic/cc-6th-rates/v/introduction-to-rates",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Word Problems",
    grade: 6,
    questionType: "MC",
    question:
      "A pizza is cut into 8 equal slices, and 3 slices are eaten. What fraction of the pizza is left?",
    options: ["A) 3/8", "B) 5/8", "C) 1/2", "D) 2/8"],
    correctAnswer: "B",
    hint: "Subtract the fraction eaten from the whole pizza.",
    correctAnswerExplanation:
      "The whole pizza is 8/8. If 3/8 is eaten, subtract: 8/8 - 3/8 = 5/8. The answer is B) 5/8.",
    incorrectAnswersExplanation: {
      A: "A) 3/8 is incorrect because it represents the amount eaten, not left.",
      C: "C) 1/2 is incorrect because it assumes 4/8 was eaten.",
      D: "D) 2/8 is incorrect because it underestimates the amount left.",
    },
    difficulty: "Medium",
    tags: ["word problems", "fractions"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-adding-fractions/v/subtracting-fractions",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Word Problems",
    grade: 6,
    questionType: "MC",
    question:
      "A book costs $15, and a notebook costs $5. If you buy 2 books and 3 notebooks, how much do you spend?",
    options: ["A) $45", "B) $35", "C) $40", "D) $50"],
    correctAnswer: "C",
    hint: "Multiply the cost of each item by the quantity and add the totals.",
    correctAnswerExplanation:
      "For 2 books: 2 × $15 = $30. For 3 notebooks: 3 × $5 = $15. Add: $30 + $15 = $40. The answer is C) $40.",
    incorrectAnswersExplanation: {
      A: "A) $45 is incorrect because it overestimates the notebook cost.",
      B: "B) $35 is incorrect because it underestimates the total.",
      D: "D) $50 is incorrect because it overestimates the total.",
    },
    difficulty: "Hard",
    tags: ["word problems", "arithmetic"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-multiplying-decimals/v/multiplying-whole-numbers",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Word Problems",
    grade: 6,
    questionType: "MC",
    question: "A garden is 12 feet long and 6 feet wide. What is its area?",
    options: ["A) 72 ft²", "B) 36 ft²", "C) 18 ft²", "D) 60 ft²"],
    correctAnswer: "A",
    hint: "Multiply the length by the width to find the area.",
    correctAnswerExplanation:
      "The area of a rectangle is length × width. So, 12 ft × 6 ft = 72 ft². The answer is A) 72 ft².",
    incorrectAnswersExplanation: {
      B: "B) 36 ft² is incorrect because it miscalculates the product.",
      C: "C) 18 ft² is incorrect because it adds instead of multiplies.",
      D: "D) 60 ft² is incorrect because it underestimates the area.",
    },
    difficulty: "Medium",
    tags: ["word problems", "geometry"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-geometry-topic/cc-6th-area/v/rectangle-area-as-product-of-dimensions",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Number Sense",
    grade: 6,
    questionType: "MC",
    question: "What is the greatest common factor of 12 and 18?",
    options: ["A) 3", "B) 6", "C) 9", "D) 12"],
    correctAnswer: "B",
    hint: "List the factors of both numbers and find the largest one they share.",
    correctAnswerExplanation:
      "Factors of 12: 1, 2, 3, 4, 6, 12. Factors of 18: 1, 2, 3, 6, 9, 18. The greatest common factor is 6. The answer is B) 6.",
    incorrectAnswersExplanation: {
      A: "A) 3 is incorrect because 6 is a larger common factor.",
      C: "C) 9 is incorrect because 9 is not a factor of 12.",
      D: "D) 12 is incorrect because 12 is not a factor of 18.",
    },
    difficulty: "Medium",
    tags: ["number sense", "factors"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-factors-and-multiples/cc-6th-gcf/v/greatest-common-factor",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Number Sense",
    grade: 6,
    questionType: "MC",
    question: "What is the least common multiple of 4 and 6?",
    options: ["A) 12", "B) 24", "C) 8", "D) 16"],
    correctAnswer: "A",
    hint: "Find the smallest number that both 4 and 6 divide into evenly.",
    correctAnswerExplanation:
      "List multiples of 4: 4, 8, 12, 16, 20, 24. List multiples of 6: 6, 12, 18, 24. The least common multiple is 12. The answer is A) 12.",
    incorrectAnswersExplanation: {
      B: "B) 24 is incorrect because 12 is a smaller common multiple.",
      C: "C) 8 is incorrect because 6 does not divide into 8 evenly.",
      D: "D) 16 is incorrect because 6 does not divide into 16 evenly.",
    },
    difficulty: "Medium",
    tags: ["number sense", "multiples"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-factors-and-multiples/cc-6th-lcm/v/least-common-multiple",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Number Sense",
    grade: 6,
    questionType: "MC",
    question: "Which number is a prime number?",
    options: ["A) 15", "B) 17", "C) 21", "D) 25"],
    correctAnswer: "B",
    hint: "A prime number has only two factors: 1 and itself.",
    correctAnswerExplanation:
      "A prime number has only two factors. Check: 15 (1, 3, 5, 15), 17 (1, 17), 21 (1, 3, 7, 21), 25 (1, 5, 25). Only 17 is prime. The answer is B) 17.",
    incorrectAnswersExplanation: {
      A: "A) 15 is incorrect because it has factors 3 and 5 besides 1 and 15.",
      C: "C) 21 is incorrect because it has factors 3 and 7 besides 1 and 21.",
      D: "D) 25 is incorrect because it has factor 5 besides 1 and 25.",
    },
    difficulty: "Medium",
    tags: ["number sense", "prime numbers"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-factors-and-multiples/cc-6th-prime-factorization/v/prime-numbers",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Number Sense",
    grade: 6,
    questionType: "MC",
    question: "What is 2³ × 3²?",
    options: ["A) 36", "B) 72", "C) 18", "D) 24"],
    correctAnswer: "B",
    hint: "Calculate each exponent and then multiply the results.",
    correctAnswerExplanation:
      "First, calculate 2³ = 2 × 2 × 2 = 8 and 3² = 3 × 3 = 9. Then multiply: 8 × 9 = 72. The answer is B) 72.",
    incorrectAnswersExplanation: {
      A: "A) 36 is incorrect because it underestimates the product.",
      C: "C) 18 is incorrect because it miscalculates the exponents or product.",
      D: "D) 24 is incorrect because it underestimates the product.",
    },
    difficulty: "Hard",
    tags: ["number sense", "exponents"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-arithmetic-operations/cc-6th-exponents/v/introduction-to-exponents",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Number Sense",
    grade: 6,
    questionType: "MC",
    question: "Which number is divisible by both 3 and 4?",
    options: ["A) 15", "B) 24", "C) 27", "D) 32"],
    correctAnswer: "B",
    hint: "Check if the number is divisible by both 3 and 4 using divisibility rules.",
    correctAnswerExplanation:
      "A number divisible by 3 has digits summing to a multiple of 3, and by 4 if the last two digits form a multiple of 4. For 24: 2 + 4 = 6 (divisible by 3), and 24 is divisible by 4 (24 ÷ 4 = 6). The answer is B) 24.",
    incorrectAnswersExplanation: {
      A: "A) 15 is incorrect because it is not divisible by 4.",
      C: "C) 27 is incorrect because it is not divisible by 4.",
      D: "D) 32 is incorrect because it is not divisible by 3 (3 + 2 = 5).",
    },
    difficulty: "Hard",
    tags: ["number sense", "divisibility"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-factors-and-multiples/cc-6th-divisibility/v/divisibility-rules",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Data and Statistics",
    grade: 6,
    questionType: "MC",
    question: "What is the mean of the numbers 4, 8, 12, and 16?",
    options: ["A) 10", "B) 12", "C) 8", "D) 14"],
    correctAnswer: "A",
    hint: "Add the numbers and divide by the count.",
    correctAnswerExplanation:
      "To find the mean, add the numbers: 4 + 8 + 12 + 16 = 40. Divide by the count (4): 40 ÷ 4 = 10. The answer is A) 10.",
    incorrectAnswersExplanation: {
      B: "B) 12 is incorrect because it overestimates the mean.",
      C: "C) 8 is incorrect because it underestimates the mean.",
      D: "D) 14 is incorrect because it miscalculates the sum or division.",
    },
    difficulty: "Medium",
    tags: ["data and statistics", "mean"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics/cc-6th-mean-median-mode/v/mean-median-and-mode",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Data and Statistics",
    grade: 6,
    questionType: "MC",
    question: "What is the median of the numbers 3, 7, 1, 9, 5?",
    options: ["A) 5", "B) 7", "C) 3", "D) 9"],
    correctAnswer: "A",
    hint: "Order the numbers and find the middle one.",
    correctAnswerExplanation:
      "Order the numbers: 1, 3, 5, 7, 9. The middle number (third in the list) is 5. The answer is A) 5.",
    incorrectAnswersExplanation: {
      B: "B) 7 is incorrect because it is not the middle number.",
      C: "C) 3 is incorrect because it is not the middle number.",
      D: "D) 9 is incorrect because it is not the middle number.",
    },
    difficulty: "Medium",
    tags: ["data and statistics", "median"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics/cc-6th-mean-median-mode/v/median",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Data and Statistics",
    grade: 6,
    questionType: "MC",
    question: "What is the mode of the numbers 2, 4, 4, 6, 8?",
    options: ["A) 2", "B) 4", "C) 6", "D) 8"],
    correctAnswer: "B",
    hint: "Find the number that appears most often.",
    correctAnswerExplanation:
      "The numbers are 2, 4, 4, 6, 8. The number 4 appears twice, more than any other. The answer is B) 4.",
    incorrectAnswersExplanation: {
      A: "A) 2 is incorrect because it appears only once.",
      C: "C) 6 is incorrect because it appears only once.",
      D: "D) 8 is incorrect because it appears only once.",
    },
    difficulty: "Medium",
    tags: ["data and statistics", "mode"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics/cc-6th-mean-median-mode/v/mode",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Data and Statistics",
    grade: 6,
    questionType: "MC",
    question: "What is the range of the numbers 10, 5, 8, 12, 3?",
    options: ["A) 9", "B) 7", "C) 12", "D) 5"],
    correctAnswer: "A",
    hint: "Subtract the smallest number from the largest.",
    correctAnswerExplanation:
      "The range is the largest number minus the smallest. The numbers are 10, 5, 8, 12, 3. Largest is 12, smallest is 3: 12 - 3 = 9. The answer is A) 9.",
    incorrectAnswersExplanation: {
      B: "B) 7 is incorrect because it underestimates the range.",
      C: "C) 12 is incorrect because it uses the largest number alone.",
      D: "D) 5 is incorrect because it underestimates the range.",
    },
    difficulty: "Medium",
    tags: ["data and statistics", "range"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics/cc-6th-statistical-questions/v/range-of-data",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Data and Statistics",
    grade: 6,
    questionType: "MC",
    question:
      "A class has test scores of 80, 85, 90, 85, and 95. What is the mean score?",
    options: ["A) 85", "B) 87", "C) 90", "D) 88"],
    correctAnswer: "B",
    hint: "Add the scores and divide by the number of scores.",
    correctAnswerExplanation:
      "Add the scores: 80 + 85 + 90 + 85 + 95 = 435. Divide by 5: 435 ÷ 5 = 87. The answer is B) 87.",
    incorrectAnswersExplanation: {
      A: "A) 85 is incorrect because it underestimates the mean.",
      C: "C) 90 is incorrect because it overestimates the mean.",
      D: "D) 88 is incorrect because it miscalculates the sum or division.",
    },
    difficulty: "Hard",
    tags: ["data and statistics", "mean"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-data-statistics/cc-6th-mean-median-mode/v/mean-median-and-mode",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Integers",
    grade: 6,
    questionType: "MC",
    question: "What is -3 + 5?",
    options: ["A) 2", "B) -2", "C) 8", "D) -8"],
    correctAnswer: "A",
    hint: "Think of moving right on a number line for positive numbers.",
    correctAnswerExplanation:
      "To find -3 + 5, start at -3 and move 5 units right on the number line: -3 + 5 = 2. The answer is A) 2.",
    incorrectAnswersExplanation: {
      B: "B) -2 is incorrect because it subtracts instead of adds.",
      C: "C) 8 is incorrect because it ignores the negative sign.",
      D: "D) -8 is incorrect because it misinterprets both signs.",
    },
    difficulty: "Medium",
    tags: ["integers", "addition"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-numbers-topic/cc-6th-adding-negative-numbers/v/adding-integers",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Integers",
    grade: 6,
    questionType: "MC",
    question: "What is -4 - 2?",
    options: ["A) -6", "B) 6", "C) -2", "D) 2"],
    correctAnswer: "A",
    hint: "Subtracting a positive number moves left on the number line.",
    correctAnswerExplanation:
      "To find -4 - 2, start at -4 and move 2 units left: -4 - 2 = -6. The answer is A) -6.",
    incorrectAnswersExplanation: {
      B: "B) 6 is incorrect because it ignores the negative signs.",
      C: "C) -2 is incorrect because it underestimates the subtraction.",
      D: "D) 2 is incorrect because it adds instead of subtracts.",
    },
    difficulty: "Medium",
    tags: ["integers", "subtraction"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-numbers-topic/cc-6th-adding-negative-numbers/v/subtracting-integers",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Integers",
    grade: 6,
    questionType: "MC",
    question: "What is -2 × 3?",
    options: ["A) 6", "B) -6", "C) 5", "D) -5"],
    correctAnswer: "B",
    hint: "A negative times a positive gives a negative result.",
    correctAnswerExplanation:
      "To multiply -2 × 3, multiply the numbers (2 × 3 = 6) and apply the sign: a negative times a positive is negative, so -6. The answer is B) -6.",
    incorrectAnswersExplanation: {
      A: "A) 6 is incorrect because it ignores the negative sign.",
      C: "C) 5 is incorrect because it miscalculates the product.",
      D: "D) -5 is incorrect because it miscalculates the product.",
    },
    difficulty: "Medium",
    tags: ["integers", "multiplication"],
    timeEstimate: 60,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-numbers-topic/cc-6th-mult-div-integers/v/multiplying-integers",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
  {
    subject: "Mathematics",
    topic: "Integers",
    grade: 6,
    questionType: "MC",
    question: "What is -8 ÷ -2?",
    options: ["A) 4", "B) -4", "C) 6", "D) -6"],
    correctAnswer: "A",
    hint: "A negative divided by a negative gives a positive result.",
    correctAnswerExplanation:
      "To divide -8 ÷ -2, divide the numbers (8 ÷ 2 = 4) and apply the sign: a negative divided by a negative is positive, so 4. The answer is A) 4.",
    incorrectAnswersExplanation: {
      B: "B) -4 is incorrect because it assumes a negative result.",
      C: "C) 6 is incorrect because it miscalculates the quotient.",
      D: "D) -6 is incorrect because it miscalculates the quotient and sign.",
    },
    difficulty: "Hard",
    tags: ["integers", "division"],
    timeEstimate: 90,
    webLink:
      "https://www.khanacademy.org/math/cc-sixth-grade-math/cc-6th-negative-numbers-topic/cc-6th-mult-div-integers/v/dividing-integers",
    source: "Grok",
    lastUpdated: "2025-04-24",
  },
];
export default mathematicsGrade6Questions;
