// lib/questions/reading-grade6.ts
const readingGrade6Questions = [
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "The new dinosaur exhibit at the Chicago Museum of Natural History was packed with excited visitors. Tommy stood in awe before the massive T-Rex skeleton. He imagined what it would be like if dinosaurs still roamed the Earth today. The thought both thrilled and frightened him.",
    question: "How did Tommy feel about dinosaurs based on the passage?",
    options: [
      "A) He was bored by them",
      "B) He was both excited and scared about them",
      "C) He hated them",
      "D) He only felt fear toward them",
    ],
    correctAnswer: "B",
    hint: "Look for words that describe Tommy's emotions in the passage.",
    correctAnswerExplanation:
      "The passage states that Tommy 'imagined what it would be like if dinosaurs still roamed the Earth today. The thought both thrilled and frightened him.' This shows he had mixed feelings of excitement and fear.",
    incorrectAnswersExplanation: {
      A: "The passage describes Tommy as standing 'in awe' and being 'thrilled,' which shows he was interested, not bored.",
      C: "Tommy doesn't hate dinosaurs; the passage shows he was fascinated enough to imagine them in the present day.",
      D: "Tommy wasn't only frightened; the passage specifically mentions he was both 'thrilled and frightened.'",
    },
    difficulty: "Medium",
    tags: ["comprehension", "emotions", "inference"],
    timeEstimate: 60,
    webLink: "https://www.readworks.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "Max's wolf pup, Luna, loved to listen to bedtime stories. Every night, Max would read about brave explorers and magical adventures. Luna would curl up next to him, her ears perked up attentively. Sometimes, she would even howl softly when the story got exciting.",
    question: "What can you infer about Luna from the passage?",
    options: [
      "A) Luna enjoys when Max reads to her",
      "B) Luna can read the stories herself",
      "C) Luna dislikes bedtime stories",
      "D) Luna falls asleep before the stories end",
    ],
    correctAnswer: "A",
    hint: "Think about Luna's behavior when Max reads stories.",
    correctAnswerExplanation:
      "The passage states that Luna 'loved to listen to bedtime stories,' 'would curl up next to him, her ears perked up attentively,' and 'would even howl softly when the story got exciting.' These behaviors show she enjoys the stories.",
    incorrectAnswersExplanation: {
      B: "There's no evidence that Luna can read; the passage only mentions that she listens to stories Max reads.",
      C: "The passage explicitly states that Luna 'loved to listen to bedtime stories,' so she doesn't dislike them.",
      D: "The passage mentions Luna would 'howl softly when the story got exciting,' suggesting she stays awake during the stories.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "inference", "character analysis"],
    timeEstimate: 60,
    webLink: "https://www.commonlit.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "Sarah's summer reading project was to create a miniature scene from her favorite book. She chose 'The Secret Garden' and spent weeks building a tiny garden with real plants and a small wooden door. Her teacher, Ms. Johnson, was impressed with Sarah's attention to detail and awarded her the highest grade in the class.",
    question: "Why did Sarah receive the highest grade in the class?",
    options: [
      "A) Because she chose 'The Secret Garden' as her book",
      "B) Because she spent more time than others on her project",
      "C) Because she used real plants in her project",
      "D) Because of her careful attention to detail",
    ],
    correctAnswer: "D",
    hint: "Look for what specifically impressed Ms. Johnson.",
    correctAnswerExplanation:
      "The passage states that 'Ms. Johnson was impressed with Sarah's attention to detail and awarded her the highest grade in the class.' This directly links Sarah's attention to detail with receiving the highest grade.",
    incorrectAnswersExplanation: {
      A: "The passage doesn't suggest that Sarah's book choice influenced her grade; many books could have been chosen for the project.",
      B: "Although the passage mentions Sarah 'spent weeks' on her project, it doesn't say this is why she received the highest grade.",
      C: "While Sarah used real plants, the passage doesn't indicate this specific element earned her the highest grade.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "cause and effect", "reading"],
    timeEstimate: 60,
    webLink: "https://www.readingrockets.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "Every Saturday, Carlos walked his golden retriever, Buddy, to the local library. The librarian, Mrs. Lee, always greeted them with a smile and a dog treat for Buddy. Carlos would browse for new adventure books while Buddy sat patiently by his side. This weekly ritual was Carlos's favorite part of the weekend.",
    question: "What happens every Saturday according to the passage?",
    options: [
      "A) Carlos reads to Buddy at home",
      "B) Carlos and Buddy visit the local library",
      "C) Mrs. Lee visits Carlos and Buddy's house",
      "D) Carlos takes Buddy to a dog park",
    ],
    correctAnswer: "B",
    hint: "The first sentence tells you what Carlos did every Saturday.",
    correctAnswerExplanation:
      "The passage starts with 'Every Saturday, Carlos walked his golden retriever, Buddy, to the local library.' This clearly states that Carlos and Buddy's Saturday activity was visiting the library together.",
    incorrectAnswersExplanation: {
      A: "The passage doesn't mention Carlos reading to Buddy at home; it only describes their library visits.",
      C: "According to the passage, Carlos and Buddy go to the library where Mrs. Lee works; she doesn't visit their house.",
      D: "The passage specifically mentions they go to the library, not a dog park.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "literal meaning", "sequence"],
    timeEstimate: 60,
    webLink: "https://www.teacherspayteachers.com/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "The ancient dinosaur fossils lay buried beneath the red Arizona desert. Dr. Martinez and her team worked carefully with small brushes to reveal the bones. After three weeks of patient excavation, they uncovered what appeared to be a new species of raptor. Dr. Martinez could hardly contain her excitement at the discovery.",
    question: "Why was Dr. Martinez excited?",
    options: [
      "A) Because she found gold in the desert",
      "B) Because the excavation was finally over",
      "C) Because she discovered what seemed to be a new dinosaur species",
      "D) Because she was going home after three weeks",
    ],
    correctAnswer: "C",
    hint: "Look for what special discovery was made after three weeks of work.",
    correctAnswerExplanation:
      "The passage states that 'they uncovered what appeared to be a new species of raptor' and 'Dr. Martinez could hardly contain her excitement at the discovery.' This shows she was excited specifically about finding what might be a previously unknown dinosaur.",
    incorrectAnswersExplanation: {
      A: "The passage doesn't mention finding gold; they were excavating dinosaur fossils.",
      B: "While the excavation lasted three weeks, the passage doesn't indicate she was excited merely because it was over.",
      D: "The passage doesn't mention Dr. Martinez going home or being excited about that.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "cause and effect", "science"],
    timeEstimate: 60,
    webLink: "https://www.readworks.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "Jessie had never seen snow before moving to Colorado. On the first winter morning, she woke to a world transformed. The trees wore white coats, and the ground sparkled like diamonds. Jessie rushed outside without her gloves, eager to touch the magical substance. She quickly learned that snow was much colder than she had imagined!",
    question: "What lesson did Jessie learn in this passage?",
    options: [
      "A) Snow is dangerous and should be avoided",
      "B) Colorado winters are beautiful but harsh",
      "C) Snow is colder than she expected",
      "D) Always wear proper winter clothing",
    ],
    correctAnswer: "C",
    hint: "Look at what happened when Jessie touched the snow.",
    correctAnswerExplanation:
      "The passage directly states that 'She quickly learned that snow was much colder than she had imagined!' This shows that Jessie learned snow was colder than she expected when she touched it without gloves.",
    incorrectAnswersExplanation: {
      A: "The passage doesn't suggest snow is dangerous or should be avoided; Jessie was actually eager to touch it.",
      B: "While the passage describes the beauty of snow, it doesn't make a general statement about Colorado winters being harsh.",
      D: "While this might be implied, the passage doesn't explicitly state this as the lesson Jessie learned.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "inference", "lesson"],
    timeEstimate: 60,
    webLink: "https://www.k12reader.com/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "Marcus loved playing Minecraft after school. He would build elaborate castles with hidden rooms and secret passages. His latest creation included a library with bookshelves that opened to reveal a laboratory. Marcus spent hours designing every detail, making sure it was perfect before showing it to his friends online.",
    question: "What does the passage suggest about Marcus?",
    options: [
      "A) He prefers playing outside rather than video games",
      "B) He is creative and detail-oriented",
      "C) He doesn't have many friends",
      "D) He dislikes reading books",
    ],
    correctAnswer: "B",
    hint: "Consider how Marcus approaches his building projects in Minecraft.",
    correctAnswerExplanation:
      "The passage describes how Marcus builds 'elaborate castles with hidden rooms and secret passages' and 'spent hours designing every detail.' This shows he is both creative (making complex designs) and detail-oriented (paying attention to every aspect of his creation).",
    incorrectAnswersExplanation: {
      A: "The passage only mentions Marcus playing Minecraft; there's no comparison to outdoor activities.",
      C: "The passage mentions Marcus showing his creation to 'friends online,' suggesting he does have friends.",
      D: "The passage mentions Marcus building a library in his Minecraft creation, which doesn't suggest he dislikes books.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "character traits", "inference"],
    timeEstimate: 60,
    webLink: "https://www.commonlit.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "Miguel's dog, Rex, had a strange habit. Whenever Miguel would read aloud, Rex would sit and tilt his head as if listening intently. One day, Miguel was reading a story about wolves in the wild. When he reached a part about wolf howls, Rex threw back his head and let out a perfect howl! Miguel couldn't stop laughing at his dog's perfect timing.",
    question: "What made Miguel laugh in this passage?",
    options: [
      "A) The funny story about wolves",
      "B) Rex's habit of tilting his head",
      "C) Rex howling at the same time Miguel read about wolf howls",
      "D) Rex trying to run away from the book",
    ],
    correctAnswer: "C",
    hint: "Think about what Rex did that had 'perfect timing' according to the passage.",
    correctAnswerExplanation:
      "The passage states that 'When he reached a part about wolf howls, Rex threw back his head and let out a perfect howl!' and then 'Miguel couldn't stop laughing at his dog's perfect timing.' This shows Miguel laughed because Rex howled right when Miguel was reading about wolves howling.",
    incorrectAnswersExplanation: {
      A: "The passage doesn't suggest the wolf story itself was funny; Miguel laughed at Rex's reaction to it.",
      B: "While the passage mentions Rex would tilt his head when Miguel read, it specifically states Miguel laughed at the howling incident.",
      D: "The passage doesn't mention Rex trying to run away from the book.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "cause and effect", "sequence"],
    timeEstimate: 60,
    webLink: "https://www.readworks.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "The old oak tree in the schoolyard had been there for over a hundred years. Its massive branches provided shade for generations of students. Under its canopy, children read books, ate lunch, and told stories. Some said the tree had magical powers—that it remembered every word of every book read beneath its branches.",
    question: "What is the main idea of this passage?",
    options: [
      "A) Trees have magical powers and can remember things",
      "B) The old oak tree is important to the school and its students",
      "C) Reading under trees is better than reading inside",
      "D) The schoolyard needs more trees for shade",
    ],
    correctAnswer: "B",
    hint: "Think about what the entire passage is describing about the tree.",
    correctAnswerExplanation:
      "The passage focuses on the significance of the old oak tree in the schoolyard—how long it's been there, how it serves students, and the special place it holds in school tradition. Every detail in the passage contributes to showing the tree's importance to the school community.",
    incorrectAnswersExplanation: {
      A: "The passage only mentions this as something 'some said' about the tree, not as the main point of the passage.",
      C: "While the passage mentions reading under the tree, it doesn't compare this to reading inside or suggest it's better.",
      D: "The passage doesn't suggest the schoolyard needs more trees; it focuses on the significance of the one existing oak tree.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "main idea", "inference"],
    timeEstimate: 60,
    webLink: "https://www.readingrockets.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "The National Dinosaur Museum in Denver was hosting a special writing contest. Students were asked to write stories imagining what would happen if dinosaurs returned to modern America. Twelve-year-old Zoe spent weeks researching different dinosaur species for her story about a friendly Triceratops living in New York City. Her hard work paid off when she won first place.",
    question: "What was Zoe's story about?",
    options: [
      "A) Dinosaurs fighting in ancient times",
      "B) A Triceratops living in New York City",
      "C) How dinosaurs became extinct",
      "D) A museum exhibit coming to life",
    ],
    correctAnswer: "B",
    hint: "The passage directly states what Zoe wrote about for her contest entry.",
    correctAnswerExplanation:
      "The passage specifically states that Zoe wrote 'her story about a friendly Triceratops living in New York City.' This directly tells us the subject of her story that won the contest.",
    incorrectAnswersExplanation: {
      A: "The passage doesn't mention Zoe writing about dinosaurs fighting; her story was about a Triceratops in modern New York.",
      C: "The passage doesn't mention Zoe writing about dinosaur extinction; her story was about dinosaurs returning to modern times.",
      D: "While this might fit the contest theme, the passage specifically states Zoe wrote about a Triceratops in New York City.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "literal meaning", "details"],
    timeEstimate: 60,
    webLink: "https://www.commonlit.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "The winter storm had covered Boston in three feet of snow. Schools were closed, and Maya was thrilled to have an unexpected day off. She bundled up in her warmest clothes and headed outside with her border collie, Scout. Together they explored the transformed neighborhood, where familiar landmarks now looked like strange snow sculptures.",
    question: "How did Maya feel about the snow day?",
    options: ["A) Disappointed", "B) Afraid", "C) Excited", "D) Worried"],
    correctAnswer: "C",
    hint: "Look for words that describe Maya's emotional reaction to school being closed.",
    correctAnswerExplanation:
      "The passage states that 'Maya was thrilled to have an unexpected day off' and describes her actively going outside to explore. Being 'thrilled' means she was very excited about the snow day situation.",
    incorrectAnswersExplanation: {
      A: "The passage says Maya was 'thrilled,' which is the opposite of disappointed.",
      B: "There's no indication Maya was afraid; she willingly went outside to explore the snow.",
      D: "The passage doesn't suggest Maya was worried; she embraced the snow day by going outside with her dog.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "emotions", "inference"],
    timeEstimate: 60,
    webLink: "https://www.k12reader.com/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "Jake had been tending his small garden in Stardew Valley for months. He carefully watered each tomato plant and watched as the fruits slowly grew from tiny green balls to plump red treasures. One morning, Jake discovered something had eaten half his crop overnight. Examining the garden closely, he found tiny paw prints that could only belong to a family of raccoons.",
    question: "What happened to Jake's tomatoes?",
    options: [
      "A) They grew too slowly",
      "B) They were stolen by neighbors",
      "C) They were eaten by raccoons",
      "D) They died from lack of water",
    ],
    correctAnswer: "C",
    hint: "Look at what evidence Jake found in his garden.",
    correctAnswerExplanation:
      "The passage states that 'something had eaten half his crop overnight' and then Jake found 'tiny paw prints that could only belong to a family of raccoons.' This evidence leads to the conclusion that raccoons ate his tomatoes.",
    incorrectAnswersExplanation: {
      A: "The passage actually states that Jake 'watched as the fruits slowly grew,' but slowness wasn't the problem with his crop.",
      B: "There's no mention of neighbors in the passage; the evidence points to raccoons.",
      D: "The passage specifically mentions that Jake 'carefully watered each tomato plant,' so lack of water wasn't the issue.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "cause and effect", "inference"],
    timeEstimate: 60,
    webLink: "https://www.readworks.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "The school's annual Book Character Day was coming up. Students were encouraged to dress as their favorite literary characters. Emma couldn't decide between Katniss Everdeen from The Hunger Games or Hermione Granger from Harry Potter. She finally chose Katniss and spent a week creating a perfect mockingjay pin from clay and gold paint.",
    question: "What was Emma preparing for?",
    options: [
      "A) A Halloween party",
      "B) Book Character Day at school",
      "C) A movie premiere",
      "D) A cosplay competition",
    ],
    correctAnswer: "B",
    hint: "Look at the first sentence of the passage.",
    correctAnswerExplanation:
      "The very first sentence of the passage states 'The school's annual Book Character Day was coming up.' This directly tells us what event Emma was preparing for by creating her Katniss costume.",
    incorrectAnswersExplanation: {
      A: "The passage specifically mentions Book Character Day, not Halloween.",
      C: "There's no mention of a movie premiere in the passage.",
      D: "While cosplay involves dressing as characters, the passage specifically mentions this was for Book Character Day at school.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "literal meaning", "details"],
    timeEstimate: 60,
    webLink: "https://www.commonlit.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "Lucas found an unusual book at the back of the library shelf. It had no title on its worn leather cover, only strange symbols that resembled dinosaur footprints. When he opened it, the pages were blank. Disappointed, Lucas was about to return it when words began to appear on the first page: 'Only the true reader can see our story.'",
    question: "What was unusual about the book Lucas found?",
    options: [
      "A) It was written in a foreign language",
      "B) It had dinosaur pictures inside",
      "C) It had strange symbols on the cover and blank pages that later revealed text",
      "D) It was too heavy to lift",
    ],
    correctAnswer: "C",
    hint: "Think about the physical description of the book and what happened when Lucas opened it.",
    correctAnswerExplanation:
      "The passage describes the book as having 'no title on its worn leather cover, only strange symbols that resembled dinosaur footprints' and that 'the pages were blank' until 'words began to appear.' These features make the book unusual.",
    incorrectAnswersExplanation: {
      A: "The passage doesn't mention a foreign language; it mentions symbols that looked like dinosaur footprints.",
      B: "The passage mentions symbols resembling dinosaur footprints on the cover, not pictures inside.",
      D: "The passage doesn't mention anything about the book's weight.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "details", "inference"],
    timeEstimate: 60,
    webLink: "https://www.readingrockets.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "The writing contest deadline was tomorrow, and Sophia hadn't even started her story. She stared at the blank page, feeling panic rise. Just then, her German shepherd, Apollo, dropped his favorite toy in her lap. Sophia smiled as an idea struck her—she would write about a brave dog who saves his neighborhood during a blackout. Her fingers flew across the keyboard as the story took shape.",
    question: "What was Sophia's problem at the beginning of the passage?",
    options: [
      "A) Her dog was bothering her",
      "B) She couldn't find her keyboard",
      "C) She didn't have a story idea and the deadline was approaching",
      "D) She didn't want to enter the writing contest",
    ],
    correctAnswer: "C",
    hint: "Look at what made Sophia feel panic in the first two sentences.",
    correctAnswerExplanation:
      "The passage states that 'The writing contest deadline was tomorrow, and Sophia hadn't even started her story. She stared at the blank page, feeling panic rise.' This shows her problem was not having a story idea with the deadline approaching soon.",
    incorrectAnswersExplanation: {
      A: "Apollo bringing his toy actually helped inspire Sophia rather than bothering her.",
      B: "The passage doesn't mention any issue with finding her keyboard; it mentions her 'fingers flew across the keyboard' later.",
      D: "The passage shows Sophia actively trying to write for the contest, not avoiding it.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "problem and solution", "sequence"],
    timeEstimate: 60,
    webLink: "https://www.k12reader.com/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "Wolf Creek Middle School's robotics team was preparing for the state championship. For weeks, they had been programming their robot to navigate an obstacle course and collect colored blocks. On the day of the competition, their robot suddenly stopped working. With only thirty minutes until their turn, Jamal discovered a loose wire and quickly fixed the problem.",
    question: "What was the climax or most exciting part of this passage?",
    options: [
      "A) The team preparing for the championship",
      "B) Programming the robot to collect blocks",
      "C) The robot breaking down before the competition",
      "D) Jamal finding and fixing the loose wire",
    ],
    correctAnswer: "D",
    hint: "The climax is usually the moment of highest tension or turning point in a story.",
    correctAnswerExplanation:
      "The climax is Jamal finding and fixing the loose wire because this is the moment of resolution after the main conflict (the robot breaking down). With 'only thirty minutes until their turn,' this moment represents the highest point of tension and its resolution.",
    incorrectAnswersExplanation: {
      A: "This is background information that sets up the story, not the climax.",
      B: "This is also part of the setup or exposition of the story, not the climactic moment.",
      C: "This is the introduction of the conflict or problem, but not the climax itself.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "story structure", "climax"],
    timeEstimate: 60,
    webLink: "https://www.readworks.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "The dinosaur museum was unlike any place Ryan had ever visited. In the main hall stood a massive Brachiosaurus skeleton reaching toward the ceiling. In another room, lifelike models of Velociraptors seemed ready to pounce. Ryan's favorite exhibit, however, was the interactive fossil dig where visitors could uncover replica bones buried in sand.",
    question: "Which part of the museum did Ryan like best?",
    options: [
      "A) The Brachiosaurus skeleton",
      "B) The Velociraptor models",
      "C) The interactive fossil dig",
      "D) The museum gift shop",
    ],
    correctAnswer: "C",
    hint: "The passage specifically mentions Ryan's favorite exhibit.",
    correctAnswerExplanation:
      "The passage directly states that 'Ryan's favorite exhibit, however, was the interactive fossil dig where visitors could uncover replica bones buried in sand.' This clearly identifies which part of the museum Ryan preferred over the others.",
    incorrectAnswersExplanation: {
      A: "While the passage mentions the impressive Brachiosaurus skeleton, it doesn't say this was Ryan's favorite.",
      B: "The passage describes the lifelike Velociraptor models but doesn't indicate Ryan preferred this exhibit.",
      D: "The passage doesn't mention a museum gift shop at all.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "literal meaning", "details"],
    timeEstimate: 60,
    webLink: "https://www.commonlit.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "Ms. Rodriguez assigned a creative writing project where students had to write from the perspective of an animal. Tyler chose to write from the viewpoint of a wolf living in Yellowstone National Park. Through his research, Tyler learned about wolf pack behavior, hunting strategies, and their important role in the ecosystem. His story about a young wolf's first hunt earned him an A+ and was displayed in the school library.",
    question: "What animal's perspective did Tyler write from?",
    options: ["A) A dinosaur", "B) A wolf", "C) A dog", "D) An eagle"],
    correctAnswer: "B",
    hint: "The passage directly states which animal Tyler chose for his project.",
    correctAnswerExplanation:
      "The passage clearly states that 'Tyler chose to write from the viewpoint of a wolf living in Yellowstone National Park.' This directly identifies the animal perspective he selected for his creative writing project.",
    incorrectAnswersExplanation: {
      A: "The passage doesn't mention Tyler writing about dinosaurs.",
      C: "While wolves and dogs are related, the passage specifically states Tyler wrote about a wolf, not a dog.",
      D: "The passage doesn't mention Tyler writing about eagles.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "literal meaning", "details"],
    timeEstimate: 60,
    webLink: "https://www.k12reader.com/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "In the school play about famous inventors, Alicia was cast as Marie Curie, Alex played Thomas Edison, and Jamal portrayed George Washington Carver. Each student researched their character's life and accomplishments. On opening night, the auditorium was packed with parents and teachers. Despite forgetting a few lines, the students received a standing ovation for their performances.",
    question: "What problem occurred during the play?",
    options: [
      "A) The auditorium was empty",
      "B) The costumes were missing",
      "C) Some students forgot their lines",
      "D) The lights went out during the performance",
    ],
    correctAnswer: "C",
    hint: "Look for what minor issue happened during the performance.",
    correctAnswerExplanation:
      "The passage states that 'Despite forgetting a few lines, the students received a standing ovation for their performances.' This indicates that some students forgetting their lines was the problem that occurred during the play.",
    incorrectAnswersExplanation: {
      A: "The passage actually states that 'the auditorium was packed with parents and teachers,' not empty.",
      B: "The passage doesn't mention any issues with costumes.",
      D: "There's no mention of lighting problems in the passage.",
    },
    difficulty: "Medium",
    tags: ["comprehension", "problem identification", "details"],
    timeEstimate: 60,
    webLink: "https://www.readworks.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "Ethan couldn't believe his luck when he won tickets to the Natural History Museum's special 'Night at the Museum' event. Visitors would get to explore the dinosaur hall after dark with only flashlights to guide them. There would even be paleontologists stationed throughout the exhibit to answer questions. Ethan invited his best friend, Riley, who knew everything about prehistoric creatures.",
    question: "Why might Ethan have invited Riley to the museum event?",
    options: [
      "A) Because Riley works at the museum",
      "B) Because Riley is afraid of the dark",
      "C) Because Riley knows a lot about dinosaurs",
      "D) Because Riley had extra flashlights",
    ],
    correctAnswer: "C",
    hint: "The passage gives information about Riley's knowledge that relates to the museum event.",
    correctAnswerExplanation:
      "The passage states that Ethan 'invited his best friend, Riley, who knew everything about prehistoric creatures.' Since the event was at a Natural History Museum with dinosaur exhibits, Riley's knowledge about prehistoric creatures would make them a perfect companion.",
    incorrectAnswersExplanation: {
      A: "The passage doesn't mention Riley working at the museum.",
      B: "There's no mention of Riley being afraid of the dark; in fact, the event takes place in the dark with flashlights.",
      D: "The passage doesn't mention Riley having extra flashlights.",
    },
    difficulty: "Hard",
    tags: ["comprehension", "inference", "cause and effect"],
    timeEstimate: 90,
    webLink: "https://www.commonlit.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "The Westside Library's summer reading program had a unique twist this year. For each book students read, they earned points that translated to real money donated to save endangered wolves. Maya was determined to read more books than anyone else. Not only did she love reading, but she also had visited a wolf sanctuary last year and felt connected to their cause.",
    question: "What were two reasons Maya wanted to read many books?",
    options: [
      "A) To win a prize and impress her teachers",
      "B) To enjoy reading and help save wolves",
      "C) To beat her friends and earn money for herself",
      "D) To please her parents and improve her grades",
    ],
    correctAnswer: "B",
    hint: "Look for Maya's personal motivation and the program's purpose.",
    correctAnswerExplanation:
      "The passage states that Maya 'loved reading' (first reason) and that she 'had visited a wolf sanctuary last year and felt connected to their cause' (second reason). These combine to show she wanted to read for enjoyment and to help the wolf conservation effort.",
    incorrectAnswersExplanation: {
      A: "The passage doesn't mention prizes or Maya wanting to impress teachers.",
      C: "While Maya wanted to 'read more books than anyone else,' the money earned went to save wolves, not to Maya personally.",
      D: "The passage doesn't mention Maya's parents or grades as motivations.",
    },
    difficulty: "Hard",
    tags: ["comprehension", "motivation", "multiple elements"],
    timeEstimate: 90,
    webLink: "https://www.readingrockets.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "Leo couldn't help but laugh when his younger brother Adam let out an enormous fart during the school talent show. The sound echoed through the quiet auditorium right before Leo's piano solo. Somehow, Leo managed to compose himself, take a deep breath, and still deliver a flawless performance of Mozart's 'Rondo Alla Turca.' His music teacher later commented that it was the most focused she had ever seen him play.",
    question: "What is the most surprising element of this passage?",
    options: [
      "A) That Adam disrupted the talent show",
      "B) That Leo played Mozart's 'Rondo Alla Turca'",
      "C) That Leo performed better than usual despite the disruption",
      "D) That the music teacher attended the talent show",
    ],
    correctAnswer: "C",
    hint: "Consider what the music teacher said about Leo's performance.",
    correctAnswerExplanation:
      "The surprising element is that despite the embarrassing disruption from his brother, Leo 'still deliver[ed] a flawless performance' and his teacher commented 'it was the most focused she had ever seen him play.' This shows Leo performed better than usual despite circumstances that could have ruined his concentration.",
    incorrectAnswersExplanation: {
      A: "While disruptive, a younger sibling causing embarrassment isn't particularly surprising.",
      B: "The specific piece Leo played isn't presented as surprising in the passage.",
      D: "A music teacher attending a school talent show would be expected, not surprising.",
    },
    difficulty: "Hard",
    tags: ["comprehension", "inference", "unexpected outcomes"],
    timeEstimate: 90,
    webLink: "https://www.k12reader.com/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "The old bookstore on Main Street held a secret known only to regular customers. Behind a revolving bookshelf in the history section was a hidden reading room with comfortable chairs and free hot chocolate. The owner, Mrs. Chen, created this space for people who truly loved books and needed a quiet place to read. She believed that reading was not just about absorbing information, but about finding sanctuary in stories.",
    question:
      "What does this passage suggest about Mrs. Chen's view of reading?",
    options: [
      "A) Reading should be expensive and exclusive",
      "B) Reading is primarily for learning facts",
      "C) Reading is a social activity best done in groups",
      "D) Reading is both informative and a form of retreat or comfort",
    ],
    correctAnswer: "D",
    hint: "Look at Mrs. Chen's stated belief about reading in the last sentence.",
    correctAnswerExplanation:
      "The passage states that Mrs. Chen 'believed that reading was not just about absorbing information, but about finding sanctuary in stories.' This shows she viewed reading as both informative (absorbing information) and as a retreat or comfort (finding sanctuary).",
    incorrectAnswersExplanation: {
      A: "Mrs. Chen offered free hot chocolate and created a special space for readers, suggesting she wanted to make reading accessible, not exclusive.",
      B: "The passage explicitly states that Mrs. Chen believed reading was 'not just about absorbing information,' contradicting this option.",
      C: "The creation of a 'quiet place to read' suggests Mrs. Chen valued solitary reading, not reading as a primarily social activity.",
    },
    difficulty: "Hard",
    tags: ["comprehension", "theme", "character beliefs"],
    timeEstimate: 90,
    webLink: "https://www.readworks.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "The Junior Paleontologists Club took a field trip to the Morrison Formation in Colorado, a famous site for dinosaur fossils. Before digging, Dr. Martinez explained the proper techniques for excavation. 'Remember, we must document everything exactly as we find it,' she emphasized. 'A fossil's position tells us as much about the dinosaur's life as the fossil itself.' The students nodded, eager to apply their classroom knowledge to real fieldwork.",
    question:
      "What important principle of paleontology does Dr. Martinez emphasize?",
    options: [
      "A) Finding as many fossils as possible is the primary goal",
      "B) The context and position of a fossil provides crucial information",
      "C) Dinosaur fossils are only found in Colorado",
      "D) Students should work as quickly as possible",
    ],
    correctAnswer: "B",
    hint: "Consider what Dr. Martinez says about a fossil's position.",
    correctAnswerExplanation:
      "Dr. Martinez states that 'A fossil's position tells us as much about the dinosaur's life as the fossil itself' and emphasizes that they 'must document everything exactly as we find it.' This demonstrates the principle that the context and position of fossils provide crucial scientific information.",
    incorrectAnswersExplanation: {
      A: "Dr. Martinez emphasizes documentation and careful excavation rather than quantity of fossils found.",
      C: "The passage doesn't suggest fossils are only found in Colorado; it simply mentions this as one famous site.",
      D: "The emphasis on documentation and careful technique contradicts the idea of working quickly.",
    },
    difficulty: "Hard",
    tags: ["comprehension", "main idea", "scientific principles"],
    timeEstimate: 90,
    webLink: "https://www.commonlit.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "Amara had always struggled with reading aloud in class. Her words would jumble, and her classmates would sometimes giggle. This year, her teacher, Mr. Jackson, had a different approach. He started a 'Reading Buddies' program where students read to therapy dogs that visited once a week. With no judgment from her canine listener, Amara's confidence grew. By spring, she volunteered to read the morning announcements over the school intercom.",
    question: "How did the 'Reading Buddies' program help Amara?",
    options: [
      "A) It taught her how to train dogs",
      "B) It allowed her to practice reading without feeling judged",
      "C) It excused her from reading assignments",
      "D) It paired her with better readers who read for her",
    ],
    correctAnswer: "B",
    hint: "Think about what was different about reading to dogs versus reading to classmates.",
    correctAnswerExplanation:
      "The passage states that 'With no judgment from her canine listener, Amara's confidence grew.' This shows that the program helped Amara by giving her a way to practice reading aloud without the fear of judgment that had previously made reading difficult for her.",
    incorrectAnswersExplanation: {
      A: "The program involved reading to dogs, not learning to train them.",
      C: "The program provided additional reading practice, not exemption from reading assignments.",
      D: "The program paired students with dogs, not with other students who would read for them.",
    },
    difficulty: "Hard",
    tags: ["comprehension", "cause and effect", "problem and solution"],
    timeEstimate: 90,
    webLink: "https://www.readingrockets.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "The ancient wolves of North America were larger than today's wolves, with stronger jaws and heavier builds. These prehistoric predators lived alongside massive creatures like woolly mammoths and giant sloths. As the climate warmed and their large prey disappeared, wolves evolved to become smaller and faster, better suited for chasing deer and elk through forests. This adaptation allowed wolves to survive while many other Ice Age animals went extinct.",
    question:
      "What caused wolves to evolve and become smaller according to the passage?",
    options: [
      "A) They were hunted by humans",
      "B) They moved to different territories",
      "C) Changes in climate and available prey",
      "D) Competition with other predators",
    ],
    correctAnswer: "C",
    hint: "Look for environmental changes mentioned in the passage that affected wolves.",
    correctAnswerExplanation:
      "The passage states that 'As the climate warmed and their large prey disappeared, wolves evolved to become smaller and faster.' This directly identifies changes in climate and available prey as the factors that caused wolves to evolve into smaller animals.",
    incorrectAnswersExplanation: {
      A: "The passage doesn't mention hunting by humans as a factor in wolf evolution.",
      B: "While territorial changes might be implied, the passage specifically cites climate change and prey changes as the direct causes.",
      D: "The passage doesn't mention competition with other predators as a factor.",
    },
    difficulty: "Hard",
    tags: ["comprehension", "cause and effect", "scientific concepts"],
    timeEstimate: 90,
    webLink: "https://www.k12reader.com/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "The community library's Minecraft building competition had strict rules: create a structure inspired by a book you've read this year. Twelve-year-old Jordan designed an elaborate underground laboratory based on 'The Mysterious Benedict Society.' He included hidden passages, secret codes, and even a replica of Mr. Benedict's red bucket chair. The judges were impressed by how Jordan had captured the book's essence while adding his own creative elements.",
    question:
      "What aspect of Jordan's design particularly impressed the judges?",
    options: [
      "A) The size of his structure",
      "B) The bright colors he used",
      "C) How he balanced representing the book while adding original elements",
      "D) The fact that he finished before the deadline",
    ],
    correctAnswer: "C",
    hint: "Look at what specifically impressed the judges in the last sentence.",
    correctAnswerExplanation:
      "The passage states that 'The judges were impressed by how Jordan had captured the book's essence while adding his own creative elements.' This shows they appreciated his balance of faithfully representing the book while also incorporating original ideas.",
    incorrectAnswersExplanation: {
      A: "The passage doesn't mention the size of Jordan's creation impressing the judges.",
      B: "The passage doesn't mention bright colors being used or impressing the judges.",
      D: "The passage doesn't mention anything about Jordan's timing or the competition deadline.",
    },
    difficulty: "Hard",
    tags: ["comprehension", "details", "evaluation"],
    timeEstimate: 90,
    webLink: "https://www.readworks.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "For the science fair, Olivia created a display about how different dog breeds were developed for specific purposes. Her poster showed how Border Collies were bred for herding, Saint Bernards for mountain rescue, and Dachshunds for hunting badgers. 'The shape of a dog's body tells you about its original job,' Olivia explained to the judges. 'For example, Dachshunds have short legs and long bodies to enter badger tunnels underground.'",
    question: "What was the main point of Olivia's science fair project?",
    options: [
      "A) Dogs make good pets for families",
      "B) Some dog breeds are smarter than others",
      "C) Dog breeds were developed with physical traits suited to specific tasks",
      "D) All dogs descended from wolves thousands of years ago",
    ],
    correctAnswer: "C",
    hint: "Look at the explanation Olivia gives to the judges about dog bodies and their jobs.",
    correctAnswerExplanation:
      "Olivia's main point was that dog breeds were developed with physical characteristics that helped them perform specific jobs. This is shown in her statement that 'The shape of a dog's body tells you about its original job' and her example of Dachshunds' body shape being suited to their hunting purpose.",
    incorrectAnswersExplanation: {
      A: "The passage doesn't discuss dogs as pets or their suitability for families.",
      B: "The passage doesn't compare the intelligence of different breeds.",
      D: "While this might be true, the passage doesn't mention wolf ancestry as part of Olivia's project.",
    },
    difficulty: "Hard",
    tags: ["comprehension", "main idea", "scientific concepts"],
    timeEstimate: 90,
    webLink: "https://www.commonlit.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "The class writing project required students to research an endangered animal and create an informative brochure. Madison chose the red wolf, a species native to the southeastern United States. She discovered that red wolves once roamed across the eastern U.S. but were nearly hunted to extinction by the 1970s. Thanks to conservation efforts, some red wolves now live in protected areas, though fewer than 20 remain in the wild. Madison's brochure included ways people could help support red wolf recovery.",
    question:
      "What sequence of events affected red wolf populations according to the passage?",
    options: [
      "A) They were introduced to the U.S., became overpopulated, then were controlled by hunting",
      "B) They were common, then nearly went extinct from hunting, then partially recovered through conservation",
      "C) They were always rare, then became a protected species, then increased in numbers",
      "D) They migrated to the southeastern U.S., adapted to the environment, then became endangered",
    ],
    correctAnswer: "B",
    hint: "Look for the historical pattern of red wolf population changes mentioned in the passage.",
    correctAnswerExplanation:
      "The passage states that red wolves 'once roamed across the eastern U.S.' (were common), 'but were nearly hunted to extinction by the 1970s' (nearly went extinct from hunting), and 'Thanks to conservation efforts, some red wolves now live in protected areas' (partially recovered through conservation).",
    incorrectAnswersExplanation: {
      A: "The passage indicates red wolves are native to the U.S., not introduced, and doesn't mention overpopulation.",
      C: "The passage suggests they were once common ('roamed across the eastern U.S.'), not always rare.",
      D: "The passage states they are 'native to the southeastern United States,' not that they migrated there.",
    },
    difficulty: "Hard",
    tags: ["comprehension", "sequence", "cause and effect"],
    timeEstimate: 90,
    webLink: "https://www.readingrockets.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "When the principal announced that this year's school play would be about the discovery of dinosaur fossils, Mr. Thompson's sixth-grade class was thrilled. Aiden hoped to play the lead paleontologist, while Sophia wanted to design the dinosaur costumes. Even quiet Eduardo, who usually avoided performances, volunteered to help write the script. 'I've read every dinosaur book in the library,' he told Mr. Thompson with unexpected enthusiasm.",
    question: "What can you infer about Eduardo from this passage?",
    options: [
      "A) He wants to be the star of the play",
      "B) He dislikes working with his classmates",
      "C) He is usually shy but has a strong interest in dinosaurs",
      "D) He is the best writer in the class",
    ],
    correctAnswer: "C",
    hint: "Consider what the passage says about Eduardo's typical behavior versus his reaction to the dinosaur play.",
    correctAnswerExplanation:
      "The passage describes Eduardo as 'quiet' who 'usually avoided performances' but volunteered to help write the script and showed 'unexpected enthusiasm' because of his extensive reading about dinosaurs. This suggests he's typically shy but has a strong interest in the dinosaur topic.",
    incorrectAnswersExplanation: {
      A: "Eduardo volunteered to write the script, not to act in the play, suggesting he doesn't want to be the star.",
      B: "The passage doesn't suggest Eduardo dislikes working with classmates; he voluntarily joined the play project.",
      D: "While Eduardo volunteered to help write the script, the passage doesn't indicate he's known as the best writer.",
    },
    difficulty: "Hard",
    tags: ["comprehension", "character analysis", "inference"],
    timeEstimate: 90,
    webLink: "https://www.k12reader.com/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "Jasmine's favorite part of summer was the annual camping trip to Yellowstone National Park. This year, she was determined to spot a wolf in the wild. She read about wolf behavior, learned to identify paw prints, and packed her father's binoculars. On the third morning, while everyone else was still asleep, Jasmine quietly left the tent. From a safe distance, she watched as a gray wolf trotted along the tree line at dawn, its breath visible in the cool air.",
    question: "Which best describes the structure of this passage?",
    options: [
      "A) Problem and solution",
      "B) Cause and effect",
      "C) Compare and contrast",
      "D) Goal, preparation, and achievement",
    ],
    correctAnswer: "D",
    hint: "Look at how the passage progresses from Jasmine's desire through her actions to the final outcome.",
    correctAnswerExplanation:
      "The passage follows a clear structure: Jasmine's goal ('determined to spot a wolf'), her preparations ('read about wolf behavior, learned to identify paw prints, and packed binoculars'), and finally her achievement ('watched as a gray wolf trotted along the tree line').",
    incorrectAnswersExplanation: {
      A: "While Jasmine has a goal, the passage doesn't present it as a problem that needs solving.",
      B: "Though preparation contributed to success, the passage is more focused on the sequence of goal-setting, preparation, and achievement.",
      C: "The passage doesn't compare or contrast different elements; it follows a single narrative sequence.",
    },
    difficulty: "Hard",
    tags: ["comprehension", "text structure", "analysis"],
    timeEstimate: 90,
    webLink: "https://www.readworks.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "The ancient scrolls discovered in the Arizona cave contained something extraordinary—drawings of what appeared to be dinosaurs interacting with humans. Dr. Wilson carefully photographed and cataloged each image before sharing them with colleagues. 'While these drawings are fascinating,' she wrote in her report, 'we must consider that they may represent mythical creatures rather than actual dinosaurs. The artists who created these images 2,000 years ago had no access to fossil records as we know them today.'",
    question:
      "What perspective does Dr. Wilson take regarding the cave drawings?",
    options: [
      "A) Excited belief that they prove humans and dinosaurs lived together",
      "B) Anger that someone created fake ancient drawings",
      "C) Cautious scientific skepticism while documenting the evidence",
      "D) Dismissal of the drawings as completely worthless",
    ],
    correctAnswer: "C",
    hint: "Consider Dr. Wilson's actions and statements about the drawings.",
    correctAnswerExplanation:
      "Dr. Wilson demonstrates cautious scientific skepticism by carefully documenting the evidence ('carefully photographed and cataloged each image') while suggesting alternative interpretations ('may represent mythical creatures rather than actual dinosaurs') and providing context for why the images shouldn't be taken at face value.",
    incorrectAnswersExplanation: {
      A: "Dr. Wilson specifically cautions against this interpretation, suggesting the drawings might represent myths instead.",
      B: "There's no indication Dr. Wilson believes the drawings are fake; she treats them as genuine ancient artifacts.",
      D: "Dr. Wilson clearly values the drawings, calling them 'fascinating' and carefully documenting them, not dismissing them.",
    },
    difficulty: "Hard",
    tags: ["comprehension", "author's perspective", "scientific reasoning"],
    timeEstimate: 90,
    webLink: "https://www.commonlit.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Reading",
    topic: "Comprehension",
    grade: 6,
    questionType: "MC",
    passage:
      "The reading buddies program paired sixth graders with first graders twice a week. At first, Noah was disappointed—he'd rather play basketball than read picture books to little kids. But his assigned buddy, Emma, was so excited to see him each Tuesday that Noah started to enjoy their sessions. He even practiced reading with expression to make the stories come alive. By year's end, Noah realized he had not only helped Emma improve her reading but had become a more confident reader himself.",
    question:
      "How did Noah's attitude toward the reading buddies program change?",
    options: [
      "A) He started excited but became bored with it",
      "B) He disliked it throughout the entire year",
      "C) He initially disliked it but grew to value the experience",
      "D) His attitude remained consistently positive",
    ],
    correctAnswer: "C",
    hint: "Look at Noah's feelings at the beginning compared to the end of the passage.",
    correctAnswerExplanation:
      "The passage states that 'At first, Noah was disappointed' and would 'rather play basketball than read picture books,' showing his initial negative attitude. Later, he 'started to enjoy their sessions' and 'realized he had not only helped Emma improve her reading but had become a more confident reader himself,' showing his changed, positive perspective.",
    incorrectAnswersExplanation: {
      A: "This is the opposite of what happened; Noah started disappointed but ended up enjoying the program.",
      B: "The passage clearly shows Noah's attitude improved over time; he didn't dislike it throughout the year.",
      D: "Noah's attitude wasn't consistently positive; it changed from negative to positive.",
    },
    difficulty: "Hard",
    tags: ["comprehension", "character development", "theme"],
    timeEstimate: 90,
    webLink: "https://www.readingrockets.org/",
    source: "Claude",
    lastUpdated: "2025-04-23",
  },
];

export default readingGrade6Questions;
