// lib/questions/science-grade6.ts
const scienceGrade6Questions = [
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "At a Florida zoo, a wolf’s heart beats fast when it sees a dinosaur skeleton—what does the heart do for the wolf?",
    options: [
      "A) It helps the wolf breathe.",
      "B) It pumps blood throughout the wolf's body.",
      "C) It digests the wolf's food.",
      "D) It controls the wolf's movements.",
    ],
    correctAnswer: "B",
    hint: "Think about what organ moves blood in animals.",
    correctAnswerExplanation:
      "The heart pumps blood, carrying oxygen and nutrients to the wolf's body, which is essential for its survival.",
    incorrectAnswersExplanation: {
      A: "Breathing is primarily managed by the lungs, not the heart.",
      C: "Digestion is handled by the stomach and intestines, not the heart.",
      D: "Movement is controlled by the brain and muscles, not the heart.",
    },
    difficulty: "Medium",
    tags: ["biology", "circulatory system", "animals"],
    timeEstimate: 60,
    webLink: "https://kids.nationalgeographic.com/science/article/heart",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "During a science fair in Texas, a student pushes a toy car with a force—how does the car move?",
    options: [
      "A) It stays still regardless of the push.",
      "B) It moves in the opposite direction of the push.",
      "C) It moves in the direction of the applied force.",
      "D) It moves randomly without any pattern.",
    ],
    correctAnswer: "C",
    hint: "Objects move in the direction of the force applied to them.",
    correctAnswerExplanation:
      "When a force is applied to an object, like pushing a toy car, it moves in the direction of that force due to Newton's First Law of Motion.",
    incorrectAnswersExplanation: {
      A: "An object will move if a sufficient force is applied.",
      B: "Objects move in the direction of the applied force, not the opposite.",
      D: "Movement follows the direction of the force, not randomly.",
    },
    difficulty: "Medium",
    tags: ["physics", "force", "motion"],
    timeEstimate: 60,
    webLink:
      "https://kids.nationalgeographic.com/science/article/force-and-motion",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Earth Science",
    grade: 6,
    questionType: "MC",
    question:
      "A student in California reads about the Grand Canyon—what type of rock is most common there?",
    options: [
      "A) Igneous rock",
      "B) Sedimentary rock",
      "C) Metamorphic rock",
      "D) Lava rock",
    ],
    correctAnswer: "B",
    hint: "Think about rocks formed from layers over time.",
    correctAnswerExplanation:
      "The Grand Canyon is primarily composed of sedimentary rocks, which are formed by the accumulation and compression of mineral and organic particles over millions of years.",
    incorrectAnswersExplanation: {
      A: "Igneous rocks form from cooled lava or magma, which is less common in the Grand Canyon.",
      C: "Metamorphic rocks are altered by heat and pressure, not predominant in the Grand Canyon.",
      D: "Lava rocks are a type of igneous rock and are not the main type found in the Grand Canyon.",
    },
    difficulty: "Medium",
    tags: ["earth science", "geology", "rocks"],
    timeEstimate: 60,
    webLink: "https://kids.nationalgeographic.com/science/article/rocks",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Scientific Inquiry",
    grade: 6,
    questionType: "MC",
    question:
      "In a classroom experiment, students observe that plants grow faster with more sunlight. What is the variable they are testing?",
    options: [
      "A) Type of plant",
      "B) Amount of water",
      "C) Amount of sunlight",
      "D) Type of soil",
    ],
    correctAnswer: "C",
    hint: "Consider what factor is being changed to observe its effect.",
    correctAnswerExplanation:
      "The amount of sunlight is the independent variable being tested to see its effect on plant growth.",
    incorrectAnswersExplanation: {
      A: "If the type of plant remains the same, it's not the variable being tested.",
      B: "Assuming water is kept constant, it's not the variable being tested.",
      D: "If the soil type doesn't change, it's not the variable being tested.",
    },
    difficulty: "Medium",
    tags: ["scientific inquiry", "experiments", "variables"],
    timeEstimate: 60,
    webLink:
      "https://www.sciencebuddies.org/science-fair-projects/science-fair/variables",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "At a Florida zoo, a wolf\u2019s heart beats fast when it sees a dinosaur skeleton\u2014what does the heart do for the wolf?",
    options: [
      "A) It helps the wolf breathe.",
      "B) It pumps blood throughout the wolf's body.",
      "C) It digests the wolf's food.",
      "D) It controls the wolf's movements.",
    ],
    correctAnswer: "B",
    hint: "Think about what organ moves blood in animals.",
    correctAnswerExplanation:
      "The heart pumps blood, carrying oxygen and nutrients to the wolf's body, which is essential for its survival.",
    incorrectAnswersExplanation: {
      A: "Breathing is primarily managed by the lungs, not the heart.",
      C: "Digestion is handled by the stomach and intestines, not the heart.",
      D: "Movement is controlled by the brain and muscles, not the heart.",
    },
    difficulty: "Medium",
    tags: ["biology", "circulatory system", "animals"],
    timeEstimate: 60,
    webLink: "https://kids.nationalgeographic.com/science/article/heart",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "During a science fair in Texas, a student pushes a toy car with a force\u2014how does the car move?",
    options: [
      "A) It stays still regardless of the push.",
      "B) It moves in the opposite direction of the push.",
      "C) It moves in the direction of the applied force.",
      "D) It moves randomly without any pattern.",
    ],
    correctAnswer: "C",
    hint: "Objects move in the direction of the force applied to them.",
    correctAnswerExplanation:
      "When a force is applied to an object, like pushing a toy car, it moves in the direction of that force due to Newton's First Law of Motion.",
    incorrectAnswersExplanation: {
      A: "An object will move if a sufficient force is applied.",
      B: "Objects move in the direction of the applied force, not the opposite.",
      D: "Movement follows the direction of the force, not randomly.",
    },
    difficulty: "Medium",
    tags: ["physics", "force", "motion"],
    timeEstimate: 60,
    webLink:
      "https://kids.nationalgeographic.com/science/article/force-and-motion",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Earth Science",
    grade: 6,
    questionType: "MC",
    question:
      "A student in California reads about the Grand Canyon\u2014what type of rock is most common there?",
    options: [
      "A) Igneous rock",
      "B) Sedimentary rock",
      "C) Metamorphic rock",
      "D) Lava rock",
    ],
    correctAnswer: "B",
    hint: "Think about rocks formed from layers over time.",
    correctAnswerExplanation:
      "The Grand Canyon is primarily composed of sedimentary rocks, which are formed by the accumulation and compression of mineral and organic particles over millions of years.",
    incorrectAnswersExplanation: {
      A: "Igneous rocks form from cooled lava or magma, which is less common in the Grand Canyon.",
      C: "Metamorphic rocks are altered by heat and pressure, not predominant in the Grand Canyon.",
      D: "Lava rocks are a type of igneous rock and are not the main type found in the Grand Canyon.",
    },
    difficulty: "Medium",
    tags: ["earth science", "geology", "rocks"],
    timeEstimate: 60,
    webLink: "https://kids.nationalgeographic.com/science/article/rocks",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Scientific Inquiry",
    grade: 6,
    questionType: "MC",
    question:
      "In a classroom experiment, students observe that plants grow faster with more sunlight. What is the variable they are testing?",
    options: [
      "A) Type of plant",
      "B) Amount of water",
      "C) Amount of sunlight",
      "D) Type of soil",
    ],
    correctAnswer: "C",
    hint: "Consider what factor is being changed to observe its effect.",
    correctAnswerExplanation:
      "The amount of sunlight is the independent variable being tested to see its effect on plant growth.",
    incorrectAnswersExplanation: {
      A: "If the type of plant remains the same, it's not the variable being tested.",
      B: "Assuming water is kept constant, it's not the variable being tested.",
      D: "If the soil type doesn't change, it's not the variable being tested.",
    },
    difficulty: "Medium",
    tags: ["scientific inquiry", "experiments", "variables"],
    timeEstimate: 60,
    webLink:
      "https://www.sciencebuddies.org/science-fair-projects/science-fair/variables",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "A dog in Stardew Valley plants a \u2018paws-itively\u2019 glowing flower\u2014what causes the glow?",
    options: [
      "A) Magic spells",
      "B) Bioluminescence",
      "C) Solar energy",
      "D) Radioactivity",
    ],
    correctAnswer: "B",
    hint: "Some organisms produce light naturally.",
    correctAnswerExplanation:
      "Bioluminescence is the natural emission of light by living organisms, like certain flowers or animals.",
    incorrectAnswersExplanation: {
      A: "Magic spells are fictional and not a scientific explanation.",
      C: "Solar energy powers photosynthesis but doesn't cause organisms to glow.",
      D: "Radioactivity can emit light but is harmful and not related to natural glowing in organisms.",
    },
    difficulty: "Medium",
    tags: ["chemistry", "bioluminescence"],
    timeEstimate: 60,
    webLink:
      "https://www.scientificamerican.com/article/what-is-bioluminescence/",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "At a Florida zoo, a wolf’s heart beats fast when it sees a dinosaur skeleton—what does the heart do for the wolf?",
    options: [
      "A) Pumps blood to the body",
      "B) Helps the wolf see better",
      "C) Makes the wolf howl louder",
      "D) Keeps the wolf warm",
    ],
    correctAnswer: "A",
    hint: "Think about what your heart does when you run fast.",
    correctAnswerExplanation:
      "The heart pumps blood to carry oxygen and nutrients to the wolf’s muscles and organs. This helps the wolf stay strong and active, especially when it’s excited or scared by a dinosaur skeleton.",
    incorrectAnswersExplanation: {
      B: "The heart doesn’t affect vision; eyes help the wolf see.",
      C: "Howling comes from the lungs and throat, not the heart.",
      D: "The heart doesn’t directly control body warmth; fur and metabolism do.",
    },
    difficulty: "Medium",
    tags: ["biology", "wolf", "heart"],
    timeEstimate: 60,
    webLink:
      "https://kids.nationalgeographic.com/animals/mammals/facts/gray-wolf",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "A dog in a Texas park sniffs a plant—what part of the plant makes food for it?",
    options: ["A) Roots", "B) Leaves", "C) Stem", "D) Flower"],
    correctAnswer: "B",
    hint: "Look at what part of a plant is green and flat.",
    correctAnswerExplanation:
      "Leaves use sunlight, water, and carbon dioxide to make food for the plant through a process called photosynthesis. This food helps the plant grow strong.",
    incorrectAnswersExplanation: {
      A: "Roots take in water and nutrients, but they don’t make food.",
      C: "The stem supports the plant and moves water, not makes food.",
      D: "Flowers help make seeds, not food for the plant.",
    },
    difficulty: "Medium",
    tags: ["biology", "plant", "photosynthesis"],
    timeEstimate: 60,
    webLink:
      "https://www.sciencebuddies.org/stem-activities/leaf-photosynthesis",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "In a Yellowstone National Park study, scientists find that wolves have sharp teeth—what are these teeth mainly used for?",
    options: [
      "A) Chewing plants",
      "B) Tearing meat",
      "C) Digging burrows",
      "D) Grooming fur",
    ],
    correctAnswer: "B",
    hint: "Think about what wolves eat in the wild.",
    correctAnswerExplanation:
      "Wolves are carnivores, and their sharp teeth are designed to tear meat from their prey. This helps them eat animals like deer or elk.",
    incorrectAnswersExplanation: {
      A: "Wolves don’t eat plants; their teeth aren’t made for chewing leaves.",
      C: "Wolves use their paws, not teeth, to dig.",
      D: "Grooming is done with the tongue, not sharp teeth.",
    },
    difficulty: "Medium",
    tags: ["biology", "wolf", "teeth"],
    timeEstimate: 60,
    webLink:
      "https://kids.nationalgeographic.com/animals/mammals/facts/gray-wolf",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "A student in California reads about a T-Rex skeleton—how did its bones help it move?",
    options: [
      "A) They stored food",
      "B) They supported its body",
      "C) They made it swim faster",
      "D) They helped it see far",
    ],
    correctAnswer: "B",
    hint: "Think about what your bones do when you walk.",
    correctAnswerExplanation:
      "The T-Rex’s bones formed a strong skeleton that supported its heavy body and allowed it to move, walk, and run. Without bones, it would collapse.",
    incorrectAnswersExplanation: {
      A: "Bones don’t store food; they provide structure.",
      C: "T-Rex didn’t swim much; its bones were for land movement.",
      D: "Bones don’t help with vision; eyes do that.",
    },
    difficulty: "Medium",
    tags: ["biology", "dinosaur", "skeleton"],
    timeEstimate: 60,
    webLink:
      "https://www.nationalgeographic.com/science/article/dinosaur-fossils",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "A dog in Stardew Valley plants a ‘paws-itively’ glowing flower—what process in the flower causes the glow?",
    options: [
      "A) Photosynthesis",
      "B) Bioluminescence",
      "C) Respiration",
      "D) Digestion",
    ],
    correctAnswer: "B",
    hint: "Think about animals like fireflies that glow.",
    correctAnswerExplanation:
      "Bioluminescence is when living things, like some plants or animals, produce light through a chemical reaction. This makes the flower glow in the game.",
    incorrectAnswersExplanation: {
      A: "Photosynthesis makes food using sunlight, not light emission.",
      C: "Respiration provides energy, but doesn’t create glow.",
      D: "Digestion breaks down food, not related to glowing.",
    },
    difficulty: "Medium",
    tags: ["biology", "bioluminescence", "plant"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/bioluminescence",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "In a Colorado forest, a wolf’s eyes help it hunt at night—what part of the eye lets in light?",
    options: ["A) Retina", "B) Pupil", "C) Lens", "D) Cornea"],
    correctAnswer: "B",
    hint: "Think about the black circle in the middle of your eye.",
    correctAnswerExplanation:
      "The pupil is the opening in the eye that lets light in so the wolf can see in the dark. It gets bigger in low light to help the wolf hunt.",
    incorrectAnswersExplanation: {
      A: "The retina detects light, but doesn’t let it in.",
      C: "The lens focuses light, not controls its entry.",
      D: "The cornea protects the eye, but the pupil controls light.",
    },
    difficulty: "Medium",
    tags: ["biology", "wolf", "eye"],
    timeEstimate: 60,
    webLink:
      "https://kids.nationalgeographic.com/science/article/how-eyes-work",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "A student in New York writes about a frog—what type of animal is a frog?",
    options: ["A) Mammal", "B) Reptile", "C) Amphibian", "D) Bird"],
    correctAnswer: "C",
    hint: "Think about animals that live both in water and on land.",
    correctAnswerExplanation:
      "Frogs are amphibians, which means they can live in water and on land and often have moist skin. They start as tadpoles in water and grow into frogs.",
    incorrectAnswersExplanation: {
      A: "Mammals have fur or hair and feed milk to their young, unlike frogs.",
      B: "Reptiles have dry, scaly skin, not moist like frogs.",
      D: "Birds have feathers and wings, which frogs don’t have.",
    },
    difficulty: "Medium",
    tags: ["biology", "amphibian", "frog"],
    timeEstimate: 60,
    webLink:
      "https://kids.nationalgeographic.com/animals/amphibians/facts/frog",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "During a school trip to a Montana museum, a student sees a Triceratops skeleton—what was its diet?",
    options: ["A) Meat", "B) Plants", "C) Fish", "D) Insects"],
    correctAnswer: "B",
    hint: "Think about the shape of a Triceratops’s mouth.",
    correctAnswerExplanation:
      "Triceratops was a herbivore, meaning it ate plants like ferns and leaves. Its beak and teeth were designed to chew tough plant material.",
    incorrectAnswersExplanation: {
      A: "Meat was eaten by carnivores like T-Rex, not Triceratops.",
      C: "Triceratops lived on land, not near water to eat fish.",
      D: "Insects were too small for a large dinosaur like Triceratops.",
    },
    difficulty: "Medium",
    tags: ["biology", "dinosaur", "herbivore"],
    timeEstimate: 60,
    webLink:
      "https://www.nationalgeographic.com/science/article/dinosaur-fossils",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "A dog in a Virginia park chases a butterfly—what helps the butterfly fly?",
    options: ["A) Wings", "B) Antennae", "C) Legs", "D) Eyes"],
    correctAnswer: "A",
    hint: "Think about what flaps when a butterfly moves through the air.",
    correctAnswerExplanation:
      "A butterfly’s wings are light and strong, allowing it to fly by flapping them. This helps it escape from the dog.",
    incorrectAnswersExplanation: {
      B: "Antennae help butterflies sense their surroundings, not fly.",
      C: "Legs are for landing and walking, not flying.",
      D: "Eyes help butterflies see, but don’t help with flight.",
    },
    difficulty: "Medium",
    tags: ["biology", "butterfly", "wings"],
    timeEstimate: 60,
    webLink:
      "https://kids.nationalgeographic.com/animals/invertebrates/facts/monarch-butterfly",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "In an Arizona classroom, a student learns that wolves live in packs—what is the main benefit of living in a pack?",
    options: [
      "A) Better hunting success",
      "B) Warmer fur",
      "C) Louder howls",
      "D) Faster running",
    ],
    correctAnswer: "A",
    hint: "Think about why wolves work together when they hunt.",
    correctAnswerExplanation:
      "Living in a pack helps wolves hunt better because they can work together to catch larger prey, like deer. This makes it easier to find food for the group.",
    incorrectAnswersExplanation: {
      B: "Fur keeps wolves warm, not the pack.",
      C: "Howling is for communication, not improved by packs.",
      D: "Running speed depends on the wolf, not the pack.",
    },
    difficulty: "Medium",
    tags: ["biology", "wolf", "pack"],
    timeEstimate: 60,
    webLink:
      "https://kids.nationalgeographic.com/animals/mammals/facts/gray-wolf",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Oregon studies a fossil of a dinosaur’s skin—how does this fossil help scientists understand dinosaurs?",
    options: [
      "A) It shows what they ate",
      "B) It reveals their skin texture",
      "C) It tells how fast they ran",
      "D) It shows how they breathed",
    ],
    correctAnswer: "B",
    hint: "Think about what skin covers on your body.",
    correctAnswerExplanation:
      "A fossil of dinosaur skin shows scientists what the dinosaur’s skin texture was like, such as whether it was scaly or smooth. This helps them learn about how dinosaurs looked and lived.",
    incorrectAnswersExplanation: {
      A: "Skin fossils don’t show diet; teeth or stomach contents do.",
      C: "Speed is learned from bones and tracks, not skin.",
      D: "Breathing is studied through bones, not skin fossils.",
    },
    difficulty: "Hard",
    tags: ["biology", "dinosaur", "fossil"],
    timeEstimate: 90,
    webLink:
      "https://www.nationalgeographic.com/science/article/dinosaur-fossils",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "In a Wyoming forest, a wolf’s nose detects a deer—what part of the wolf’s body processes this smell?",
    options: ["A) Brain", "B) Lungs", "C) Heart", "D) Stomach"],
    correctAnswer: "A",
    hint: "Think about where signals from your nose go.",
    correctAnswerExplanation:
      "The brain processes smells by receiving signals from the wolf’s nose, helping it identify the deer. This allows the wolf to decide whether to hunt.",
    incorrectAnswersExplanation: {
      B: "Lungs are for breathing, not smelling.",
      C: "The heart pumps blood, not processes smells.",
      D: "The stomach digests food, not smells.",
    },
    difficulty: "Hard",
    tags: ["biology", "wolf", "brain"],
    timeEstimate: 90,
    webLink:
      "https://kids.nationalgeographic.com/science/article/how-your-brain-works",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Florida writes about a shark’s gills—how do gills help a shark survive?",
    options: [
      "A) They help it swim faster",
      "B) They let it breathe underwater",
      "C) They protect it from predators",
      "D) They help it find food",
    ],
    correctAnswer: "B",
    hint: "Think about how fish use water to live.",
    correctAnswerExplanation:
      "Gills allow a shark to breathe underwater by taking oxygen from the water as it flows over them. This helps the shark survive in the ocean.",
    incorrectAnswersExplanation: {
      A: "Swimming speed comes from fins and muscles, not gills.",
      C: "Gills don’t protect; skin and teeth help with that.",
      D: "Finding food is done with smell and senses, not gills.",
    },
    difficulty: "Hard",
    tags: ["biology", "shark", "gills"],
    timeEstimate: 90,
    webLink: "https://kids.nationalgeographic.com/animals/fish/facts/shark",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "During a school project in Texas, a student learns that a Velociraptor had feathers—why might it have had feathers?",
    options: [
      "A) To keep warm",
      "B) To swim better",
      "C) To eat plants",
      "D) To hear better",
    ],
    correctAnswer: "A",
    hint: "Think about what birds use feathers for besides flying.",
    correctAnswerExplanation:
      "Feathers helped Velociraptors stay warm by trapping heat close to their bodies, like a blanket. They also may have used feathers for display or balance.",
    incorrectAnswersExplanation: {
      B: "Velociraptors lived on land, not in water, so feathers weren’t for swimming.",
      C: "Feathers aren’t used for eating; teeth and claws helped with food.",
      D: "Hearing depends on ears, not feathers.",
    },
    difficulty: "Hard",
    tags: ["biology", "dinosaur", "feathers"],
    timeEstimate: 90,
    webLink:
      "https://www.nationalgeographic.com/science/article/dinosaur-fossils",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Michigan observes a caterpillar—what will it turn into after forming a chrysalis?",
    options: ["A) A frog", "B) A butterfly", "C) A bird", "D) A snake"],
    correctAnswer: "B",
    hint: "Think about what crawls and then flies.",
    correctAnswerExplanation:
      "A caterpillar forms a chrysalis and transforms into a butterfly through a process called metamorphosis. This is how it changes from a crawler to a flyer.",
    incorrectAnswersExplanation: {
      A: "Frogs come from tadpoles, not caterpillars.",
      C: "Birds hatch from eggs, not chrysalises.",
      D: "Snakes don’t come from caterpillars; they hatch from eggs.",
    },
    difficulty: "Hard",
    tags: ["biology", "butterfly", "metamorphosis"],
    timeEstimate: 90,
    webLink:
      "https://kids.nationalgeographic.com/animals/invertebrates/facts/monarch-butterfly",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "In a Colorado zoo, a student sees a snake shed its skin—why does a snake do this?",
    options: [
      "A) To grow bigger",
      "B) To change color",
      "C) To fly better",
      "D) To smell better",
    ],
    correctAnswer: "A",
    hint: "Think about why you outgrow clothes.",
    correctAnswerExplanation:
      "Snakes shed their skin to grow bigger because their skin doesn’t stretch like ours does. A new, larger skin forms underneath, and they shed the old one.",
    incorrectAnswersExplanation: {
      B: "Shedding doesn’t change a snake’s color; patterns stay the same.",
      C: "Snakes don’t fly, so shedding isn’t for flying.",
      D: "Smelling is done with the tongue, not skin.",
    },
    difficulty: "Hard",
    tags: ["biology", "snake", "shedding"],
    timeEstimate: 90,
    webLink: "https://kids.nationalgeographic.com/animals/reptiles/facts/snake",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Washington writes about a bear’s hibernation—what happens to a bear’s body during hibernation?",
    options: [
      "A) It grows feathers",
      "B) It slows its heart rate",
      "C) It changes color",
      "D) It grows gills",
    ],
    correctAnswer: "B",
    hint: "Think about what happens when you sleep for a long time.",
    correctAnswerExplanation:
      "During hibernation, a bear’s heart rate slows down to save energy while it sleeps through the winter. This helps it survive without eating for months.",
    incorrectAnswersExplanation: {
      A: "Bears don’t grow feathers; they have fur.",
      C: "Bears don’t change color during hibernation.",
      D: "Gills are for fish, not bears.",
    },
    difficulty: "Hard",
    tags: ["biology", "bear", "hibernation"],
    timeEstimate: 90,
    webLink:
      "https://kids.nationalgeographic.com/animals/mammals/facts/brown-bear",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "In a Utah museum, a student sees a fossil of a dinosaur egg—what does this tell scientists about dinosaurs?",
    options: [
      "A) They laid eggs",
      "B) They had fur",
      "C) They could fly",
      "D) They ate rocks",
    ],
    correctAnswer: "A",
    hint: "Think about what animals lay eggs today.",
    correctAnswerExplanation:
      "A fossilized dinosaur egg shows that dinosaurs laid eggs to reproduce, like birds and reptiles do today. This helps scientists understand how dinosaurs had babies.",
    incorrectAnswersExplanation: {
      B: "Eggs don’t show fur; fossils of skin or feathers do.",
      C: "Eggs don’t prove flying; wings would show that.",
      D: "Eggs don’t show diet; teeth or stomach contents do.",
    },
    difficulty: "Hard",
    tags: ["biology", "dinosaur", "egg"],
    timeEstimate: 90,
    webLink:
      "https://www.nationalgeographic.com/science/article/dinosaur-fossils",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Idaho learns that plants need sunlight—what happens if a plant doesn’t get enough sunlight?",
    options: [
      "A) It grows faster",
      "B) It makes less food",
      "C) It turns blue",
      "D) It grows roots",
    ],
    correctAnswer: "B",
    hint: "Think about what sunlight helps plants do.",
    correctAnswerExplanation:
      "Without enough sunlight, a plant can’t make enough food through photosynthesis, so it grows slowly or dies. Sunlight is like the plant’s energy source.",
    incorrectAnswersExplanation: {
      A: "Plants need sunlight to grow, so less light slows growth.",
      C: "Plants don’t turn blue; they may turn yellow or pale.",
      D: "Roots grow with water and nutrients, but sunlight affects food.",
    },
    difficulty: "Hard",
    tags: ["biology", "plant", "photosynthesis"],
    timeEstimate: 90,
    webLink:
      "https://www.sciencebuddies.org/stem-activities/leaf-photosynthesis",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Biology",
    grade: 6,
    questionType: "MC",
    question:
      "In a Nevada zoo, a student sees a lizard basking in the sun—why does the lizard need sunlight?",
    options: [
      "A) To make food",
      "B) To stay warm",
      "C) To grow feathers",
      "D) To see better",
    ],
    correctAnswer: "B",
    hint: "Think about why you feel warm in the sun.",
    correctAnswerExplanation:
      "Lizards are cold-blooded and need sunlight to warm their bodies so they can move and hunt. Basking in the sun raises their body temperature.",
    incorrectAnswersExplanation: {
      A: "Lizards don’t make food like plants; they eat other animals.",
      C: "Lizards have scales, not feathers.",
      D: "Sunlight doesn’t affect vision; eyes do that.",
    },
    difficulty: "Hard",
    tags: ["biology", "lizard", "thermoregulation"],
    timeEstimate: 90,
    webLink:
      "https://kids.nationalgeographic.com/animals/reptiles/facts/lizard",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "During a science fair in Texas, a student pushes a toy car with a force—how does the car move?",
    options: [
      "A) It stays still",
      "B) It moves forward",
      "C) It floats upward",
      "D) It spins in circles",
    ],
    correctAnswer: "B",
    hint: "Think about what happens when you push a wagon.",
    correctAnswerExplanation:
      "Pushing the toy car applies a force that makes it move forward in the direction of the push. This is because forces cause objects to move or change speed.",
    incorrectAnswersExplanation: {
      A: "If you push it, the car won’t stay still; it will move.",
      C: "Pushing doesn’t make it float; gravity keeps it down.",
      D: "Spinning requires a different kind of force, not a straight push.",
    },
    difficulty: "Medium",
    tags: ["physics", "force", "motion"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/toy-car-motion",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Colorado kicks a soccer ball—what happens to the ball’s energy when it stops rolling?",
    options: [
      "A) It disappears",
      "B) It turns into heat",
      "C) It becomes light",
      "D) It stays the same",
    ],
    correctAnswer: "B",
    hint: "Think about what happens when you rub your hands together.",
    correctAnswerExplanation:
      "When the soccer ball stops rolling, its moving energy turns into heat due to friction with the ground. This heat spreads into the air and ground.",
    incorrectAnswersExplanation: {
      A: "Energy doesn’t disappear; it changes form.",
      C: "The ball’s energy doesn’t turn into light.",
      D: "The energy changes, it doesn’t stay the same.",
    },
    difficulty: "Medium",
    tags: ["physics", "energy", "friction"],
    timeEstimate: 60,
    webLink:
      "https://www.sciencebuddies.org/stem-activities/energy-transformation",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "In a California classroom, a student shines a flashlight—what type of energy does the light have?",
    options: [
      "A) Sound energy",
      "B) Light energy",
      "C) Heat energy",
      "D) Motion energy",
    ],
    correctAnswer: "B",
    hint: "Think about what comes out of the flashlight.",
    correctAnswerExplanation:
      "The flashlight produces light energy, which lets you see in the dark. This energy comes from the batteries powering the bulb.",
    incorrectAnswersExplanation: {
      A: "Sound energy is for noises, not light.",
      C: "Heat energy makes things warm, not bright.",
      D: "Motion energy is for moving objects, not light.",
    },
    difficulty: "Medium",
    tags: ["physics", "light", "energy"],
    timeEstimate: 60,
    webLink:
      "https://www.sciencebuddies.org/stem-activities/flashlight-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Montana drops a dinosaur model off a table—what force pulls it to the ground?",
    options: ["A) Magnetism", "B) Gravity", "C) Friction", "D) Electricity"],
    correctAnswer: "B",
    hint: "Think about why things fall when you drop them.",
    correctAnswerExplanation:
      "Gravity is the force that pulls the dinosaur model to the ground when it’s dropped. It makes everything fall toward the Earth.",
    incorrectAnswersExplanation: {
      A: "Magnetism pulls metal objects, not plastic models.",
      C: "Friction slows things down, not pulls them down.",
      D: "Electricity powers devices, not causes falling.",
    },
    difficulty: "Medium",
    tags: ["physics", "gravity", "force"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/gravity-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "In a New York park, a dog pulls a sled—what force makes the sled harder to pull on grass?",
    options: ["A) Gravity", "B) Friction", "C) Magnetism", "D) Light"],
    correctAnswer: "B",
    hint: "Think about why it’s harder to slide on rough surfaces.",
    correctAnswerExplanation:
      "Friction is the force that makes the sled harder to pull on grass because the rough grass rubs against the sled, slowing it down. This force resists motion.",
    incorrectAnswersExplanation: {
      A: "Gravity pulls the sled down, not slows it forward.",
      C: "Magnetism only works with certain metals, not sleds.",
      D: "Light doesn’t affect how the sled moves.",
    },
    difficulty: "Medium",
    tags: ["physics", "friction", "force"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/friction-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Arizona rides a bike—what part of the bike uses energy to make it move?",
    options: ["A) Handlebars", "B) Pedals", "C) Seat", "D) Bell"],
    correctAnswer: "B",
    hint: "Think about what you push to make the bike go.",
    correctAnswerExplanation:
      "The pedals use energy from your legs to turn the bike’s wheels, making it move forward. This energy comes from your muscles.",
    incorrectAnswersExplanation: {
      A: "Handlebars steer the bike, not power it.",
      C: "The seat is for sitting, not moving the bike.",
      D: "The bell makes noise, not motion.",
    },
    difficulty: "Medium",
    tags: ["physics", "energy", "motion"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/bicycle-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "In a Florida classroom, a student learns about sound—how does sound travel from a barking dog to your ears?",
    options: [
      "A) Through light waves",
      "B) Through air vibrations",
      "C) Through heat waves",
      "D) Through gravity",
    ],
    correctAnswer: "B",
    hint: "Think about what happens when you clap your hands.",
    correctAnswerExplanation:
      "Sound travels as vibrations through the air, like when a dog’s bark makes the air shake and those vibrations reach your ears. This lets you hear the sound.",
    incorrectAnswersExplanation: {
      A: "Light waves carry light, not sound.",
      C: "Heat waves affect temperature, not sound.",
      D: "Gravity pulls objects, not carries sound.",
    },
    difficulty: "Medium",
    tags: ["physics", "sound", "vibrations"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/sound-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Wyoming throws a ball—what happens to the ball’s speed as it flies through the air?",
    options: [
      "A) It stays the same",
      "B) It gets faster",
      "C) It slows down",
      "D) It stops suddenly",
    ],
    correctAnswer: "C",
    hint: "Think about what happens when you toss something up.",
    correctAnswerExplanation:
      "The ball slows down as it flies because gravity pulls it down and air resistance pushes against it. Eventually, it falls back to the ground.",
    incorrectAnswersExplanation: {
      A: "The speed doesn’t stay the same; forces slow it.",
      B: "The ball doesn’t speed up on its own; gravity slows it.",
      D: "The ball doesn’t stop suddenly; it slows gradually.",
    },
    difficulty: "Medium",
    tags: ["physics", "motion", "gravity"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/projectile-motion",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "In a Texas park, a student sees a kite flying—what force keeps the kite in the air?",
    options: ["A) Friction", "B) Lift", "C) Magnetism", "D) Gravity"],
    correctAnswer: "B",
    hint: "Think about what makes airplanes stay up.",
    correctAnswerExplanation:
      "Lift is the force that keeps the kite in the air by pushing it up against gravity as the wind flows over it. This lets the kite soar high.",
    incorrectAnswersExplanation: {
      A: "Friction slows things down, not keeps them up.",
      C: "Magnetism doesn’t affect kites; it’s for metals.",
      D: "Gravity pulls the kite down, not up.",
    },
    difficulty: "Medium",
    tags: ["physics", "lift", "force"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/kite-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Michigan plays a guitar—what causes the strings to make different sounds?",
    options: [
      "A) Their color",
      "B) Their thickness",
      "C) Their length",
      "D) Their smell",
    ],
    correctAnswer: "B",
    hint: "Think about what makes a big drum sound different from a small one.",
    correctAnswerExplanation:
      "The thickness of guitar strings affects the sound they make; thicker strings produce lower sounds, and thinner strings make higher sounds. This is because they vibrate differently.",
    incorrectAnswersExplanation: {
      A: "Color doesn’t affect sound; it’s just how strings look.",
      C: "Length can change pitch, but thickness is the main factor here.",
      D: "Smell has nothing to do with sound production.",
    },
    difficulty: "Medium",
    tags: ["physics", "sound", "vibrations"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/guitar-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "In a Nevada classroom, a student learns about a car’s speed—what tool measures how fast a car is going?",
    options: ["A) Thermometer", "B) Speedometer", "C) Barometer", "D) Ruler"],
    correctAnswer: "B",
    hint: "Think about what you see on a car’s dashboard.",
    correctAnswerExplanation:
      "A speedometer measures how fast a car is going by showing its speed in miles per hour. This helps drivers know if they’re going too fast or too slow.",
    incorrectAnswersExplanation: {
      A: "A thermometer measures temperature, not speed.",
      C: "A barometer measures air pressure, not speed.",
      D: "A ruler measures length, not speed.",
    },
    difficulty: "Hard",
    tags: ["physics", "speed", "measurement"],
    timeEstimate: 90,
    webLink: "https://www.sciencebuddies.org/stem-activities/speed-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Oregon sees a rainbow after a storm—what causes the colors in a rainbow?",
    options: [
      "A) Sound waves bending",
      "B) Light bending in water droplets",
      "C) Heat rising from the ground",
      "D) Gravity pulling colors apart",
    ],
    correctAnswer: "B",
    hint: "Think about what happens to light in a prism.",
    correctAnswerExplanation:
      "A rainbow forms when sunlight bends, or refracts, in water droplets, splitting into different colors. Each color bends at a slightly different angle, creating the rainbow.",
    incorrectAnswersExplanation: {
      A: "Sound waves don’t make colors; they make noise.",
      C: "Heat doesn’t create rainbows; it affects temperature.",
      D: "Gravity doesn’t split colors; it pulls objects down.",
    },
    difficulty: "Hard",
    tags: ["physics", "light", "refraction"],
    timeEstimate: 90,
    webLink: "https://www.sciencebuddies.org/stem-activities/rainbow-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "In a Washington park, a student flies a drone—what force makes the drone hover in place?",
    options: ["A) Friction", "B) Gravity", "C) Lift", "D) Magnetism"],
    correctAnswer: "C",
    hint: "Think about what keeps a helicopter in the air.",
    correctAnswerExplanation:
      "Lift is the force created by the drone’s spinning blades, pushing it up to hover against gravity. This balances the drone in the air.",
    incorrectAnswersExplanation: {
      A: "Friction slows motion, not helps hovering.",
      B: "Gravity pulls the drone down, not keeps it up.",
      D: "Magnetism doesn’t affect drones; it’s for metals.",
    },
    difficulty: "Hard",
    tags: ["physics", "lift", "force"],
    timeEstimate: 90,
    webLink: "https://www.sciencebuddies.org/stem-activities/drone-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Idaho learns about magnets—what happens when two north poles of magnets are pushed together?",
    options: [
      "A) They stick together",
      "B) They push apart",
      "C) They spin around",
      "D) They disappear",
    ],
    correctAnswer: "B",
    hint: "Think about what happens when you try to push two like things together.",
    correctAnswerExplanation:
      "Two north poles of magnets push apart because like poles repel each other. This is a rule of magnetism: like repels, unlike attracts.",
    incorrectAnswersExplanation: {
      A: "Like poles don’t stick; they repel.",
      C: "Magnets don’t spin unless another force acts on them.",
      D: "Magnets don’t disappear; they just move apart.",
    },
    difficulty: "Hard",
    tags: ["physics", "magnetism", "force"],
    timeEstimate: 90,
    webLink: "https://www.sciencebuddies.org/stem-activities/magnet-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "In a Utah classroom, a student learns about a roller coaster—what force makes the coaster speed up as it goes downhill?",
    options: ["A) Friction", "B) Gravity", "C) Magnetism", "D) Light"],
    correctAnswer: "B",
    hint: "Think about what pulls you down a slide.",
    correctAnswerExplanation:
      "Gravity pulls the roller coaster downhill, making it speed up as it falls. This force turns potential energy into motion energy.",
    incorrectAnswersExplanation: {
      A: "Friction slows the coaster, not speeds it up.",
      C: "Magnetism isn’t used in most coasters for speed.",
      D: "Light doesn’t affect the coaster’s motion.",
    },
    difficulty: "Hard",
    tags: ["physics", "gravity", "energy"],
    timeEstimate: 90,
    webLink:
      "https://www.sciencebuddies.org/stem-activities/roller-coaster-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Virginia sees a shadow of a dinosaur model—what causes the shadow to form?",
    options: [
      "A) Light bending around the model",
      "B) Light being blocked by the model",
      "C) Heat from the model",
      "D) Sound from the model",
    ],
    correctAnswer: "B",
    hint: "Think about what happens when you stand in front of a light.",
    correctAnswerExplanation:
      "A shadow forms when the dinosaur model blocks light, stopping it from reaching the ground behind it. This creates a dark area shaped like the model.",
    incorrectAnswersExplanation: {
      A: "Light doesn’t bend to make shadows; it travels straight.",
      C: "Heat doesn’t create shadows; light does.",
      D: "Sound doesn’t affect shadows; it’s about light.",
    },
    difficulty: "Hard",
    tags: ["physics", "light", "shadow"],
    timeEstimate: 90,
    webLink: "https://www.sciencebuddies.org/stem-activities/shadow-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "In a Minnesota classroom, a student learns about electricity—what material lets electricity flow easily?",
    options: ["A) Rubber", "B) Copper", "C) Plastic", "D) Wood"],
    correctAnswer: "B",
    hint: "Think about what wires are made of.",
    correctAnswerExplanation:
      "Copper is a metal that lets electricity flow easily, which is why it’s used in wires. This makes it a good conductor of electricity.",
    incorrectAnswersExplanation: {
      A: "Rubber blocks electricity; it’s an insulator.",
      C: "Plastic doesn’t conduct electricity; it’s used for insulation.",
      D: "Wood doesn’t let electricity flow well; it’s not a conductor.",
    },
    difficulty: "Hard",
    tags: ["physics", "electricity", "conductor"],
    timeEstimate: 90,
    webLink:
      "https://www.sciencebuddies.org/stem-activities/electricity-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "A student in New Mexico sees a hot air balloon—what makes the balloon rise?",
    options: [
      "A) Cold air inside the balloon",
      "B) Hot air inside the balloon",
      "C) Heavy weights inside",
      "D) Strong magnets inside",
    ],
    correctAnswer: "B",
    hint: "Think about what happens to air when it’s heated.",
    correctAnswerExplanation:
      "Hot air inside the balloon is lighter than the cooler air outside, so the balloon rises. This is because hot air is less dense and floats upward.",
    incorrectAnswersExplanation: {
      A: "Cold air is heavier and would make the balloon sink.",
      C: "Heavy weights would pull the balloon down, not up.",
      D: "Magnets don’t affect air or make balloons rise.",
    },
    difficulty: "Hard",
    tags: ["physics", "heat", "density"],
    timeEstimate: 90,
    webLink:
      "https://www.sciencebuddies.org/stem-activities/hot-air-balloon-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "In a Missouri park, a student swings on a swing—what force slows the swing down over time?",
    options: ["A) Gravity", "B) Friction", "C) Magnetism", "D) Light"],
    correctAnswer: "B",
    hint: "Think about what happens when you slide on a rough surface.",
    correctAnswerExplanation:
      "Friction between the swing’s chains and the air, and at the pivot point, slows the swing down over time. This force resists the swing’s motion.",
    incorrectAnswersExplanation: {
      A: "Gravity affects the swing’s direction, not slows it over time.",
      C: "Magnetism doesn’t affect swings; it’s for metals.",
      D: "Light doesn’t slow motion; it’s about energy.",
    },
    difficulty: "Hard",
    tags: ["physics", "friction", "motion"],
    timeEstimate: 90,
    webLink: "https://www.sciencebuddies.org/stem-activities/swing-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Physics",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Alabama learns about lenses—what does a convex lens do to light?",
    options: [
      "A) Spreads it out",
      "B) Blocks it completely",
      "C) Bends it to a point",
      "D) Turns it into sound",
    ],
    correctAnswer: "C",
    hint: "Think about how a magnifying glass focuses light.",
    correctAnswerExplanation:
      "A convex lens bends light rays to a point, focusing them, like when a magnifying glass makes a bright spot. This is why lenses are used in glasses and microscopes.",
    incorrectAnswersExplanation: {
      A: "Spreading light is done by concave lenses, not convex.",
      B: "Lenses don’t block light; they bend it.",
      D: "Light doesn’t turn into sound; they’re different energies.",
    },
    difficulty: "Hard",
    tags: ["physics", "light", "lens"],
    timeEstimate: 90,
    webLink: "https://www.sciencebuddies.org/stem-activities/lens-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "In a Texas classroom, a student mixes baking soda and vinegar—what gas makes the bubbles?",
    options: ["A) Oxygen", "B) Carbon dioxide", "C) Nitrogen", "D) Helium"],
    correctAnswer: "B",
    hint: "Think about what gas plants use to grow.",
    correctAnswerExplanation:
      "When baking soda and vinegar mix, they react to produce carbon dioxide gas, which forms bubbles. This is a chemical reaction that releases the gas.",
    incorrectAnswersExplanation: {
      A: "Oxygen is in the air, but not made in this reaction.",
      C: "Nitrogen is common in air, but not produced here.",
      D: "Helium fills balloons, but isn’t made by this mixture.",
    },
    difficulty: "Medium",
    tags: ["chemistry", "reaction", "gas"],
    timeEstimate: 60,
    webLink:
      "https://www.sciencebuddies.org/stem-activities/baking-soda-vinegar",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Florida sees ice melt in a glass—what is this change called?",
    options: ["A) Freezing", "B) Melting", "C) Boiling", "D) Condensing"],
    correctAnswer: "B",
    hint: "Think about what happens to ice in the sun.",
    correctAnswerExplanation:
      "Melting is when ice changes from a solid to a liquid as it warms up. This happens because the heat makes the ice’s particles move faster.",
    incorrectAnswersExplanation: {
      A: "Freezing is when liquid turns to solid, the opposite of melting.",
      C: "Boiling turns liquid to gas, not solid to liquid.",
      D: "Condensing is gas turning to liquid, not solid to liquid.",
    },
    difficulty: "Medium",
    tags: ["chemistry", "states of matter", "melting"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/states-of-matter",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "In a Colorado kitchen, a student sees sugar dissolve in water—what type of change is this?",
    options: [
      "A) Chemical change",
      "B) Physical change",
      "C) Magnetic change",
      "D) Electrical change",
    ],
    correctAnswer: "B",
    hint: "Think about whether the sugar is still sugar after dissolving.",
    correctAnswerExplanation:
      "Dissolving sugar in water is a physical change because the sugar doesn’t turn into something new; it just spreads out in the water. You could evaporate the water to get the sugar back.",
    incorrectAnswersExplanation: {
      A: "A chemical change makes a new substance, but sugar stays sugar.",
      C: "Magnetism isn’t involved in dissolving.",
      D: "Electricity isn’t needed to dissolve sugar.",
    },
    difficulty: "Medium",
    tags: ["chemistry", "physical change", "dissolving"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/dissolving-sugar",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Montana finds a rusty nail—what caused the rust to form?",
    options: [
      "A) Sugar and water",
      "B) Oxygen and water",
      "C) Sand and heat",
      "D) Light and air",
    ],
    correctAnswer: "B",
    hint: "Think about what happens to metal left outside.",
    correctAnswerExplanation:
      "Rust forms when iron in the nail reacts with oxygen and water, creating iron oxide, which is rust. This is a chemical change that damages the metal.",
    incorrectAnswersExplanation: {
      A: "Sugar and water don’t cause rust; they’re not reactive with iron.",
      C: "Sand and heat don’t make rust; they’re unrelated.",
      D: "Light doesn’t cause rust; oxygen and water do.",
    },
    difficulty: "Medium",
    tags: ["chemistry", "rust", "chemical change"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/rust-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "In a New York classroom, a student learns about water—what is water made of?",
    options: [
      "A) Sugar and salt",
      "B) Hydrogen and oxygen",
      "C) Carbon and nitrogen",
      "D) Iron and copper",
    ],
    correctAnswer: "B",
    hint: "Think about the chemical formula H2O.",
    correctAnswerExplanation:
      "Water is made of two hydrogen atoms and one oxygen atom, bonded together to form H2O. This makes water a compound.",
    incorrectAnswersExplanation: {
      A: "Sugar and salt dissolve in water, but aren’t part of it.",
      C: "Carbon and nitrogen make other compounds, not water.",
      D: "Iron and copper are metals, not in water’s formula.",
    },
    difficulty: "Medium",
    tags: ["chemistry", "water", "compound"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/water-chemistry",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Arizona sees a candle burn—what new substance is made when the wax burns?",
    options: ["A) Sugar", "B) Carbon dioxide", "C) Salt", "D) Nitrogen"],
    correctAnswer: "B",
    hint: "Think about what comes out when you blow out a candle.",
    correctAnswerExplanation:
      "When a candle burns, the wax reacts with oxygen to produce carbon dioxide and water vapor. This is a chemical change that releases energy as light and heat.",
    incorrectAnswersExplanation: {
      A: "Sugar isn’t made by burning; it’s a different substance.",
      C: "Salt isn’t produced by burning wax.",
      D: "Nitrogen is in the air, not made by the candle.",
    },
    difficulty: "Medium",
    tags: ["chemistry", "combustion", "carbon dioxide"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/candle-chemistry",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "In a California kitchen, a student sees water boil—what is the water turning into?",
    options: ["A) Ice", "B) Steam", "C) Salt", "D) Sugar"],
    correctAnswer: "B",
    hint: "Think about what you see above a pot of boiling water.",
    correctAnswerExplanation:
      "When water boils, it turns into steam, which is water in its gas form. This happens because heat makes the water particles move fast enough to become a gas.",
    incorrectAnswersExplanation: {
      A: "Ice is water as a solid, formed by cooling, not heating.",
      C: "Salt doesn’t form from boiling water; it stays behind.",
      D: "Sugar isn’t made by boiling; it’s a different substance.",
    },
    difficulty: "Medium",
    tags: ["chemistry", "states of matter", "boiling"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/states-of-matter",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Wyoming mixes salt and water—what happens to the salt?",
    options: [
      "A) It burns",
      "B) It dissolves",
      "C) It freezes",
      "D) It explodes",
    ],
    correctAnswer: "B",
    hint: "Think about what happens when you stir salt into soup.",
    correctAnswerExplanation:
      "The salt dissolves in the water, spreading out evenly so you can’t see it anymore. This is a physical change, and the salt is still there.",
    incorrectAnswersExplanation: {
      A: "Salt doesn’t burn in water; it’s not flammable.",
      C: "Freezing requires cold, not just mixing with water.",
      D: "Salt and water don’t cause explosions; they mix safely.",
    },
    difficulty: "Medium",
    tags: ["chemistry", "dissolving", "physical change"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/dissolving-salt",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "In a Michigan classroom, a student learns about air—what is the main gas in the air we breathe?",
    options: ["A) Oxygen", "B) Nitrogen", "C) Carbon dioxide", "D) Helium"],
    correctAnswer: "B",
    hint: "Think about the gas that makes up most of Earth’s atmosphere.",
    correctAnswerExplanation:
      "Nitrogen is the main gas in the air, making up about 78% of the atmosphere. We breathe it in, but our bodies use oxygen more.",
    incorrectAnswersExplanation: {
      A: "Oxygen is about 21% of the air, not the main gas.",
      C: "Carbon dioxide is a small part of the air, not the main one.",
      D: "Helium is rare in air; it’s used in balloons.",
    },
    difficulty: "Medium",
    tags: ["chemistry", "air", "nitrogen"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/air-composition",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Virginia sees a balloon float—what gas makes the balloon rise?",
    options: ["A) Oxygen", "B) Carbon dioxide", "C) Helium", "D) Nitrogen"],
    correctAnswer: "C",
    hint: "Think about what’s lighter than air.",
    correctAnswerExplanation:
      "Helium is a gas lighter than air, so it makes the balloon float by lifting it upward. This is why party balloons rise.",
    incorrectAnswersExplanation: {
      A: "Oxygen is heavier and doesn’t make balloons float.",
      B: "Carbon dioxide is heavier than air, so it sinks.",
      D: "Nitrogen is part of air and doesn’t lift balloons.",
    },
    difficulty: "Medium",
    tags: ["chemistry", "helium", "density"],
    timeEstimate: 60,
    webLink: "https://www.sciencebuddies.org/stem-activities/balloon-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "In a Nevada classroom, a student learns about acids—what is an example of an acid in your kitchen?",
    options: ["A) Sugar", "B) Vinegar", "C) Salt", "D) Water"],
    correctAnswer: "B",
    hint: "Think about something sour you might taste.",
    correctAnswerExplanation:
      "Vinegar is an acid found in the kitchen, often used in cooking or cleaning. It has a sour taste and can react with other substances, like baking soda.",
    incorrectAnswersExplanation: {
      A: "Sugar is sweet, not an acid.",
      C: "Salt is neutral, not acidic.",
      D: "Water is neutral, not an acid.",
    },
    difficulty: "Hard",
    tags: ["chemistry", "acid", "vinegar"],
    timeEstimate: 90,
    webLink: "https://www.sciencebuddies.org/stem-activities/acid-base-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Oregon sees a car battery—what type of substance is inside that helps it work?",
    options: ["A) Sugar syrup", "B) Acid", "C) Saltwater", "D) Oil"],
    correctAnswer: "B",
    hint: "Think about what reacts to make electricity.",
    correctAnswerExplanation:
      "Car batteries contain an acid, like sulfuric acid, that reacts with metal plates to produce electricity. This powers the car’s engine and lights.",
    incorrectAnswersExplanation: {
      A: "Sugar syrup doesn’t conduct electricity or power batteries.",
      C: "Saltwater conducts some electricity, but it’s not used in car batteries.",
      D: "Oil lubricates, not powers batteries.",
    },
    difficulty: "Hard",
    tags: ["chemistry", "acid", "battery"],
    timeEstimate: 90,
    webLink: "https://www.sciencebuddies.org/stem-activities/battery-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "In a Washington classroom, a student learns about burning wood—what is needed for the wood to burn?",
    options: ["A) Sugar", "B) Oxygen", "C) Nitrogen", "D) Helium"],
    correctAnswer: "B",
    hint: "Think about what a fire needs to keep going.",
    correctAnswerExplanation:
      "Wood needs oxygen to burn because burning is a chemical reaction where oxygen combines with the wood to produce heat and light. Without oxygen, the fire goes out.",
    incorrectAnswersExplanation: {
      A: "Sugar doesn’t help wood burn; it’s not part of the reaction.",
      C: "Nitrogen is in the air but doesn’t help burning.",
      D: "Helium doesn’t support burning; it’s used in balloons.",
    },
    difficulty: "Hard",
    tags: ["chemistry", "combustion", "oxygen"],
    timeEstimate: 90,
    webLink: "https://www.sciencebuddies.org/stem-activities/fire-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Idaho sees frost on a window—what caused the frost to form?",
    options: [
      "A) Water vapor freezing",
      "B) Sugar crystallizing",
      "C) Salt dissolving",
      "D) Oil evaporating",
    ],
    correctAnswer: "A",
    hint: "Think about what happens to water in cold weather.",
    correctAnswerExplanation:
      "Frost forms when water vapor in the air turns directly into ice on a cold surface, like a window. This happens because the cold temperature freezes the vapor.",
    incorrectAnswersExplanation: {
      B: "Sugar doesn’t form frost; it’s not in the air.",
      C: "Salt doesn’t create frost; it dissolves in water.",
      D: "Oil doesn’t evaporate to form frost; it’s not water-based.",
    },
    difficulty: "Hard",
    tags: ["chemistry", "states of matter", "frost"],
    timeEstimate: 90,
    webLink: "https://www.sciencebuddies.org/stem-activities/frost-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "In a Utah classroom, a student learns about metals—what property makes metals shiny?",
    options: [
      "A) Their density",
      "B) Their ability to reflect light",
      "C) Their taste",
      "D) Their smell",
    ],
    correctAnswer: "B",
    hint: "Think about why a spoon looks glossy.",
    correctAnswerExplanation:
      "Metals are shiny because they reflect light well, making them look bright and polished. This property is why metals like silver and gold are used in jewelry.",
    incorrectAnswersExplanation: {
      A: "Density affects weight, not shininess.",
      C: "Taste doesn’t affect how metals look.",
      D: "Smell isn’t related to a metal’s appearance.",
    },
    difficulty: "Hard",
    tags: ["chemistry", "metals", "properties"],
    timeEstimate: 90,
    webLink: "https://www.sciencebuddies.org/stem-activities/metal-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
  {
    subject: "Science",
    topic: "Chemistry",
    grade: 6,
    questionType: "MC",
    question:
      "A student in Virginia sees a puddle evaporate—what happens to the water molecules?",
    options: [
      "A) They turn into salt",
      "B) They move into the air",
      "C) They freeze into ice",
      "D) They burn away",
    ],
    correctAnswer: "B",
    hint: "Think about where water goes when it dries up.",
    correctAnswerExplanation:
      "When a puddle evaporates, water molecules gain energy from heat and move into the air as water vapor. This is a physical change from liquid to gas.",
    incorrectAnswersExplanation: {
      A: "Water doesn’t turn into salt; it’s a different substance.",
      C: "Freezing requires cold, not heat like evaporation.",
      D: "Water doesn’t burn; it turns into vapor.",
    },
    difficulty: "Hard",
    tags: ["chemistry", "evaporation", "states of matter"],
    timeEstimate: 90,
    webLink:
      "https://www.sciencebuddies.org/stem-activities/evaporation-science",
    source: "ChatGPT",
    lastUpdated: "2025-04-23",
  },
];

export default scienceGrade6Questions;
